"use client";
import Link from "next/link";
import { useEffect,useRef,useState } from "react";
import type { NutritionDayState } from "@/content/mindfulNutritionTracker";
import MindfulNutritionOverview from "./MindfulNutritionOverview";
import MindfulNutritionDayForm from "./MindfulNutritionDayForm";
import NutritionSummaryReport from "./NutritionSummaryReport";
type SaveState="idle"|"saving"|"saved"|"error";
export default function MindfulNutritionClient({accessToken}:{accessToken:string}){const [days,setDays]=useState<Record<number,NutritionDayState>>({}),[selected,setSelected]=useState<number|null>(null),[loading,setLoading]=useState(true),[save,setSave]=useState<Record<number,SaveState>>({});const timers=useRef<Record<number,ReturnType<typeof setTimeout>>>({});useEffect(()=>{fetch(`/api/mindful-nutrition/${accessToken}`).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(result=>{const mapped:Record<number,NutritionDayState>={};result.days.forEach((x:NutritionDayState&{dayNumber:number})=>mapped[x.dayNumber]={data:x.data,isCompleted:x.isCompleted,completedAt:x.completedAt});setDays(mapped)}).finally(()=>setLoading(false))},[accessToken]);const completed=Object.values(days).filter(x=>x.isCompleted).length;async function saveDay(day:number,data:Record<string,unknown>){setSave(s=>({...s,[day]:"saving"}));try{const r=await fetch(`/api/mindful-nutrition/${accessToken}/day/${day}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({data})});if(!r.ok)throw new Error();setSave(s=>({...s,[day]:"saved"}))}catch{setSave(s=>({...s,[day]:"error"}))}}function update(day:number,key:string,value:unknown){const data={...(days[day]?.data??{}),[key]:value};setDays(current=>({...current,[day]:{data,isCompleted:current[day]?.isCompleted??false,completedAt:current[day]?.completedAt??null}}));setSave(s=>({...s,[day]:"saving"}));clearTimeout(timers.current[day]);timers.current[day]=setTimeout(()=>saveDay(day,data),500)}async function complete(day:number){clearTimeout(timers.current[day]);const data=days[day]?.data??{};setSave(s=>({...s,[day]:"saving"}));try{const r=await fetch(`/api/mindful-nutrition/${accessToken}/day/${day}/complete`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({data})});if(!r.ok)throw new Error();const result=await r.json();setDays(current=>({...current,[day]:{data,isCompleted:true,completedAt:result.completedAt}}));setSave(s=>({...s,[day]:"saved"}));setSelected(day<7?day+1:null)}catch{setSave(s=>({...s,[day]:"error"}))}}if(loading)return <main className="nutrition-loading">正在準備你的營養追蹤器…</main>;return <div className="nutrition-app"><header className="nutrition-header"><div><Link href={`/access/${accessToken}`}>← 回到工具包</Link><span>{completed} / 7 天完成</span></div><div><i style={{width:`${completed/7*100}%`}}/></div></header>{selected?<MindfulNutritionDayForm day={selected} state={days[selected]??{data:{},isCompleted:false,completedAt:null}} saveState={save[selected]??"idle"} onChange={(key,value)=>update(selected,key,value)} onSave={()=>saveDay(selected,days[selected]?.data??{})} onComplete={()=>complete(selected)} onSelect={setSelected} onOverview={()=>setSelected(null)}/>:<main className="nutrition-overview"><MindfulNutritionOverview days={days} onSelect={setSelected}/><NutritionSummaryReport days={days} accessToken={accessToken}/></main>}</div>}
