export type RiskLevel="low"|"medium"|"high";
export type Confidence="low"|"medium"|"high";
export type AnalysisResult={primaryResult:string;riskLevel:RiskLevel;confidence:Confidence;score?:number;tags:string[];explanation:string;insight:string;suggestedAction:string;nextStepHint:string;[key:string]:any};
const list=(v:unknown)=>Array.isArray(v)?v.map(String):[];
const num=(v:unknown)=>Math.max(0,Math.min(10,Number(v)||0));
const risk10=(n:number):RiskLevel=>n<=3?"low":n<=6?"medium":"high";
const confidence=(required:number,present:number):Confidence=>present>=required?"high":present>=Math.ceil(required/2)?"medium":"low";
const insufficient=(extra:Record<string,unknown>={}):AnalysisResult=>({primaryResult:"目前線索還不夠完整",riskLevel:"low",confidence:"low",tags:["資料待補"],explanation:"目前線索還不夠完整，先完成這一關的必要選項與評分，系統才會進一步分析。",insight:"資料不足時不會做過度推論。",suggestedAction:"先補齊本關資料。",nextStepHint:"完成輸入後會即時更新分析。",...extra});

export function analyzeLevel1TimeFog(input:any):AnalysisResult{
 const times=list(input.selectedTimes),craving=num(input.cravingScore),hunger=num(input.hungerScore),fatigue=num(input.fatigueScore),stress=num(input.stressScore);
 if(!times.length)return insufficient({highRiskTime:"",timePatternType:"unclear",timeRiskScore:0});
 const score=Math.round(craving*.35+fatigue*.25+stress*.25+hunger*.15),hits:string[]=[];
 if(times.some(x=>["下午 3～5 點","下班前"].includes(x))&&fatigue>=6)hits.push("afternoonCrash");
 if(times.includes("晚餐前")&&hunger>=6)hits.push("dinnerBeforeCrash");
 if(times.some(x=>["晚餐後","睡前"].includes(x))&&craving>=6&&hunger<=5)hits.push("afterDinnerHabit");
 if(stress>=7&&craving>=6)hits.push("stressTime");
 const pattern=hits.length>1?"mixed":hits[0]||"unclear",copy:Record<string,[string,string]>={afternoonCrash:["下午耗電型","你的嘴饞時間熱區偏向下午耗電型。白天能量下降時，身體可能想用甜食、飲料或零食快速補電。"],dinnerBeforeCrash:["晚餐前爆餓型","你的嘴饞時間熱區偏向晚餐前爆餓型。白天吃得不夠穩，到了晚餐前已經太餓，選擇能力容易下降。"],afterDinnerHabit:["晚餐後習慣型","你的嘴饞時間熱區偏向晚餐後習慣型。這比較像儀式感、放鬆需求或固定習慣，不一定是真的餓。"],stressTime:["壓力觸發型","你的嘴饞時間熱區偏向壓力觸發型。食物或飲料可能成為壓力累積後的快速出口。"],mixed:["複合時間型","你的嘴饞時間不是單一原因，可能同時受到疲憊、壓力與飢餓影響。後面幾關會繼續拆解主要觸發線索。"],unclear:["尚待觀察型","目前沒有單一訊號特別突出，建議再觀察一次相同時段的身體與情緒狀態。"]};
 const actions:Record<string,string>={afternoonCrash:"明天先準備一個下午補給：無糖豆漿、茶葉蛋、優格或無糖拿鐵，避免直接靠甜飲撐精神。",dinnerBeforeCrash:"明天避免晚餐前空太久，下午先補水與蛋白質。",afterDinnerHabit:"今晚固定一個晚餐後收尾動作，例如泡熱茶、刷牙或離開零食區。",stressTime:"下一次嘴饞前先做 3 分鐘身心連結，降低壓力強度後再決定。",mixed:"先處理分數最高的訊號，並持續記錄相同時段。",unclear:"再記錄一次嘴饞時段與四項分數。"};
 return {primaryResult:copy[pattern][0],riskLevel:risk10(score),confidence:hits.length?"high":"medium",score,tags:hits.length?hits:["unclear"],explanation:copy[pattern][1],insight:`加權風險為 ${score}/10；嘴饞影響 35%、疲憊與壓力各 25%、飢餓 15%。`,suggestedAction:actions[pattern],nextStepHint:"下一關會確認這個時間熱區最常出現在哪個場景。",highRiskTime:String(input.primaryTime||times[0]),timePatternType:pattern,timeRiskScore:score,sourceScores:{craving,hunger,fatigue,stress}};
}

export function analyzeLevel2SceneMaze(input:any):AnalysisResult{
 const scenes=list(input.selectedScenes),triggers=list(input.selectedTriggers);if(!scenes.length||!triggers.length)return insufficient({highRiskScenes:scenes,triggerType:"unclear"});
 const groups={environmentLoop:["看到食物","聞到味道","食物放太近","手機跳外送通知"],emotionalLoop:["壓力很大","想獎勵自己"],bodyLoop:["太累","晚餐吃太少"],habitLoop:["太無聊","追劇時","跟別人一起吃"]};
 const scores=Object.fromEntries(Object.entries(groups).map(([k,items])=>[k,triggers.filter(x=>items.includes(x)).length]));if(scenes.includes("追劇時"))scores.habitLoop++;if(scenes.includes("家裡沙發"))scores.habitLoop++;
 const max=Math.max(...Object.values(scores)),winners=Object.entries(scores).filter(([,v])=>v===max&&v>0).map(([k])=>k),type=winners.length===1?winners[0]:"mixedLoop";
 const explanations:Record<string,string>={environmentLoop:"你的嘴饞比較像環境觸發型。食物位置、外送通知、超商路線或視覺刺激，會比想像中更容易啟動嘴饞。",emotionalLoop:"你的嘴饞比較像情緒安慰型。壓力或想獎勵自己時，食物與飲料可能被大腦當成快速安撫工具。",bodyLoop:"你的嘴饞比較像身體補償型。疲憊、太餓或晚餐吃太少，會讓特定場景更容易失控。",habitLoop:"你的嘴饞比較像習慣迴路型。固定場景容易自動連結固定行為，例如沙發、追劇與零食。",mixedLoop:"你的場景觸發比較複合，可能同時包含環境、情緒、身體與習慣因素。"};
 const suggestions:string[]=[];if(scenes.includes("家裡沙發")&&triggers.includes("食物放太近"))suggestions.push("今晚先把零食移出視線，沙發旁只放水或無糖茶");if(scenes.includes("超商"))suggestions.push("進超商前先決定兩個品項，例如茶葉蛋＋無糖豆漿");if(scenes.includes("外送 App"))suggestions.push("建立固定外送備案，移除甜點與含糖飲預設選項");if(scenes.includes("手搖飲店"))suggestions.push("把點餐話術固定成小杯、微糖、不加料");if(!suggestions.length)suggestions.push(type==="environmentLoop"?"先移除最常看見的食物或通知":"先替高風險場景安排一個替代動作");
 return {primaryResult:({environmentLoop:"環境觸發型",emotionalLoop:"情緒安慰型",bodyLoop:"身體補償型",habitLoop:"習慣迴路型",mixedLoop:"複合場景型"} as any)[type],riskLevel:triggers.length>=3?"high":"medium",confidence:confidence(2,Number(Boolean(scenes.length))+Number(Boolean(triggers.length))),tags:[type,...triggers],explanation:explanations[type],insight:`主要類別計數：環境 ${scores.environmentLoop}、情緒 ${scores.emotionalLoop}、身體 ${scores.bodyLoop}、習慣 ${scores.habitLoop}。`,suggestedAction:suggestions.join("；")+"。",nextStepHint:"下一關會分辨場景出現時，身體與情緒真正發出的訊號。",highRiskScenes:scenes,triggerType:type,triggerCategoryScores:scores,sceneTriggerCombination:[...scenes,...triggers].join("＋"),suggestedEnvironmentChange:suggestions};
}

export function analyzeLevel3SignalDecoder(input:any):AnalysisResult{
 const stomach=num(input.stomachScore),fatigue=num(input.fatigueScore),stress=num(input.emotionStressScore),specific=num(input.specificFoodCravingScore),hunger=num(input.trueHungerScore),selected=String(input.selectedState||"");if(!selected)return insufficient({decodedSignalType:"unclear",signalScores:{}});
 const scores={trueHunger:Math.max(0,stomach*.4+hunger*.4-specific*.2),fatigueCraving:fatigue*.6+stomach*.2+hunger*.2,stressCraving:stress*.6+specific*.3+fatigue*.1,specificCraving:specific*.6+stress*.2+fatigue*.2};
 const sorted=Object.entries(scores).sort((a,b)=>b[1]-a[1]),mixed=sorted[0][1]-sorted[1][1]<1;let type=mixed?"mixedSignal":sorted[0][0];if(selected.includes("累")&&fatigue>=7)type="fatigueCraving";else if(selected.includes("壓力")&&stress>=7)type="stressCraving";else if(selected.includes("真的餓")&&hunger>=6&&stomach>=5)type="trueHunger";else if(!mixed&&hunger>=6&&stomach>=5&&scores.trueHunger>=sorted[0][1])type="trueHunger";else if(!mixed&&fatigue>=7)type="fatigueCraving";else if(!mixed&&stress>=7)type="stressCraving";else if(!mixed&&specific>=7&&hunger<=5)type="specificCraving";
 const copy:Record<string,[string,string,string]>={trueHunger:["真餓型訊號","這次比較偏向真的餓。你不需要硬忍，重點是先選擇較穩的正常餐食。","先吃蛋白質＋蔬菜＋適量澱粉，不要只靠零食或水果撐。"],fatigueCraving:["疲憊型嘴饞","大腦可能在尋找快速補電，所以特別想吃甜、鹹或重口味。","先喝水、補一份蛋白質點心，休息 5 分鐘後再決定。"],stressCraving:["壓力型嘴饞","食物或飲料可能正在扮演快速放鬆的角色。","先做 3 分鐘身心連結或 10 分鐘急救流程。"],specificCraving:["特定食物觸發","這不一定是真的餓，比較像味道、口感或習慣被啟動。","先選海苔、毛豆、優格或水果一份，並先分裝。"],mixedSignal:["混合型訊號","最高兩項訊號差距不到 1 分，代表身體與情緒可能同時影響這次嘴饞。","先喝水並停 3 分鐘，再處理分數最高的兩項需求。"]},c=copy[type];
 return {primaryResult:c[0],riskLevel:risk10(Math.round(Math.max(...Object.values(scores)))),confidence:"high",score:Math.round(Math.max(...Object.values(scores))*10)/10,tags:[type,selected],explanation:c[1],insight:`最高訊號為 ${c[0]}，與第二名差距 ${Math.abs(sorted[0][1]-sorted[1][1]).toFixed(1)} 分。`,suggestedAction:c[2],nextStepHint:"支線岔路會結合角色、時間、場景與這次訊號推薦優先路線。",decodedSignalType:type,signalScores:scores,safetyChoice:c[2]};
}

type Previous={1?:any;2?:any;3?:any;5?:any;6?:any};
export function analyzeLevel4BranchTrial(input:any,previous:Previous={},characterResult:any={}):AnalysisResult{
 const result=analyzeBranchRoutes({answers:input.answers||{},selectedBranch:input.selectedBranch},previous,characterResult);
 const primary=branchRoutes[result.recommendedBranch],selected=branchRoutes[result.selectedBranch];
 return {...result,primaryResult:primary.name,riskLevel:"medium",score:result.scores[result.recommendedBranch].total,tags:[result.recommendedBranch,result.secondaryBranch,result.selectedBranch],explanation:result.summary,insight:`${result.combinedPattern}；前三關與角色佔 50%，8 題情境試煉佔 50%。`,suggestedAction:selected.exclusiveAction,nextStepHint:"下一關會依主要攻略路線顯示專屬額外任務。",branchScores:result.scores};
}

export function analyzeLevel5NutritionGap(input:any):AnalysisResult{
 const data={breakfastGap:Number(input.breakfastScore),lunchGap:Number(input.lunchScore),hydrationGap:Number(input.waterScore),proteinGap:Number(input.proteinScore),energyGap:Number(input.afternoonEnergyScore)};if(Object.values(data).some(Number.isNaN))return insufficient({totalNutritionScore:0,nutritionGapTypes:[]});
 const score=Object.values(data).reduce((a,b)=>a+b,0),min=Math.min(...Object.values(data)),gaps=Object.entries(data).filter(([,v])=>v===min&&v<=1).map(([k])=>k),names:any={breakfastGap:"早餐洞",lunchGap:"午餐洞",hydrationGap:"水分洞",proteinGap:"蛋白洞",energyGap:"下午能量洞"};
 const explain:any={breakfastGap:"早餐蛋白質不足會讓上午能量不穩，下午更容易想靠甜飲或零食補電。",lunchGap:"午餐吃太少或太隨便，常讓晚餐前爆餓，提高晚間失控機率。",hydrationGap:"水分不足有時會被誤判成嘴饞，下午疲憊時尤其明顯。",proteinGap:"蛋白質不足容易讓飽足感不穩，晚餐後或睡前更容易想吃。",energyGap:"下午能量不足時，大腦容易想用甜飲、甜食或重口味快速提神。"},task:any={breakfastGap:"明天早餐補一份蛋白質，例如蛋、無糖豆漿或優格。",lunchGap:"明天午餐保留一份蛋白質和主食，不要只吃沙拉。",hydrationGap:"明天下午嘴饞前先喝 300ml 水。",proteinGap:"明天三餐至少先補一餐明確蛋白質。",energyGap:"明天下午準備一個穩定點心，避免直接靠甜飲。"};
 const branch=input.selectedBranch?normalizeBranchKey(input.selectedBranch):null,branchNote=branch&&input.branchAnswer?`${branchRoutes[branch].name}支線補充：${input.branchAnswer}。`:"";
 return {primaryResult:gaps.length?gaps.map(x=>names[x]).join("＋"):"補給相對穩定",riskLevel:score<=3?"high":score<=7?"medium":"low",confidence:"high",score,tags:[...gaps,...(branch?[branch]:[])],explanation:(gaps.length?gaps.map(x=>explain[x]).join(""):"五項補給分數相對穩定，請繼續維持可執行的節奏。")+branchNote,insight:`營養補洞總分 ${score}/10；最低分項目為 ${gaps.map(x=>names[x]).join("、")||"無明顯缺口"}。${branchNote}`,suggestedAction:gaps.length?task[gaps[0]]:"維持目前補給節奏。",nextStepHint:"下一關會確認晚餐是否能接住白天的能量需求。",totalNutritionScore:score,lowestItems:gaps.map(x=>names[x]),nutritionGapTypes:gaps,tomorrowRepairTask:gaps.length?task[gaps[0]]:"維持目前補給節奏",selectedBranch:branch,branchAnswer:String(input.branchAnswer||"")};
}

export function analyzeLevel6DinnerDefense(input:any):AnalysisResult{
 const protein=Boolean(input.selectedProtein),vegetable=Boolean(input.selectedVegetable),carb=Boolean(input.selectedCarb),drink=["水","無糖茶","無糖豆漿","無糖拿鐵"].includes(String(input.selectedDrink)),score=(protein?30:0)+(vegetable?30:0)+(carb?20:0)+(drink?20:0),missing=[!protein&&"protein",!vegetable&&"vegetable",!carb&&"carb",!drink&&"drink"].filter(Boolean) as string[];
 if(!protein&&!vegetable&&!carb&&!input.selectedDrink)return insufficient({dinnerStabilityScore:0,missingElements:missing});
 const upgrades:any={protein:"加茶葉蛋、雞胸、豆腐、魚或肉片，補強晚餐後飽足感。",vegetable:"加沙拉、燙青菜、海帶或菇類，補足體積感。",carb:"若白天吃得少，可保留地瓜、飯半碗或飯糰。",drink:"飲料改成水、無糖茶或無糖豆漿。"};
 return {primaryResult:score<=40?"防線偏弱":score<=70?"基礎防線":"穩定防線",riskLevel:score<=40?"high":score<=70?"medium":"low",confidence:"high",score,tags:[String(input.dinnerScene||"未指定"),...missing],explanation:score<=40?"這餐可能不太能撐住晚上的嘴饞，優先補蛋白質與飲料。":score<=70?"已有基礎防線，但仍可補強缺少的餐盤元素。":"這是一份相對穩定、適合作為下班後使用的晚餐備案。",insight:`蛋白質 ${protein?30:0}/30、蔬菜 ${vegetable?30:0}/30、澱粉 ${carb?20:0}/20、飲料 ${drink?20:0}/20。`,suggestedAction:missing.length?missing.map(x=>upgrades[x]).join(" "):"把這份組合保存成固定晚餐備案。",nextStepHint:"迷霧核心會把晚餐防線與前五關線索一起整合。",dinnerStabilityScore:score,missingElements:missing,strengths:[protein&&"protein",vegetable&&"vegetable",carb&&"carb",drink&&"drink"].filter(Boolean),upgradeSuggestion:missing.map(x=>upgrades[x]),savedDinnerBackups:list(input.savedDinnerBackups)};
}

export function generatePersonalRescueMap(all:Record<number,any>,character:any={},input:any={}):AnalysisResult{
 const l1=all[1]||{},l2=all[2]||{},l3=all[3]||{},l4=all[4]||{},l5=all[5]||{},l6=all[6]||{},scores={fatiguePattern:0,stressPattern:0,habitPattern:0,drinkPattern:0,nutritionPattern:0},type=String(character.primaryType||character.primaryOriginalTypeName||"");
 if(type.includes("fatigue_loss")||type.includes("疲憊"))scores.fatiguePattern+=2;if(["afternoonCrash","dinnerBeforeCrash"].includes(l1.timePatternType))scores.fatiguePattern+=2;if(["fatigueCraving","trueHunger"].includes(l3.decodedSignalType))scores.fatiguePattern+=2;if(Number(l5.totalNutritionScore)<=6)scores.fatiguePattern+=2;
 if(/[壓力委屈]/.test(type)||/[stress_release|compensation]/.test(type))scores.stressPattern+=2;if(Number(l1.sourceScores?.stress)>=7)scores.stressPattern+=2;if(l2.triggerType==="emotionalLoop")scores.stressPattern+=2;if(l3.decodedSignalType==="stressCraving")scores.stressPattern+=2;
 if(type.includes("boredom")||type.includes("無聊"))scores.habitPattern+=2;if(["habitLoop","environmentLoop"].includes(l2.triggerType))scores.habitPattern+=2;if(l3.decodedSignalType==="specificCraving")scores.habitPattern+=2;if(list(l2.highRiskScenes).some(x=>["家裡沙發","追劇時","外送 App","超商"].includes(x)))scores.habitPattern+=2;
 if(type.includes("sugary_drink")||type.includes("含糖飲料"))scores.drinkPattern+=2;if(list(l2.highRiskScenes).some(x=>["手搖飲店","超商"].includes(x)))scores.drinkPattern+=2;if(l1.highRiskTime==="下午 3～5 點")scores.drinkPattern+=2;if(normalizeBranchKey(l4.selectedBranch)==="drink_loop")scores.drinkPattern+=2;
 if(type.includes("nutrition_gap")||type.includes("營養不足"))scores.nutritionPattern+=2;if(Number(l5.totalNutritionScore)<=6)scores.nutritionPattern+=2;if(Number(l6.dinnerStabilityScore)<=70)scores.nutritionPattern+=2;if(Number(l1.sourceScores?.hunger)>=6)scores.nutritionPattern+=2;
 const ranked=Object.entries(scores).sort((a,b)=>b[1]-a[1]),primary=ranked[0][0],secondary=ranked[1][0],copy:any={fatiguePattern:["疲憊與補給不足型","你的嘴饞核心偏向疲憊與補給不足。重點不是更用力忍耐，而是讓白天能量與下班後晚餐更穩。","下週先固定一個下午補給和一個下班後晚餐備案。"],stressPattern:["壓力與情緒釋放型","食物或飲料常在幫你快速降壓，破關重點是建立非食物的安撫流程。","下週壓力大想吃前，先做一次 3 分鐘身心連結或 10 分鐘急救流程。"],habitPattern:["場景與習慣迴路型","固定場景會自動啟動固定行為，因此只靠意志力通常不夠。","下週改變一個高風險場景，例如零食位置、追劇儀式或外送 App 選項。"],drinkPattern:["飲料迴路型","飲料可能同時承擔提神、安慰、配餐與儀式感，不只是熱量問題。","下週把最常喝的飲料改成小杯、微糖、不加料。"],nutritionPattern:["營養缺口型","晚上想吃很多，可能是白天補給不足一路累積的結果。","下週先修補一個白天營養缺口，例如早餐蛋白質、水量或午餐份量。"]},c=copy[primary],complete=[l1,l2,l3,l4,l5,l6].filter(x=>x.confidence&&x.confidence!=="low").length;
 if(complete<4)return insufficient({primaryCravingPattern:primary,secondaryCravingPattern:secondary,patternScores:scores});
 const selectedBranch=normalizeBranchKey(l4.selectedBranch),secondaryBranch=normalizeBranchKey(l4.secondaryBranch),routeEvidence=list(l4.primaryEvidence).slice(0,3);
 return {primaryResult:c[0],riskLevel:ranked[0][1]>=6?"high":"medium",confidence:complete===6?"high":"medium",score:ranked[0][1],tags:[primary,secondary,selectedBranch],explanation:c[1],insight:`整合 ${complete}/6 關有效分析；主要模式 ${ranked[0][1]} 分，次要模式 ${ranked[1][1]} 分。`,suggestedAction:branchRoutes[selectedBranch].exclusiveAction,nextStepHint:c[2],primaryCravingPattern:primary,secondaryCravingPattern:secondary,keyRiskMoment:l1.highRiskTime||"持續觀察",keyRiskScene:list(l2.highRiskScenes)[0]||"持續觀察",mainTriggerMechanism:l3.primaryResult||"持續觀察",biggestNutritionGap:list(l5.lowestItems).join("、")||"無明顯缺口",dinnerDefenseStatus:l6.analysisSummary||l6.primaryResult||"尚未完成",firstRescueAction:String(input.firstRescueAction||branchRoutes[selectedBranch].exclusiveAction),nextWeekMission:String(input.nextWeekAction||branchRoutes[selectedBranch].exclusiveAction),personalRescueMapSummary:c[1],patternScores:scores,selectedBranch,secondaryBranch,routeEvidence,branchExclusiveAction:branchRoutes[selectedBranch].exclusiveAction};
}

export function analyzeBreakthroughLevel(level:number,input:any,previous:Record<number,any>={},character:any={}){if(level===1)return analyzeLevel1TimeFog(input);if(level===2)return analyzeLevel2SceneMaze(input);if(level===3)return analyzeLevel3SignalDecoder(input);if(level===4)return analyzeLevel4BranchTrial(input,previous,character);if(level===5)return analyzeLevel5NutritionGap(input);if(level===6)return analyzeLevel6DinnerDefense(input);return generatePersonalRescueMap(previous,character,input)}
import {branchRoutes,normalizeBranchKey} from "../content/branchRoutes";
import {analyzeBranchRoutes} from "./branch-route-analysis";
