import {branchRoutes,normalizeBranchKey,type BranchKey} from "../content/branchRoutes";
export type JourneyContext={character:{name:string;type:string}|null;timeClue:any;sceneClue:any;signalClue:any;recommendedBranch:BranchKey|null;selectedBranch:BranchKey|null;secondaryBranch:BranchKey|null;routeEvidence:string[];nutritionClue:any;dinnerBackups:any[];currentLevel:number;completedLevels:number[];earnedBadges:string[];latestClues:string[]};
export function buildJourneyContext(state:any):JourneyContext{
 const entries=Array.isArray(state?.entries)?state.entries:[],byLevel=Object.fromEntries(entries.map((x:any)=>[x.levelNumber,x]));const l4=byLevel[4]?.analysisResult||{};
 const selectedRaw=state?.progress?.selectedBranch||byLevel[4]?.selectedBranch||l4.selectedBranch,recommendedRaw=l4.recommendedBranch||state?.profile?.branch;
 const time=byLevel[1]?.analysisResult||{},scene=byLevel[2]?.analysisResult||{},signal=byLevel[3]?.analysisResult||{},nutrition=byLevel[5]?.analysisResult||{},dinnerInputs=byLevel[6]?.userInputs||{};
 const selected=selectedRaw?normalizeBranchKey(selectedRaw):null,recommended=recommendedRaw?normalizeBranchKey(recommendedRaw):null,secondary=l4.secondaryBranch?normalizeBranchKey(l4.secondaryBranch):null;
 const latestClues=[time.highRiskTime&&`高風險時間：${time.highRiskTime}`,scene.sceneTriggerCombination&&`高風險場景：${scene.sceneTriggerCombination}`,signal.primaryResult&&`主要訊號：${signal.primaryResult}`,selected&&`攻略路線：${branchRoutes[selected].name}`,nutrition.primaryResult&&`營養缺口：${nutrition.primaryResult}`].filter(Boolean) as string[];
 return {character:state?.characters?.primary?{name:state.characters.primary.characterName,type:state.characters.primary.originalTypeName}:null,timeClue:time,sceneClue:scene,signalClue:signal,recommendedBranch:recommended,selectedBranch:selected,secondaryBranch:secondary,routeEvidence:Array.isArray(l4.primaryEvidence)?l4.primaryEvidence.map(String):[],nutritionClue:nutrition,dinnerBackups:Array.isArray(dinnerInputs.savedDinnerBackups)?dinnerInputs.savedDinnerBackups:[],currentLevel:Number(state?.progress?.currentLevel||1),completedLevels:Array.isArray(state?.progress?.completedLevels)?state.progress.completedLevels.map(Number):[],earnedBadges:Array.isArray(state?.progress?.earnedBadges)?state.progress.earnedBadges.map(String):[],latestClues};
}
export function previousCluesForLevel(level:number,j:JourneyContext){const items:Array<{label:string;value:string}>=[];if(level>=1&&j.character)items.push({label:"角色",value:`${j.character.name}｜${j.character.type}`});if(level>=2&&j.timeClue.highRiskTime)items.push({label:"高風險時間",value:j.timeClue.highRiskTime},{label:"嘴饞風險",value:`${j.timeClue.timeRiskScore??j.timeClue.score??"—"} / 10`});if(level>=3&&j.sceneClue.sceneTriggerCombination)items.push({label:"場景",value:j.sceneClue.sceneTriggerCombination});if(level>=3&&j.signalClue.primaryResult)items.push({label:"主要訊號",value:j.signalClue.primaryResult});if(level>=4&&j.selectedBranch)items.push({label:"主要攻略路線",value:branchRoutes[j.selectedBranch].name});if(level>=5&&j.nutritionClue.primaryResult)items.push({label:"最大營養缺口",value:j.nutritionClue.primaryResult});if(level>=7&&j.dinnerBackups.length)items.push({label:"晚餐防線",value:`已建立 ${j.dinnerBackups.length} 組`});return items.slice(-6)}
export const clueUsage:Record<number,string[]>={1:["第 2 關的場景分析","第 4 關的支線推薦","第 7 關的止損地圖"],2:["第 3 關的身心解碼","第 4 關的支線推薦","第 6 關的晚餐防線分析"],3:["第 4 關攻略路線","第 5 關的補給重點","第 7 關的主要嘴饞模式"],4:["第 5 關額外任務","第 6 關分析權重","第 7 關主要止損建議"],5:["第 6 關晚餐優先目標","第 7 關營養缺口摘要"],6:["第 7 關的晚餐防線","個人止損地圖"],7:["你的個人止損地圖","下週止損行動"]};
