"use client";
import { useRef, useState } from "react";

export type InteractiveBadgeCardProps={badgeName:string;badgeImageUrl:string;badgeDescription:string;lockedDescription?:string;unlocked:boolean;levelNumber:number;earnedAt?:string|Date|null;actionPoints?:number;celebrate?:boolean};
export default function InteractiveBadgeCard(props:InteractiveBadgeCardProps){
  const ref=useRef<HTMLButtonElement>(null),origin=useRef({x:0,y:0}),[tilt,setTilt]=useState({x:0,y:0}),[active,setActive]=useState(false),[open,setOpen]=useState(false);
  function move(clientX:number,clientY:number){const rect=ref.current?.getBoundingClientRect();if(!rect)return;const dx=(clientX-origin.current.x)/rect.width,dy=(clientY-origin.current.y)/rect.height;setTilt({x:Math.max(-18,Math.min(18,-dy*35)),y:Math.max(-22,Math.min(22,dx*42))})}
  return <article className={`badge-card ${props.unlocked?"unlocked":"locked"} ${props.celebrate?"celebrate":""}`}><button ref={ref} className="badge-tilt" style={{transform:`rotateX(${tilt.x}deg) rotateY(${tilt.y}deg) scale(${active?1.05:1})`}} onPointerDown={e=>{if(!props.unlocked)return;origin.current={x:e.clientX,y:e.clientY};setActive(true);e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>active&&move(e.clientX,e.clientY)} onPointerUp={()=>{setActive(false);setTilt({x:0,y:0});setOpen(true)}} onPointerCancel={()=>{setActive(false);setTilt({x:0,y:0})}} onMouseMove={e=>{if(!active&&props.unlocked){origin.current={x:e.currentTarget.getBoundingClientRect().left+e.currentTarget.offsetWidth/2,y:e.currentTarget.getBoundingClientRect().top+e.currentTarget.offsetHeight/2};move(e.clientX,e.clientY)}}} onMouseLeave={()=>!active&&setTilt({x:0,y:0})} aria-label={`${props.badgeName}，${props.unlocked?"已解鎖":"尚未解鎖"}`}>
    <span className="badge-depth"/><img src={props.badgeImageUrl} alt={props.badgeName} loading="lazy" draggable={false}/><i className="badge-shine"/>{!props.unlocked&&<span className="badge-lock">🔒</span>}
  </button><div className="badge-copy"><small>{props.levelNumber===0?"第 0 天":`第 ${props.levelNumber} 關`}</small><h3>{props.badgeName}</h3><p>{props.unlocked?props.badgeDescription:props.lockedDescription}</p>{props.unlocked&&props.earnedAt&&<time>解鎖於 {new Date(props.earnedAt).toLocaleDateString("zh-TW")}</time>}{props.unlocked&&props.actionPoints!==undefined&&<b>＋{props.actionPoints} 行動點數</b>}</div>{open&&props.unlocked&&<button className="badge-close-detail" onClick={()=>setOpen(false)}>收起徽章資訊</button>}</article>
}
