"use client";
import { useEffect,useState } from "react";
import type { aiEnergyAssessmentContent } from "@/content/aiEnergyAssessment";

type Content=typeof aiEnergyAssessmentContent;
export default function AiAssessmentPageClient({accessToken,attemptedAccessToken,owned,content}:{accessToken:string|null|undefined;attemptedAccessToken:boolean;owned:boolean;content:Content}){
  const [checking,setChecking]=useState(!accessToken&&!attemptedAccessToken),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{if(accessToken){try{localStorage.setItem("emotionalEatingAccessToken",accessToken)}catch{}setChecking(false);return}if(attemptedAccessToken){try{localStorage.removeItem("emotionalEatingAccessToken")}catch{}setChecking(false);return}try{const remembered=localStorage.getItem("emotionalEatingAccessToken");if(remembered){location.replace(`/ai-energy-assessment?accessToken=${encodeURIComponent(remembered)}`);return}}catch{}setChecking(false)},[accessToken,attemptedAccessToken]);
  async function buyWithAccess(){if(!accessToken)return;setBusy(true);setError("");try{const response=await fetch("/api/orders/ai-assessment",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({accessToken})});const data=await response.json();if(!response.ok)throw new Error(data.error||"目前無法建立訂單");location.href=`/payment/redirect/${data.orderNo}`}catch(reason){setError(reason instanceof Error?reason.message:"目前無法建立訂單");setBusy(false)}}
  async function buyStandalone(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);try{const response=await fetch("/api/orders/ai-assessment/standalone",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:form.get("name"),email:form.get("email"),phone:form.get("phone"),lineId:form.get("lineId")})});const data=await response.json();if(!response.ok)throw new Error(data.error||"目前無法建立訂單");location.href=`/payment/redirect/${data.orderNo}`}catch(reason){setError(reason instanceof Error?reason.message:"目前無法建立訂單");setBusy(false)}}
  if(checking)return <main className="ai-page"><div className="ai-checking">正在確認你的購買資格…</div></main>;
  if(owned)return <main className="ai-page"><section className="ai-purchased"><div className="ai-success-mark">✓</div><span className="ai-kicker">{content.purchased.eyebrow}</span><h1>{content.purchased.title}</h1><div className="ai-purchased-copy">{content.purchased.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}</div><aside>{content.purchased.reminder}</aside><a className="btn" href="https://lin.ee/UKTsrwq" target="_blank" rel="noreferrer"><span>{content.purchased.lineCta}</span><span>→</span></a><div className="ai-contact-row"><a href="https://www.instagram.com/meko.hsu" target="_blank" rel="noreferrer">Instagram</a><a href="https://www.facebook.com/couragewellnessinstitute" target="_blank" rel="noreferrer">Facebook 粉絲專頁</a></div><small>{content.brand}</small></section></main>;
  return <main className="ai-page"><header className="ai-offer-hero"><div><span className="ai-kicker">{content.offer.eyebrow}</span><h1>{content.offer.title}</h1><h2>{content.offer.subtitle}</h2><p>{content.offer.description}</p><ul>{content.offer.highlights.map(item=><li key={item}>✓ {item}</li>)}</ul></div><aside><span>{content.offer.priceLabel}</span><strong>NT${content.price}</strong><small>一次付款</small></aside></header><section className="ai-checkout-card"><div><span className="ai-kicker">AI ENERGY ASSESSMENT</span><h2>{content.form.title}</h2><p>{content.offer.note}</p></div>{accessToken?<div className="ai-known-checkout"><button className="btn" type="button" onClick={buyWithAccess} disabled={busy}><span>{busy?"建立訂單中…":content.offer.cta}</span><span>→</span></button></div>:<form onSubmit={buyStandalone}><label>{content.form.name}<input name="name" required pattern="[A-Za-z\u4e00-\u9fff ·]{2,50}" autoComplete="name"/></label><label>{content.form.email}<input name="email" required type="email" autoComplete="email"/></label><label>{content.form.phone}<input name="phone" required inputMode="numeric" autoComplete="tel"/></label><label>{content.form.lineId}<input name="lineId"/></label><button className="btn" type="submit" disabled={busy}><span>{busy?"建立訂單中…":content.form.submit}</span><span>→</span></button></form>}{error&&<p className="ai-error">{error}</p>}<small className="ai-security">🔒 {content.form.security}</small></section></main>;
}
