import { Prisma } from "@prisma/client";
import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/db";
import { authorizeWorkbook } from "@/lib/workbook";
import { rateLimit,requestIp } from "@/lib/rate-limit";
import { buildRescueSummary } from "@/content/cravingRescue";
const score=z.number().int().min(0).max(10),text=z.string().trim().max(1000).optional().nullable();
const optionalChoice=<T extends [string,...string[]]>(values:T)=>z.preprocess(value=>value===""?null:value,z.enum(values).optional().nullable());
const body=z.object({id:z.string().cuid().optional(),complete:z.boolean().optional(),desiredItem:text,initialCraving:score,initialHunger:score,initialStress:score,initialFatigue:score,primaryStates:z.array(z.string().max(30)).min(1).max(10),selectedActions:z.array(z.string().max(50)).max(20).default([]),finalCraving:score.optional().nullable(),consumedResult:optionalChoice(["有","沒有"]),finalChoice:text,helpfulness:optionalChoice(["很有幫助","有一些幫助","普通","幫助不大"]),reminderNote:text});
const select={id:true,desiredItem:true,initialCraving:true,initialHunger:true,initialStress:true,initialFatigue:true,primaryStates:true,selectedActions:true,finalCraving:true,consumedResult:true,finalChoice:true,helpfulness:true,reminderNote:true,startedAt:true,completedAt:true,createdAt:true} as const;
export async function GET(req:Request,{params}:{params:Promise<{accessToken:string}>}){const {accessToken}=await params;if(!await rateLimit(`rescue-read:${requestIp(req)}`,60,60_000))return NextResponse.json({error:"請稍後再試"},{status:429});if(!await authorizeWorkbook(accessToken))return NextResponse.json({error:"無法開啟急救器"},{status:404});const all=await prisma.cravingRescueSession.findMany({where:{accessToken,completedAt:{not:null}},orderBy:{createdAt:"desc"},take:50,select});return NextResponse.json({records:all.slice(0,5),summary:buildRescueSummary(all)});}
export async function POST(req:Request,{params}:{params:Promise<{accessToken:string}>}){const {accessToken}=await params;if(!await rateLimit(`rescue-write:${requestIp(req)}`,60,60_000))return NextResponse.json({error:"操作太頻繁，請稍候"},{status:429});const owner=await authorizeWorkbook(accessToken);if(!owner)return NextResponse.json({error:"無法儲存急救紀錄"},{status:404});const parsed=body.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"請確認必填欄位已完成"},{status:400});const x=parsed.data;if(x.complete&&(!x.selectedActions.length||x.finalCraving===null||x.finalCraving===undefined||!x.consumedResult||!x.helpfulness))return NextResponse.json({error:"請完成急救後回報"},{status:400});const data={desiredItem:x.desiredItem||null,initialCraving:x.initialCraving,initialHunger:x.initialHunger,initialStress:x.initialStress,initialFatigue:x.initialFatigue,primaryStates:x.primaryStates as Prisma.InputJsonValue,selectedActions:x.selectedActions as Prisma.InputJsonValue,finalCraving:x.finalCraving??null,consumedResult:x.consumedResult??null,finalChoice:x.finalChoice||null,helpfulness:x.helpfulness??null,reminderNote:x.reminderNote||null,completedAt:x.complete?new Date():null};if(x.id){const exists=await prisma.cravingRescueSession.findFirst({where:{id:x.id,accessToken},select:{id:true}});if(!exists)return NextResponse.json({error:"找不到這筆急救紀錄"},{status:404});return NextResponse.json({record:await prisma.cravingRescueSession.update({where:{id:x.id},data,select})})}const record=await prisma.cravingRescueSession.create({data:{...data,accessToken,customerId:owner.customerId,orderId:owner.orderId},select});return NextResponse.json({record},{status:201});}
