"use client";
import { useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { answerOptions,calculateQuizResult,emotionalEatingQuestions,emotionalEatingTypes,quizCopy,type EmotionalEatingType,type QuizAnswers } from "@/content/emotionalEatingQuiz";

type SavedResult={answers:QuizAnswers;scores:Record<EmotionalEatingType,number>;primaryType:string;secondaryType:string|null};

function ResultTypeCard({type,role}:{type:EmotionalEatingType;role:string}){const item=emotionalEatingTypes[type];return <article className="quiz-type-card"><span>{role}</span><h2>{item.name}</h2><dl><div><dt>{quizCopy.description}</dt><dd>{item.description}</dd></div><div><dt>{quizCopy.scenario}</dt><dd>{item.scenario}</dd></div><div><dt>{quizCopy.firstStep}</dt><dd>{item.firstStep}</dd></div><div><dt>{quizCopy.task}</dt><dd>{item.task}</dd></div></dl></article>}

function drawWrapped(ctx:CanvasRenderingContext2D,text:string,x:number,y:number,maxWidth:number,lineHeight:number){let line="",currentY=y;for(const char of text){const next=line+char;if(ctx.measureText(next).width>maxWidth&&line){ctx.fillText(line,x,currentY);line=char;currentY+=lineHeight}else line=next}if(line)ctx.fillText(line,x,currentY);return currentY+lineHeight}
async function downloadResultCard(result:SavedResult,primary:EmotionalEatingType[],secondary:EmotionalEatingType[]){
  await document.fonts?.ready;
  const types=[...primary.map(type=>({type,role:quizCopy.primary})),...secondary.map(type=>({type,role:quizCopy.secondary}))],width=1200,height=620+types.length*430;
  const canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;const ctx=canvas.getContext("2d");if(!ctx)return;
  ctx.fillStyle="#fbf5ef";ctx.fillRect(0,0,width,height);ctx.fillStyle="#b85f67";ctx.fillRect(0,0,width,22);
  ctx.fillStyle="#76645d";ctx.font='700 27px "Noto Sans TC", sans-serif';ctx.fillText("可樂吉健康研究所｜崇銘老師",80,95);
  ctx.fillStyle="#4b403c";ctx.font='700 58px "Noto Serif TC", serif';ctx.fillText("我的情緒性進食 6 型測驗結果",80,180);
  ctx.fillStyle="#786a64";ctx.font='400 26px "Noto Sans TC", sans-serif';ctx.fillText("這是一般健康教育與自我觀察結果，不是醫療或心理診斷。",80,235);
  let y=305;for(const {type,role} of types){const item=emotionalEatingTypes[type];ctx.fillStyle="#ffffff";ctx.beginPath();ctx.roundRect(60,y-35,width-120,370,28);ctx.fill();ctx.fillStyle="#b85f67";ctx.font='700 24px "Noto Sans TC", sans-serif';ctx.fillText(`${role} · ${result.scores[type]} 分`,95,y+15);ctx.fillStyle="#4b403c";ctx.font='700 42px "Noto Serif TC", serif';ctx.fillText(item.name,95,y+75);ctx.fillStyle="#5f514c";ctx.font='400 25px "Noto Sans TC", sans-serif';let textY=drawWrapped(ctx,item.description,95,y+125,width-190,39);ctx.fillStyle="#536253";ctx.font='700 23px "Noto Sans TC", sans-serif';ctx.fillText("第一步建議",95,textY+12);ctx.fillStyle="#5f514c";ctx.font='400 25px "Noto Sans TC", sans-serif';drawWrapped(ctx,item.firstStep,95,textY+55,width-190,39);y+=430}
  ctx.fillStyle="#7b6c66";ctx.font='400 23px "Noto Sans TC", sans-serif';ctx.fillText("建議接著開始七日紀錄手冊，看懂自己的日常觸發模式。",80,height-70);
  canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download="情緒性進食6型測驗結果.png";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},"image/png");
}

export default function EmotionalEatingQuizClient({accessToken,ownsAiAssessment}:{accessToken:string;ownsAiAssessment:boolean}){
  const [started,setStarted]=useState(false),[current,setCurrent]=useState(0),[answers,setAnswers]=useState<QuizAnswers>({}),[result,setResult]=useState<SavedResult|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
  useEffect(()=>{fetch(`/api/quiz/emotional-eating/${accessToken}`).then(async response=>{if(!response.ok)throw new Error("無法讀取測驗");return response.json()}).then(data=>{if(data.result){setResult(data.result);setAnswers(data.result.answers)}}).catch(()=>setError("目前無法讀取既有結果，請重新整理後再試。" )).finally(()=>setLoading(false))},[accessToken]);
  const question=emotionalEatingQuestions[current],answered=answers[String(question?.id)]!==undefined;
  const progress=Math.round(((current+1)/emotionalEatingQuestions.length)*100);
  const display=useMemo(()=>result?calculateQuizResult(result.answers):null,[result]);
  async function next(){if(!answered){setError(quizCopy.required);return}setError("");if(current<emotionalEatingQuestions.length-1){setCurrent(value=>value+1);return}setSaving(true);try{const response=await fetch(`/api/quiz/emotional-eating/${accessToken}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({answers})});const data=await response.json();if(!response.ok)throw new Error(data.error||"儲存失敗");setResult(data.result)}catch(reason){setError(reason instanceof Error?reason.message:"儲存失敗")}finally{setSaving(false)}}
  function restart(){setResult(null);setStarted(true);setCurrent(0);setAnswers({});setError("")}
  if(loading)return <main className="quiz-shell"><div className="quiz-loading">正在準備你的測驗…</div></main>;
  if(result&&display){const primary=display.primaryTypes,secondary=display.secondaryTypes;return <main className="quiz-shell"><header className="quiz-top"><Link href={`/access/${accessToken}`}>← 回到工具包</Link><span>可樂吉健康研究所</span></header><div className="quiz-result"><span className="quiz-kicker">YOUR RESULT</span><h1>{quizCopy.resultTitle}</h1>{display.isMixed&&<div className="quiz-mixed">{quizCopy.mixed}</div>}<div className="quiz-result-grid">{primary.map(type=><ResultTypeCard key={type} type={type} role={`${quizCopy.primary} · ${result.scores[type]} 分`}/>)}{secondary.map(type=><ResultTypeCard key={type} type={type} role={`${quizCopy.secondary} · ${result.scores[type]} 分`}/>)}</div><p className="quiz-disclaimer">{quizCopy.disclaimer}</p><button className="quiz-download" type="button" onClick={()=>downloadResultCard(result,primary,secondary)}><span>↓</span>{quizCopy.downloadCta}</button><div className={`quiz-result-actions ${ownsAiAssessment?"has-ai":"single"}`}><Link className="btn" href={`/access/${accessToken}/workbook`}><span>{quizCopy.workbookCta}</span><span>→</span></Link>{ownsAiAssessment&&<section className="quiz-ai-offer"><h2>{quizCopy.aiTitle}</h2><p>{quizCopy.aiDescription}</p><a className="btn quiz-ai-btn" href={`/ai-energy-assessment?accessToken=${encodeURIComponent(accessToken)}`}><span>{quizCopy.aiCta}</span><span>→</span></a></section>}</div>{error&&<p className="quiz-error">{error}</p>}<button className="quiz-restart" type="button" onClick={restart}>重新測驗</button></div></main>}
  if(!started)return <main className="quiz-shell"><header className="quiz-top"><Link href={`/access/${accessToken}`}>← 回到工具包</Link><span>可樂吉健康研究所</span></header><section className="quiz-welcome"><div className="quiz-visual"><span>6</span><small>TYPES</small><i>24 題 · 約 3 分鐘</i></div><span className="quiz-kicker">{quizCopy.eyebrow}</span><h1>{quizCopy.title}</h1><p>{quizCopy.intro}</p>{error&&<p className="quiz-error">{error}</p>}<button className="btn" type="button" onClick={()=>setStarted(true)}><span>{quizCopy.start}</span><span>→</span></button></section></main>;
  return <main className="quiz-shell"><header className="quiz-top"><Link href={`/access/${accessToken}`}>← 暫時離開</Link><span>{current+1} / {emotionalEatingQuestions.length}</span></header><section className="quiz-question"><div className="quiz-progress-copy"><span>測驗進度</span><strong>{current+1} / 24</strong></div><div className="quiz-progress"><i style={{width:`${progress}%`}}/></div><span className="quiz-type-label">{emotionalEatingTypes[question.type].name}</span><h1>{question.text}</h1><div className="quiz-options">{answerOptions.map(option=><button className={answers[String(question.id)]===option.value?"selected":""} type="button" key={option.value} onClick={()=>{setAnswers(value=>({...value,[String(question.id)]:option.value}));setError("")}}><span>{option.value}</span><strong>{option.label}</strong></button>)}</div>{error&&<p className="quiz-error">{error}</p>}<div className="quiz-navigation"><button type="button" disabled={current===0} onClick={()=>setCurrent(value=>value-1)}>← {quizCopy.previous}</button><button className="primary" type="button" disabled={saving} onClick={next}>{saving?"正在儲存…":current===23?quizCopy.finish:`${quizCopy.next} →`}</button></div></section></main>;
}
