import "./globals.css";
import "./enhancements.css";
import "./trigger-analysis.css";
import "./drink-reset.css";
import "./mindful-nutrition.css";
import "./craving-rescue.css";
import "./dinner-formula.css";
import "./safe-swap.css";
import "./pro-tools.css";
import "./breakthrough.css";
import "./access-breakthrough.css";
import "./game-achievements.css";
import "./flow-fixes.css";
import "./sales-game-refresh.css";
import "./fog-kingdom.css";
import "./access-clarity-fixes.css";
import "./access-ai-card.css";
import "./sales-trust.css";
import "./eating-navigation.css";
import "./pro-addon.css";
import "./navigation-feedback.css";
import "./tool-next-step-unification.css";
import "./dinner-defense.css";
import "./journey-connections.css";
import BadgeUnlockHost from "@/components/badges/BadgeUnlockHost";
import CharacterImageLightboxHost from "@/components/access/CharacterImageLightboxHost";
import NavigationFeedback from "@/components/navigation/NavigationFeedback";
export const metadata = { title: "7 天嘴饞破關計畫｜可樂吉健康研究所", description: "每天完成一個小任務，解鎖你的減脂止損地圖" };
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) { return <html lang="zh-Hant"><body>{children}<NavigationFeedback/><BadgeUnlockHost/><CharacterImageLightboxHost/></body></html>; }
