// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/access/[accessToken]" | "/access/[accessToken]/7-day-eating-out-menu" | "/access/[accessToken]/breakthrough-plan" | "/access/[accessToken]/breakthrough-plan/level/[levelNumber]" | "/access/[accessToken]/character-creation" | "/access/[accessToken]/clue-plan" | "/access/[accessToken]/craving-rescue" | "/access/[accessToken]/dinner-formula" | "/access/[accessToken]/drink-reset" | "/access/[accessToken]/drink-swap-pro" | "/access/[accessToken]/mindful-nutrition-tracker" | "/access/[accessToken]/personal-rescue-map" | "/access/[accessToken]/pro/eating-navigation" | "/access/[accessToken]/quiz/emotional-eating" | "/access/[accessToken]/reward" | "/access/[accessToken]/safe-swap-list" | "/access/[accessToken]/three-minute-check" | "/access/[accessToken]/trigger-analysis" | "/access/[accessToken]/workbook" | "/admin/email-test" | "/ai-energy-assessment" | "/checkout" | "/dev/scene-02-characters" | "/payment/redirect/[orderNo]" | "/payment/return" | "/preview/payment-success" | "/preview/workbook" | "/pro-tools/[slug]" | "/sales/emotional-eating" | "/thank-you/[orderNo]"
type AppRouteHandlerRoutes = "/api/admin/email/test" | "/api/admin/orders/[orderNo]/sync" | "/api/breakthrough/[accessToken]" | "/api/breakthrough/[accessToken]/reset" | "/api/character-creation/[accessToken]" | "/api/craving-rescue/[accessToken]" | "/api/dinner-formula/[accessToken]" | "/api/dinner-formula/[accessToken]/[entryId]" | "/api/drink-reset/[accessToken]" | "/api/drink-reset/[accessToken]/day/[dayNumber]" | "/api/drink-reset/[accessToken]/day/[dayNumber]/complete" | "/api/drink-swap-pro/[accessToken]" | "/api/drink-swap-pro/[accessToken]/favorites" | "/api/drink-swap-pro/[accessToken]/favorites/[favoriteId]" | "/api/drink-swap-pro/[accessToken]/profile" | "/api/eating-navigation/[accessToken]" | "/api/eating-navigation/[accessToken]/favorites" | "/api/eating-out-menu/[accessToken]" | "/api/eating-out-menu/[accessToken]/[entryId]" | "/api/eating-out-menu/[accessToken]/favorites" | "/api/gomypay/callback" | "/api/mindful-nutrition/[accessToken]" | "/api/mindful-nutrition/[accessToken]/day/[dayNumber]" | "/api/mindful-nutrition/[accessToken]/day/[dayNumber]/complete" | "/api/mindful-nutrition/[accessToken]/summary" | "/api/orders" | "/api/orders/[orderNo]" | "/api/orders/[orderNo]/reconcile" | "/api/orders/ai-assessment" | "/api/orders/ai-assessment/standalone" | "/api/orders/pro-addon" | "/api/quiz/emotional-eating/[accessToken]" | "/api/safe-swap/[accessToken]" | "/api/safe-swap/[accessToken]/favorites" | "/api/three-minute-check/[accessToken]" | "/api/three-minute-check/[accessToken]/latest" | "/api/trigger-analysis/[accessToken]" | "/api/trigger-analysis/[accessToken]/[entryId]" | "/api/trigger-analysis/[accessToken]/summary" | "/api/workbook/[accessToken]" | "/api/workbook/[accessToken]/day/[dayNumber]" | "/api/workbook/[accessToken]/day/[dayNumber]/complete"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = "/game-assets/badges/[[...file]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/access/[accessToken]": { "accessToken": string; }
  "/access/[accessToken]/7-day-eating-out-menu": { "accessToken": string; }
  "/access/[accessToken]/breakthrough-plan": { "accessToken": string; }
  "/access/[accessToken]/breakthrough-plan/level/[levelNumber]": { "accessToken": string; "levelNumber": string; }
  "/access/[accessToken]/character-creation": { "accessToken": string; }
  "/access/[accessToken]/clue-plan": { "accessToken": string; }
  "/access/[accessToken]/craving-rescue": { "accessToken": string; }
  "/access/[accessToken]/dinner-formula": { "accessToken": string; }
  "/access/[accessToken]/drink-reset": { "accessToken": string; }
  "/access/[accessToken]/drink-swap-pro": { "accessToken": string; }
  "/access/[accessToken]/mindful-nutrition-tracker": { "accessToken": string; }
  "/access/[accessToken]/personal-rescue-map": { "accessToken": string; }
  "/access/[accessToken]/pro/eating-navigation": { "accessToken": string; }
  "/access/[accessToken]/quiz/emotional-eating": { "accessToken": string; }
  "/access/[accessToken]/reward": { "accessToken": string; }
  "/access/[accessToken]/safe-swap-list": { "accessToken": string; }
  "/access/[accessToken]/three-minute-check": { "accessToken": string; }
  "/access/[accessToken]/trigger-analysis": { "accessToken": string; }
  "/access/[accessToken]/workbook": { "accessToken": string; }
  "/admin/email-test": {}
  "/ai-energy-assessment": {}
  "/api/admin/email/test": {}
  "/api/admin/orders/[orderNo]/sync": { "orderNo": string; }
  "/api/breakthrough/[accessToken]": { "accessToken": string; }
  "/api/breakthrough/[accessToken]/reset": { "accessToken": string; }
  "/api/character-creation/[accessToken]": { "accessToken": string; }
  "/api/craving-rescue/[accessToken]": { "accessToken": string; }
  "/api/dinner-formula/[accessToken]": { "accessToken": string; }
  "/api/dinner-formula/[accessToken]/[entryId]": { "accessToken": string; "entryId": string; }
  "/api/drink-reset/[accessToken]": { "accessToken": string; }
  "/api/drink-reset/[accessToken]/day/[dayNumber]": { "accessToken": string; "dayNumber": string; }
  "/api/drink-reset/[accessToken]/day/[dayNumber]/complete": { "accessToken": string; "dayNumber": string; }
  "/api/drink-swap-pro/[accessToken]": { "accessToken": string; }
  "/api/drink-swap-pro/[accessToken]/favorites": { "accessToken": string; }
  "/api/drink-swap-pro/[accessToken]/favorites/[favoriteId]": { "accessToken": string; "favoriteId": string; }
  "/api/drink-swap-pro/[accessToken]/profile": { "accessToken": string; }
  "/api/eating-navigation/[accessToken]": { "accessToken": string; }
  "/api/eating-navigation/[accessToken]/favorites": { "accessToken": string; }
  "/api/eating-out-menu/[accessToken]": { "accessToken": string; }
  "/api/eating-out-menu/[accessToken]/[entryId]": { "accessToken": string; "entryId": string; }
  "/api/eating-out-menu/[accessToken]/favorites": { "accessToken": string; }
  "/api/gomypay/callback": {}
  "/api/mindful-nutrition/[accessToken]": { "accessToken": string; }
  "/api/mindful-nutrition/[accessToken]/day/[dayNumber]": { "accessToken": string; "dayNumber": string; }
  "/api/mindful-nutrition/[accessToken]/day/[dayNumber]/complete": { "accessToken": string; "dayNumber": string; }
  "/api/mindful-nutrition/[accessToken]/summary": { "accessToken": string; }
  "/api/orders": {}
  "/api/orders/[orderNo]": { "orderNo": string; }
  "/api/orders/[orderNo]/reconcile": { "orderNo": string; }
  "/api/orders/ai-assessment": {}
  "/api/orders/ai-assessment/standalone": {}
  "/api/orders/pro-addon": {}
  "/api/quiz/emotional-eating/[accessToken]": { "accessToken": string; }
  "/api/safe-swap/[accessToken]": { "accessToken": string; }
  "/api/safe-swap/[accessToken]/favorites": { "accessToken": string; }
  "/api/three-minute-check/[accessToken]": { "accessToken": string; }
  "/api/three-minute-check/[accessToken]/latest": { "accessToken": string; }
  "/api/trigger-analysis/[accessToken]": { "accessToken": string; }
  "/api/trigger-analysis/[accessToken]/[entryId]": { "accessToken": string; "entryId": string; }
  "/api/trigger-analysis/[accessToken]/summary": { "accessToken": string; }
  "/api/workbook/[accessToken]": { "accessToken": string; }
  "/api/workbook/[accessToken]/day/[dayNumber]": { "accessToken": string; "dayNumber": string; }
  "/api/workbook/[accessToken]/day/[dayNumber]/complete": { "accessToken": string; "dayNumber": string; }
  "/checkout": {}
  "/dev/scene-02-characters": {}
  "/game-assets/badges/[[...file]]": { "file"?: string[]; }
  "/payment/redirect/[orderNo]": { "orderNo": string; }
  "/payment/return": {}
  "/preview/payment-success": {}
  "/preview/workbook": {}
  "/pro-tools/[slug]": { "slug": string; }
  "/sales/emotional-eating": {}
  "/thank-you/[orderNo]": { "orderNo": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
