// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/access/[accessToken]/7-day-eating-out-menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access/[accessToken]/7-day-eating-out-menu">> = Specific
  const handler = {} as typeof import("../../src/app/access/[accessToken]/7-day-eating-out-menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/access/[accessToken]/breakthrough-plan/level/[levelNumber]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access/[accessToken]/breakthrough-plan/level/[levelNumber]">> = Specific
  const handler = {} as typeof import("../../src/app/access/[accessToken]/breakthrough-plan/level/[levelNumber]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/access/[accessToken]/breakthrough-plan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access/[accessToken]/breakthrough-plan">> = Specific
  const handler = {} as typeof import("../../src/app/access/[accessToken]/breakthrough-plan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/access/[accessToken]/character-creation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access/[accessToken]/character-creation">> = Specific
  const handler = {} as typeof import("../../src/app/access/[accessToken]/character-creation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/access/[accessToken]/clue-plan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access/[accessToken]/clue-plan">> = Specific
  const handler = {} as typeof import("../../src/app/access/[accessToken]/clue-plan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/access/[accessToken]/craving-rescue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access/[accessToken]/craving-rescue">> = Specific
  const handler = {} as typeof import("../../src/app/access/[accessToken]/craving-rescue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/access/[accessToken]/dinner-formula/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access/[accessToken]/dinner-formula">> = Specific
  const handler = {} as typeof import("../../src/app/access/[accessToken]/dinner-formula/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/access/[accessToken]/drink-reset/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access/[accessToken]/drink-reset">> = Specific
  const handler = {} as typeof import("../../src/app/access/[accessToken]/drink-reset/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/access/[accessToken]/drink-swap-pro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access/[accessToken]/drink-swap-pro">> = Specific
  const handler = {} as typeof import("../../src/app/access/[accessToken]/drink-swap-pro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/access/[accessToken]/mindful-nutrition-tracker/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access/[accessToken]/mindful-nutrition-tracker">> = Specific
  const handler = {} as typeof import("../../src/app/access/[accessToken]/mindful-nutrition-tracker/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/access/[accessToken]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access/[accessToken]">> = Specific
  const handler = {} as typeof import("../../src/app/access/[accessToken]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/access/[accessToken]/personal-rescue-map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access/[accessToken]/personal-rescue-map">> = Specific
  const handler = {} as typeof import("../../src/app/access/[accessToken]/personal-rescue-map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/access/[accessToken]/pro/eating-navigation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access/[accessToken]/pro/eating-navigation">> = Specific
  const handler = {} as typeof import("../../src/app/access/[accessToken]/pro/eating-navigation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/access/[accessToken]/quiz/emotional-eating/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access/[accessToken]/quiz/emotional-eating">> = Specific
  const handler = {} as typeof import("../../src/app/access/[accessToken]/quiz/emotional-eating/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/access/[accessToken]/reward/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access/[accessToken]/reward">> = Specific
  const handler = {} as typeof import("../../src/app/access/[accessToken]/reward/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/access/[accessToken]/safe-swap-list/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access/[accessToken]/safe-swap-list">> = Specific
  const handler = {} as typeof import("../../src/app/access/[accessToken]/safe-swap-list/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/access/[accessToken]/three-minute-check/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access/[accessToken]/three-minute-check">> = Specific
  const handler = {} as typeof import("../../src/app/access/[accessToken]/three-minute-check/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/access/[accessToken]/trigger-analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access/[accessToken]/trigger-analysis">> = Specific
  const handler = {} as typeof import("../../src/app/access/[accessToken]/trigger-analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/access/[accessToken]/workbook/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access/[accessToken]/workbook">> = Specific
  const handler = {} as typeof import("../../src/app/access/[accessToken]/workbook/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/email-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/email-test">> = Specific
  const handler = {} as typeof import("../../src/app/admin/email-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ai-energy-assessment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-energy-assessment">> = Specific
  const handler = {} as typeof import("../../src/app/ai-energy-assessment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dev/scene-02-characters/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/scene-02-characters">> = Specific
  const handler = {} as typeof import("../../src/app/dev/scene-02-characters/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/payment/redirect/[orderNo]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment/redirect/[orderNo]">> = Specific
  const handler = {} as typeof import("../../src/app/payment/redirect/[orderNo]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/payment/return/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment/return">> = Specific
  const handler = {} as typeof import("../../src/app/payment/return/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/preview/payment-success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preview/payment-success">> = Specific
  const handler = {} as typeof import("../../src/app/preview/payment-success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/preview/workbook/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preview/workbook">> = Specific
  const handler = {} as typeof import("../../src/app/preview/workbook/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pro-tools/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pro-tools/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/pro-tools/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sales/emotional-eating/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/emotional-eating">> = Specific
  const handler = {} as typeof import("../../src/app/sales/emotional-eating/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/thank-you/[orderNo]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/thank-you/[orderNo]">> = Specific
  const handler = {} as typeof import("../../src/app/thank-you/[orderNo]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/email/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/email/test">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/email/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/orders/[orderNo]/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/orders/[orderNo]/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/orders/[orderNo]/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/breakthrough/[accessToken]/reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/breakthrough/[accessToken]/reset">> = Specific
  const handler = {} as typeof import("../../src/app/api/breakthrough/[accessToken]/reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/breakthrough/[accessToken]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/breakthrough/[accessToken]">> = Specific
  const handler = {} as typeof import("../../src/app/api/breakthrough/[accessToken]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/character-creation/[accessToken]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/character-creation/[accessToken]">> = Specific
  const handler = {} as typeof import("../../src/app/api/character-creation/[accessToken]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/craving-rescue/[accessToken]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/craving-rescue/[accessToken]">> = Specific
  const handler = {} as typeof import("../../src/app/api/craving-rescue/[accessToken]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dinner-formula/[accessToken]/[entryId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dinner-formula/[accessToken]/[entryId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/dinner-formula/[accessToken]/[entryId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dinner-formula/[accessToken]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dinner-formula/[accessToken]">> = Specific
  const handler = {} as typeof import("../../src/app/api/dinner-formula/[accessToken]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/drink-reset/[accessToken]/day/[dayNumber]/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drink-reset/[accessToken]/day/[dayNumber]/complete">> = Specific
  const handler = {} as typeof import("../../src/app/api/drink-reset/[accessToken]/day/[dayNumber]/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/drink-reset/[accessToken]/day/[dayNumber]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drink-reset/[accessToken]/day/[dayNumber]">> = Specific
  const handler = {} as typeof import("../../src/app/api/drink-reset/[accessToken]/day/[dayNumber]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/drink-reset/[accessToken]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drink-reset/[accessToken]">> = Specific
  const handler = {} as typeof import("../../src/app/api/drink-reset/[accessToken]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/drink-swap-pro/[accessToken]/favorites/[favoriteId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drink-swap-pro/[accessToken]/favorites/[favoriteId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/drink-swap-pro/[accessToken]/favorites/[favoriteId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/drink-swap-pro/[accessToken]/favorites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drink-swap-pro/[accessToken]/favorites">> = Specific
  const handler = {} as typeof import("../../src/app/api/drink-swap-pro/[accessToken]/favorites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/drink-swap-pro/[accessToken]/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drink-swap-pro/[accessToken]/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/drink-swap-pro/[accessToken]/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/drink-swap-pro/[accessToken]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drink-swap-pro/[accessToken]">> = Specific
  const handler = {} as typeof import("../../src/app/api/drink-swap-pro/[accessToken]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/eating-navigation/[accessToken]/favorites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/eating-navigation/[accessToken]/favorites">> = Specific
  const handler = {} as typeof import("../../src/app/api/eating-navigation/[accessToken]/favorites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/eating-navigation/[accessToken]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/eating-navigation/[accessToken]">> = Specific
  const handler = {} as typeof import("../../src/app/api/eating-navigation/[accessToken]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/eating-out-menu/[accessToken]/[entryId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/eating-out-menu/[accessToken]/[entryId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/eating-out-menu/[accessToken]/[entryId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/eating-out-menu/[accessToken]/favorites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/eating-out-menu/[accessToken]/favorites">> = Specific
  const handler = {} as typeof import("../../src/app/api/eating-out-menu/[accessToken]/favorites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/eating-out-menu/[accessToken]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/eating-out-menu/[accessToken]">> = Specific
  const handler = {} as typeof import("../../src/app/api/eating-out-menu/[accessToken]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gomypay/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gomypay/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/gomypay/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mindful-nutrition/[accessToken]/day/[dayNumber]/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mindful-nutrition/[accessToken]/day/[dayNumber]/complete">> = Specific
  const handler = {} as typeof import("../../src/app/api/mindful-nutrition/[accessToken]/day/[dayNumber]/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mindful-nutrition/[accessToken]/day/[dayNumber]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mindful-nutrition/[accessToken]/day/[dayNumber]">> = Specific
  const handler = {} as typeof import("../../src/app/api/mindful-nutrition/[accessToken]/day/[dayNumber]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mindful-nutrition/[accessToken]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mindful-nutrition/[accessToken]">> = Specific
  const handler = {} as typeof import("../../src/app/api/mindful-nutrition/[accessToken]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mindful-nutrition/[accessToken]/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mindful-nutrition/[accessToken]/summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/mindful-nutrition/[accessToken]/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[orderNo]/reconcile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[orderNo]/reconcile">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[orderNo]/reconcile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[orderNo]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[orderNo]">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[orderNo]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/ai-assessment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/ai-assessment">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/ai-assessment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/ai-assessment/standalone/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/ai-assessment/standalone">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/ai-assessment/standalone/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/pro-addon/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/pro-addon">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/pro-addon/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quiz/emotional-eating/[accessToken]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quiz/emotional-eating/[accessToken]">> = Specific
  const handler = {} as typeof import("../../src/app/api/quiz/emotional-eating/[accessToken]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/safe-swap/[accessToken]/favorites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/safe-swap/[accessToken]/favorites">> = Specific
  const handler = {} as typeof import("../../src/app/api/safe-swap/[accessToken]/favorites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/safe-swap/[accessToken]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/safe-swap/[accessToken]">> = Specific
  const handler = {} as typeof import("../../src/app/api/safe-swap/[accessToken]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/three-minute-check/[accessToken]/latest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/three-minute-check/[accessToken]/latest">> = Specific
  const handler = {} as typeof import("../../src/app/api/three-minute-check/[accessToken]/latest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/three-minute-check/[accessToken]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/three-minute-check/[accessToken]">> = Specific
  const handler = {} as typeof import("../../src/app/api/three-minute-check/[accessToken]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/trigger-analysis/[accessToken]/[entryId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trigger-analysis/[accessToken]/[entryId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/trigger-analysis/[accessToken]/[entryId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/trigger-analysis/[accessToken]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trigger-analysis/[accessToken]">> = Specific
  const handler = {} as typeof import("../../src/app/api/trigger-analysis/[accessToken]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/trigger-analysis/[accessToken]/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trigger-analysis/[accessToken]/summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/trigger-analysis/[accessToken]/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workbook/[accessToken]/day/[dayNumber]/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workbook/[accessToken]/day/[dayNumber]/complete">> = Specific
  const handler = {} as typeof import("../../src/app/api/workbook/[accessToken]/day/[dayNumber]/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workbook/[accessToken]/day/[dayNumber]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workbook/[accessToken]/day/[dayNumber]">> = Specific
  const handler = {} as typeof import("../../src/app/api/workbook/[accessToken]/day/[dayNumber]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workbook/[accessToken]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workbook/[accessToken]">> = Specific
  const handler = {} as typeof import("../../src/app/api/workbook/[accessToken]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
