export const triggerAnalysisContent={
  title:"下班後嘴饞觸發點分析器",intro:"你的嘴饞不是突然發生的。請回推嘴饞前 30 分鐘，找出時間、場景、情緒、身體與營養線索。",positioning:"事後回推每次破功前的時間、情緒、場景、身體與營養線索。累積 3–7 次紀錄後，更容易看見重複出現的破功開關。",newEntry:"新增一次嘴饞紀錄",saved:"已儲存，這是一個很重要的線索。",edit:"查看／編輯",delete:"刪除",deleteConfirm:"確定要刪除這筆嘴饞紀錄嗎？刪除後無法復原。",empty:"還沒有紀錄。下一次嘴饞發生後，花幾分鐘回推剛才的情境，就是很有價值的開始。",
  steps:["記錄這次嘴饞事件","回推嘴饞前 30 分鐘","分類觸發點","下次止損策略"],
  event:{title:"Step 1：記錄這次嘴饞事件",occurredAt:"發生時間",location:"當時在哪裡？",cravingItem:"想吃或想喝什麼？",cravingScore:"嘴饞強度",hungerScore:"身體飢餓程度",stressScore:"壓力程度",fatigueScore:"疲憊程度",didEat:"最後有吃或喝嗎？",consumedItem:"如果有，實際吃或喝了什麼？",afterFeeling:"吃喝之後的感覺",afterOptions:["滿足","放鬆","內疚","更想吃","沒感覺"]},
  rewind:{title:"Step 2：回推嘴饞前 30 分鐘",beforeActivity:"嘴饞前 30 分鐘，我正在做什麼？",beforeEvent:"嘴饞前 30 分鐘，我剛發生什麼事？",beforeEmotion:"我那時候的情緒是什麼？",bodyState:"我那時候身體狀態如何？",lastMealTime:"我上一餐是什麼時候吃的？",lastMealEnough:"上一餐吃得夠嗎？",waterEnough:"今天水分足夠嗎？",sleepPoor:"昨晚有睡不好嗎？"},
  classify:{title:"Step 3：分類觸發點",groups:[{title:"時間與場景",options:["固定時間到了","經過特定店家","打開外送 App","便利商店","沙發追劇","冰箱或零食櫃","回家路上"]},{title:"情緒與身體",options:["壓力太大","很疲憊","心情委屈","無聊","焦慮","想獎勵自己","睡眠不足","生理期前","真的餓"]},{title:"營養與習慣",options:["白天吃太少","蛋白質不足","水喝太少","午餐太隨便","下午靠飲料撐精神","飯後習慣想吃","追劇或滑手機想配東西","下班後一定要喝飲料"]}],mainTrigger:"這次最主要的觸發點是什麼？",notes:"我想先處理的原因是什麼？"},
  strategy:{title:"Step 4：下次止損策略",label:"如果我下次又遇到 ______，那我就先 ______。",examples:["如果我下班後想買手搖飲，那我就先喝 300ml 水，10 分鐘後再決定。","如果我晚餐後想吃甜食，那我就先刷牙或泡熱茶。","如果我壓力大想叫外送，那我就先做 3 分鐘身心連結工作本。","如果我很累不想選餐，那我就使用固定晚餐備案。","如果我追劇想配零食，那我就換成無糖飲或安全點心。","如果我白天吃太少晚上想吃，那我就明天早餐或午餐補蛋白質。"],apply:"套用這個策略"},
  nav:{back:"上一步",next:"下一步",save:"儲存這筆紀錄",saving:"儲存中…",saved:"✓ 已儲存"},
  list:{title:"我的紀錄列表",date:"日期",item:"想吃／喝",trigger:"主要觸發點",score:"嘴饞強度",stopped:"是否止損",yes:"未吃喝",no:"有吃喝"},
  summary:{title:"我的觸發點摘要",needMore:"目前先顯示基本摘要。累積至少 3 筆後，會提供更完整的高風險模式分析。",count:"紀錄總數",avgCraving:"平均嘴饞",avgHunger:"平均飢餓",avgStress:"平均壓力",avgFatigue:"平均疲憊",topTriggers:"常見觸發點",topLocations:"高風險場景",topTimes:"高風險時間",topItems:"常想吃喝",eatRatio:"實際吃喝比例",mainTrigger:"最常見主因",riskTitle:"我的高風險模式"},
  patterns:{stress:"壓力觸發傾向",fatigue:"疲憊觸發傾向",nutrition:"營養缺口傾向",habit:"習慣觸發傾向",drink:"含糖飲料觸發傾向",unclear:"目前模式尚不明顯"},
  next:{title:"下一步建議",emotion:"情緒觸發明顯：建議回去看情緒性進食 6 型測驗結果。",pause:"當下很難停下來：建議使用嘴饞前 3 分鐘身心連結工作本。",rescue:"已經快要失控：建議使用 10 分鐘嘴饞急救流程卡。",day5:"白天吃太少：建議完成 7 天嘴饞止損行動手冊 Day 5。",day6:"晚餐後失控：建議完成 7 天嘴饞止損行動手冊 Day 6。",aiTitle:"想知道更深層的減脂卡關原因？",aiText:"如果你已經加購 1 元 AI 減脂測驗，點擊後可直接進入測驗領取與聯繫頁面。若尚未加購，系統會引導你進入加購頁。",aiButton:"前往 AI 能量減脂初評"},
  errors:{invalid:"這個工具包連結無效、尚未付款，或未包含主商品。請從購買信件中的專屬連結重新進入。",load:"目前無法讀取紀錄，請稍後再試。",save:"目前無法儲存，請確認網路後再試。",remove:"目前無法刪除，請稍後再試。"}
} as const;

export type TriggerEntry={id?:string;occurredAt?:string|null;location?:string|null;cravingItem?:string|null;cravingScore?:number|null;hungerScore?:number|null;stressScore?:number|null;fatigueScore?:number|null;didEatOrDrink?:boolean|null;consumedItem?:string|null;afterFeeling:string[];beforeActivity?:string|null;beforeEvent?:string|null;beforeEmotion?:string|null;bodyState?:string|null;lastMealTime?:string|null;lastMealEnough?:string|null;waterEnough?:string|null;sleepPoor?:boolean|null;triggerTypes:string[];mainTrigger?:string|null;notes?:string|null;nextStrategy?:string|null;createdAt?:string;updatedAt?:string};
export const emptyTriggerEntry:TriggerEntry={occurredAt:new Date().toISOString().slice(0,16),afterFeeling:[],triggerTypes:[]};
export type TriggerSummary={count:number;averages:{craving:number|null;hunger:number|null;stress:number|null;fatigue:number|null};topTriggers:{label:string;count:number}[];topLocations:{label:string;count:number}[];topTimes:{label:string;count:number}[];topItems:{label:string;count:number}[];eatRatio:number|null;mainTrigger:string|null;patterns:string[];narrative:string;suggestions:string[]};

const average=(values:(number|null|undefined)[])=>{const valid=values.filter((value):value is number=>typeof value==="number");return valid.length?Number((valid.reduce((a,b)=>a+b,0)/valid.length).toFixed(1)):null};
const top=(values:(string|null|undefined)[],limit=3)=>Object.entries(values.filter((value):value is string=>Boolean(value?.trim())).reduce<Record<string,number>>((map,value)=>(map[value]=(map[value]??0)+1,map),{})).sort((a,b)=>b[1]-a[1]).slice(0,limit).map(([label,count])=>({label,count}));
export function buildTriggerSummary(entries:TriggerEntry[]):TriggerSummary{
  const averages={craving:average(entries.map(x=>x.cravingScore)),hunger:average(entries.map(x=>x.hungerScore)),stress:average(entries.map(x=>x.stressScore)),fatigue:average(entries.map(x=>x.fatigueScore))};
  const timeLabels=entries.map(entry=>{if(!entry.occurredAt)return null;const hour=new Date(entry.occurredAt).getHours();return hour<6?"凌晨 00–05 時":hour<12?"早上 06–11 時":hour<18?"下午 12–17 時":"晚上 18–23 時"});
  const triggers=entries.flatMap(x=>x.triggerTypes??[]),topTriggers=top(triggers),topLocations=top(entries.map(x=>x.location)),topTimes=top(timeLabels),topItems=top(entries.map(x=>x.cravingItem)),mainTrigger=top(entries.map(x=>x.mainTrigger),1)[0]?.label??null;
  const patterns:string[]=[];if((averages.stress??0)>=7&&triggers.includes("壓力太大"))patterns.push("stress");if((averages.fatigue??0)>=7)patterns.push("fatigue");if((averages.hunger??0)>=7||triggers.some(x=>["白天吃太少","蛋白質不足"].includes(x)))patterns.push("nutrition");if(triggers.some(x=>["飯後習慣想吃","追劇或滑手機想配東西"].includes(x)))patterns.push("habit");if(triggers.some(x=>["下班後一定要喝飲料","下午靠飲料撐精神"].includes(x)))patterns.push("drink");
  const eaten=entries.filter(x=>x.didEatOrDrink===true).length,answered=entries.filter(x=>typeof x.didEatOrDrink==="boolean").length,eatRatio=answered?Math.round(eaten/answered*100):null;
  const names=patterns.length?patterns.map(key=>triggerAnalysisContent.patterns[key as keyof typeof triggerAnalysisContent.patterns]):[triggerAnalysisContent.patterns.unclear];
  const narrative=entries.length<3?triggerAnalysisContent.summary.needMore:`你目前較明顯的模式是「${names.slice(0,2).join("」與「")}」。${topTriggers[0]?`最常出現的觸發線索是「${topTriggers[0].label}」。`:""}建議先從最常重複的情境，安排一個容易做到的止損動作。`;
  const suggestions=[patterns.some(x=>["stress","fatigue"].includes(x))&&triggerAnalysisContent.next.emotion,triggerAnalysisContent.next.pause,(averages.craving??0)>=8&&triggerAnalysisContent.next.rescue,patterns.includes("nutrition")&&triggerAnalysisContent.next.day5,(topTriggers.some(x=>x.label.includes("飯後"))||topLocations.some(x=>x.label.includes("家")))&&triggerAnalysisContent.next.day6].filter(Boolean) as string[];
  return {count:entries.length,averages,topTriggers,topLocations,topTimes,topItems,eatRatio,mainTrigger,patterns,narrative,suggestions:[...new Set(suggestions)]};
}
