export type DinnerScene={protein:string[];vegetable:string[];carb:string[];drink:string[];note?:string};
export const dinnerFormulaContent={title:"下班後防暴食晚餐公式",subtitle:"外食族也能用的 3-1-1 穩定晚餐選擇法",intro:"不需要研究營養，也不用自己煮。用 1–2 分鐘替今晚選一份比較穩定、比較不容易晚餐後繼續嘴饞的外食晚餐。",formula:["3 拳蔬菜","1 掌蛋白質","1 拳澱粉","1 杯水或無糖飲"],states:["很餓","很累","很煩","很想喝飲料","很想吃炸物","很想叫外送","只是懶得想"],scenes:{
"便當店":{protein:["雞腿","雞胸","魚","瘦肉","滷排骨","豆腐"],vegetable:["多夾兩格青菜","飯少一點多菜"],carb:["半碗飯","一碗飯","不吃主食"],drink:["水","無糖茶"]},
"超商":{protein:["茶葉蛋","雞胸","無糖豆漿","豆腐","鮪魚","毛豆"],vegetable:["沙拉","毛豆","菇類","燙青菜"],carb:["地瓜","飯糰","玉米","吐司","不吃主食"],drink:["水","無糖茶","無糖豆漿"]},
"麵店":{protein:["滷蛋","豆干","燙肉片","雞肉","魚丸貢丸適量"],vegetable:["燙青菜","海帶","豆芽"],carb:["湯麵","乾麵減醬","米粉","不吃主食"],drink:["水","無糖茶"]},
"早餐店當晚餐":{protein:["雞蛋","鮪魚","里肌","無糖豆漿"],vegetable:["生菜","蔬菜蛋餅"],carb:["吐司","蛋餅","饅頭","不吃主食"],drink:["無糖豆漿","無糖茶"],note:"避免奶茶 + 鐵板麵 + 薯餅三連擊。"},
"速食店":{protein:["雞肉","牛肉","魚排，先保留主餐蛋白質"],vegetable:["若有沙拉可加","若沒有就先穩住飲料與薯條"],carb:["漢堡麵包","薯條減量","不吃主食"],drink:["無糖茶","水","黑咖啡"],note:"主餐保留，飲料換無糖，薯條減量或不加點，不加甜點。"},
"滷味":{protein:["豆干","雞肉","蛋","豆腐"],vegetable:["青菜","菇類","海帶"],carb:["冬粉","王子麵少量","玉米","不吃主食"],drink:["水","無糖茶"]},
"自助餐":{protein:["雞","魚","肉","豆腐","蛋"],vegetable:["先夾菜，再夾肉，最後決定飯量"],carb:["半碗飯","一碗飯","不吃主食"],drink:["水","無糖茶"]},
"外送":{protein:["有雞、魚、肉、蛋或豆腐的主餐"],vegetable:["優先選有蔬菜的餐點"],carb:["保留一份主食，不加點炸物","不吃主食"],drink:["水","無糖茶"],note:"先選主餐，不加點含糖飲料、甜點與炸物加購。優先選有蛋白質與蔬菜的餐點。"},
"其他":{protein:["選一份看得見的蛋白質"],vegetable:["加一份蔬菜或高纖食物"],carb:["選一拳左右的主食","不吃主食"],drink:["水","無糖飲"]}
} as Record<string,DinnerScene>,closingActions:["刷牙","泡熱茶","散步 5 分鐘","把零食移開","收拾餐桌後離開用餐區"],reminder:"晚餐不需要完美，只要比『太餓後隨便吃』多一點穩定。",invalid:"這個專屬連結無效、訂單尚未付款，或未包含《下班後嘴饞止損包》。請從購買完成信中的工具包連結重新進入。",cta:{title:"前往 AI 能量減脂初評",text:"如果你發現自己最大問題不是不知道怎麼吃，而是下班後太累、沒時間準備、外食選擇很不穩，那你需要的可能不是更複雜的菜單，而是一套更簡單、固定、可以每天執行的營養安排。",note:"如果你已經加購 1 元 AI 能量減脂初評，點擊下方按鈕後，系統會直接帶你進入領取與聯繫頁面。若你尚未加購，則會先進入加購頁。",button:"立即前往測驗入口"},disclaimer:"這是一般健康教育與自我觀察工具，不是醫療診斷，也不保證減重效果。"} as const;
export type DinnerEntry={id:string;hungerScore:number;fatigueScore:number;stressScore:number;currentStates:unknown;mealScene:string;proteinChoice:string;vegetableChoice:string;carbChoice:string;drinkChoice:string;closingAction:string;generatedSuggestion:string;daytimeIntakeStatus?:string|null;dinnerTimeBand?:string|null;tonightConcerns?:unknown|null;contextData?:unknown|null;dinnerFormulaResult?:any|null;fullnessAfterDinner:number|null;cravingAfterDinner:string|null;hadSweetDrink:boolean|null;didClosingAction:string|null;reflection:string|null;createdAt:string|Date;updatedAt:string|Date};
const common=(values:string[])=>Object.entries(values.reduce<Record<string,number>>((m,x)=>(m[x]=(m[x]??0)+1,m),{})).sort((a,b)=>b[1]-a[1])[0]?.[0]??"資料不足";
export function generateDinnerSuggestion(x:{proteinChoice:string;vegetableChoice:string;carbChoice:string;drinkChoice:string;closingAction:string}){return `今晚你可以選：${x.proteinChoice} + ${x.vegetableChoice} + ${x.carbChoice}，飲料選${x.drinkChoice}。晚餐後先${x.closingAction}，避免直接進入零食模式。`}
export function buildDinnerSummary(entries:DinnerEntry[]){const commonScene=common(entries.map(x=>x.mealScene)),missing={蛋白質:entries.filter(x=>!x.proteinChoice).length,蔬菜:entries.filter(x=>!x.vegetableChoice).length,澱粉:entries.filter(x=>!x.carbChoice).length,飲料穩定度:entries.filter(x=>!x.drinkChoice||!["水","無糖茶","無糖飲","黑咖啡","無糖豆漿"].some(v=>x.drinkChoice.includes(v))).length},mostMissing=Object.entries(missing).sort((a,b)=>b[1]-a[1])[0],cravingDays=entries.filter(x=>x.cravingAfterDinner==="有"||x.cravingAfterDinner==="一點點").map(x=>new Date(x.createdAt).toLocaleDateString("zh-TW")),sweetWithCraving=entries.filter(x=>x.hadSweetDrink&&(x.cravingAfterDinner==="有"||x.cravingAfterDinner==="一點點")).length;return {count:entries.length,commonScene,mostMissing:mostMissing&&mostMissing[1]>0?mostMissing[0]:"目前沒有明顯缺口",cravingDays,sweetWithCraving,suggestion:`你這幾次晚餐最常出現在「${commonScene}」，目前較需要留意「${mostMissing&&mostMissing[1]>0?mostMissing[0]:"固定備案"}」。建議先固定 2 個不用思考的外食備案，並把晚餐飲料改成水或無糖茶。`}}
