export type DrinkField={key:string;label:string;type:"text"|"textarea"|"radio"|"checkbox"|"slider"|"textArray";options?:readonly string[];placeholder?:string};
export type DrinkDay={day:number;title:string;intro:string;fields:DrinkField[]};
const sugar=["全糖","少糖","半糖","微糖","無糖"];
export const drinkResetContent={
  title:"7 天含糖飲料重置表",subtitle:"不靠硬戒，先看懂自己為什麼想喝，再建立真正適合生活的飲料規則。",overview:"每天只做一個小練習：記錄、找觸發、糖度降階、減加料、先補水、建立替代清單，最後整理成你的個人飲料規則。",saved:"✓ 已儲存",saving:"儲存中…",saveError:"儲存失敗，請確認網路後再試",complete:"完成今天",back:"回到 7 天總覽",previous:"上一天",next:"下一天",disclaimer:"這是依照填寫內容整理的自我觀察結果，不是醫療診斷。",invalid:"這個工具包連結無效、尚未付款，或未包含主商品。請從購買信件中的專屬連結重新進入。",
  days:[
    {day:1,title:"只記錄，不改變",intro:"今天不要求改變，只誠實記下喝之前與喝之後的狀態。",fields:[{key:"drinkName",label:"今天喝了什麼？",type:"text",placeholder:"例如：珍珠奶茶"},{key:"drinkTime",label:"飲用時間",type:"text",placeholder:"例如：下午 3:30"},{key:"sugarLevel",label:"甜度",type:"radio",options:sugar},{key:"toppings",label:"加料",type:"checkbox",options:["珍珠","椰果","布丁","粉粿","奶蓋","沒有","其他"]},{key:"cupSize",label:"杯型",type:"radio",options:["大杯","中杯","小杯"]},{key:"emotionBefore",label:"喝之前的狀態",type:"checkbox",options:["累","壓力","無聊","想獎勵","口渴","習慣","其他"]},{key:"afterFeeling",label:"喝完後的感覺",type:"checkbox",options:["滿足","放鬆","想睡","內疚","更想吃","沒感覺"]},{key:"observation",label:"今天的小觀察",type:"textarea"}]},
    {day:2,title:"找出飲料觸發點",intro:"想喝飲料通常有固定的時間、情緒或情境，今天先把它找出來。",fields:[{key:"triggerTypes",label:"哪些情境最容易讓我想喝？",type:"checkbox",options:["下午2-5點","下班路上","吃飯時","工作壓力大","心情不好","同事揪團","睡不好很累","想犒賞自己","口渴但懶得喝水","習慣想喝","白天吃太少"]},{key:"mainTrigger",label:"最主要的觸發點",type:"text"},{key:"triggerDescription",label:"這個觸發通常怎麼發生？",type:"textarea"}]},
    {day:3,title:"糖度降一階",intro:"不必直接變無糖，只要從平常的甜度往下降一階。",fields:[{key:"usualDrink",label:"平常最常喝的飲料",type:"text"},{key:"usualSugarLevel",label:"平常甜度",type:"radio",options:sugar},{key:"targetSugarLevel",label:"今天目標甜度",type:"radio",options:sugar},{key:"fearOrConcern",label:"降低甜度最擔心什麼？",type:"textarea"},{key:"completedSugarDown",label:"今天有做到嗎？",type:"radio",options:["有做到","還沒做到","部分做到"]}]},
    {day:4,title:"拿掉最容易爆糖的加料",intro:"先暫停一種最容易讓糖量和份量增加的加料。",fields:[{key:"pauseToppings",label:"我想先暫停的加料",type:"checkbox",options:["珍珠","粉粿","布丁","椰果","奶蓋","芋圓","仙草凍加奶精","大杯加料","其他"]},{key:"hardestTopping",label:"最難放下的加料",type:"text"},{key:"toppingFeeling",label:"這個加料帶給我的感覺",type:"checkbox",options:["飽足","嚼感","安慰","犒賞","習慣","其他"]},{key:"todayRemovedTopping",label:"今天實際拿掉了什麼？",type:"text"}]},
    {day:5,title:"想喝前先補水",intro:"先喝水不是禁止飲料，而是讓口渴不再被誤認成飲料需求。",fields:[{key:"cravingTime",label:"想喝飲料的時間",type:"text"},{key:"cravingBeforeWater",label:"喝水前想喝程度",type:"slider"},{key:"waterAmount",label:"先喝了多少水？",type:"text",placeholder:"例如：300ml"},{key:"cravingAfter10Min",label:"10 分鐘後還想喝嗎？",type:"radio",options:["想","不想","降低很多"]},{key:"adjustment",label:"最後做了哪些調整？",type:"checkbox",options:["降糖","不加料","改小杯","改無糖","沒有調整"]},{key:"reflection",label:"補水後的觀察",type:"textarea"}]},
    {day:6,title:"建立我的替代飲料清單",intro:"替不同需求準備替代選項，比只告訴自己不能喝更容易執行。",fields:[{key:"afternoonEnergyAlternative",label:"下午提神替代",type:"text"},{key:"stressSweetAlternative",label:"壓力想甜替代",type:"text"},{key:"mealDrinkAlternative",label:"搭餐飲品替代",type:"text"},{key:"milkTeaAlternative",label:"奶茶替代",type:"text"},{key:"coffeeAlternative",label:"咖啡替代",type:"text"},{key:"sparklingAlternative",label:"氣泡口感替代",type:"text"},{key:"ritualAlternative",label:"儀式感替代",type:"text"},{key:"top3Alternatives",label:"我的前三名替代飲料",type:"textArray"}]},
    {day:7,title:"設計我的飲料規則",intro:"把這七天的發現整理成下週也能繼續執行的個人規則。",fields:[{key:"weeklyDrinkLimit",label:"每週飲料次數",type:"text"},{key:"sugarLimit",label:"甜度上限",type:"text"},{key:"toppingRule",label:"加料規則",type:"text"},{key:"allowedSituations",label:"允許喝飲料的情境",type:"text"},{key:"beforeDrinkAction",label:"喝之前先做什麼？",type:"text"},{key:"dinnerAdjustmentIfDrank",label:"今天喝了飲料，晚餐怎麼調整？",type:"text"},{key:"recoveryIfBreakRule",label:"破例後如何回到規則？",type:"text"},{key:"nextWeekCommitment",label:"我對下週的承諾",type:"textarea"}]}
  ] as DrinkDay[],
  report:{title:"我的飲料降糖線索",recordedDays:"留下紀錄的天數",sugar:"最常見糖度",topping:"最常見加料",trigger:"最常見觸發點",emotion:"最常見情緒",highRiskTime:"下午或下班後衝動",waterWorked:"先補水後是否下降",patterns:"初步模式提示",ctaTitle:"想知道自己更深層的減脂卡關原因？",ctaText:"如果你發現自己總是靠飲料撐過下午，可能不只是飲料問題，而是白天營養、蛋白質、水量、壓力和作息一起影響。你可以接著完成 AI 能量減脂初評。",cta:"前往 AI 能量減脂初評"}
} as const;

export type DrinkDayState={data:Record<string,unknown>;isCompleted:boolean;completedAt:string|null};
const strings=(value:unknown)=>Array.isArray(value)?value.filter((x):x is string=>typeof x==="string"):typeof value==="string"&&value? [value]:[];
const common=(values:string[])=>Object.entries(values.reduce<Record<string,number>>((m,x)=>(m[x]=(m[x]??0)+1,m),{})).sort((a,b)=>b[1]-a[1])[0]?.[0]??"資料不足";
export function buildDrinkResetReport(days:Record<number,DrinkDayState>){const all=Object.values(days),data=all.map(x=>x.data),recordedDays=data.filter(item=>Object.values(item).some(value=>Array.isArray(value)?value.length>0:value!==""&&value!==undefined&&value!==null)).length;const sugar=common(data.flatMap(item=>strings(item.sugarLevel).concat(strings(item.usualSugarLevel),strings(item.targetSugarLevel)))),topping=common(data.flatMap(item=>strings(item.toppings).concat(strings(item.pauseToppings)))),trigger=common(data.flatMap(item=>strings(item.triggerTypes))),emotion=common(data.flatMap(item=>strings(item.emotionBefore)));const triggers=data.flatMap(item=>strings(item.triggerTypes)),emotions=data.flatMap(item=>strings(item.emotionBefore)),highRisk=triggers.some(x=>x==="下午2-5點"||x==="下班路上"),waterWorked=data.some(item=>item.cravingAfter10Min==="不想"||item.cravingAfter10Min==="降低很多");const patterns=[(triggers.includes("睡不好很累")||emotions.includes("累"))&&"疲憊提神型",(triggers.includes("工作壓力大")||emotions.includes("壓力"))&&"壓力放鬆型",(triggers.includes("想犒賞自己")||emotions.includes("想獎勵"))&&"獎勵儀式型",triggers.includes("同事揪團")&&"社交習慣型",triggers.includes("白天吃太少")&&"營養不足型"].filter(Boolean) as string[];return {recordedDays,sugar,topping,trigger,emotion,highRisk,waterWorked,patterns};}
