export type NutritionField={key:string;label:string;type:"date"|"text"|"textarea"|"radio"|"checkbox"|"slider";options?:readonly string[];placeholder?:string};
export type NutritionSection={title:string;description?:string;fields:NutritionField[]};
const protein=["有","沒有","沒吃"],yesNo=["有","沒有"],uncertain=["有","沒有","不確定"];
export const mindfulNutritionContent={
  title:"正念營養缺口掃描",subtitle:"快速檢查白天吃得穩不穩，找出晚上嘴饞可能的營養缺口",intro:"先完成一次快速掃描；若想看見更完整模式，也可以繼續進行 3 天觀察或 7 天追蹤。",invalid:"這個專屬連結無效、訂單尚未付款，或未包含《下班後嘴饞止損包》。請從購買完成信中的工具包連結重新進入。",saved:"✓ 已儲存",saving:"儲存中…",saveError:"儲存失敗，請確認網路後再試",complete:"完成今天",back:"回到 7 天總覽",previous:"上一天",next:"下一天",disclaimer:"本工具僅供一般健康教育與自我觀察，不是醫療診斷，也不保證減重效果。",
  sections:[
    {title:"今天的餐點與身體感受",fields:[{key:"date",label:"紀錄日期",type:"date"},{key:"breakfastText",label:"早餐吃了什麼？",type:"textarea"},{key:"breakfastProtein",label:"早餐有蛋白質嗎？",type:"radio",options:protein},{key:"breakfastSatiety",label:"早餐後飽足感",type:"slider"},{key:"lunchText",label:"午餐吃了什麼？",type:"textarea"},{key:"lunchProtein",label:"午餐有蛋白質嗎？",type:"radio",options:protein},{key:"lunchSatiety",label:"午餐後飽足感",type:"slider"},{key:"waterEnough",label:"今天水分足夠嗎？",type:"radio",options:["夠","不夠","不確定"]},{key:"sugaryDrink",label:"今天有含糖飲料嗎？",type:"radio",options:yesNo},{key:"afternoonFatigue",label:"下午疲憊程度",type:"slider"},{key:"afternoonDrinkCraving",label:"下午想喝飲料程度",type:"slider"},{key:"dinnerText",label:"晚餐吃了什麼？",type:"textarea"},{key:"dinnerProtein",label:"晚餐有蛋白質嗎？",type:"radio",options:uncertain},{key:"dinnerSatiety",label:"晚餐後飽足感",type:"slider"},{key:"nightCraving",label:"晚上有嘴饞嗎？",type:"radio",options:yesNo},{key:"nightCravingScore",label:"睡前嘴饞程度",type:"slider"},{key:"stressScore",label:"今日壓力程度",type:"slider"},{key:"unstableMeal",label:"今天較不穩定的餐次",type:"checkbox",options:["早餐","午餐","晚餐","點心飲料"]}]},
    {title:"正念吃飯檢查",description:"不用每項都做到，只要看見今天是怎麼吃飯的。",fields:[{key:"mindfulEating",label:"今天有哪些情況？",type:"checkbox",options:["坐下來好好吃飯","有放慢速度","沒有一直滑手機","有感覺幾分飽","吃完有滿足感","有一餐匆忙解決","吃完仍覺得空","壓力大吃很快"]},{key:"rushedMeal",label:"今天吃得最急的一餐是？",type:"text"},{key:"rushedReason",label:"當時正在趕什麼或心裡在想什麼？",type:"textarea"}]},
    {title:"白天營養缺口檢查",fields:[{key:"nutritionGaps",label:"今天可能出現的缺口",type:"checkbox",options:["早餐沒吃","早餐沒有蛋白質","午餐只有澱粉","午餐份量太少","水喝太少","下午靠含糖飲料撐","晚餐太晚吃","晚餐蛋白質不足","壓力太高","睡眠不足"]},{key:"biggestGapToday",label:"今天最可能影響晚上嘴饞的缺口是什麼？",type:"textarea"}]},
    {title:"晚間嘴饞回推",fields:[{key:"nightCravingTime",label:"晚上幾點開始嘴饞？",type:"text"},{key:"nightCravingItem",label:"想吃或想喝什麼？",type:"text"},{key:"trulyHungry",label:"當時是真的餓嗎？",type:"radio",options:["是","否","不確定"]},{key:"mostUnstableMeal",label:"今天哪一餐最不穩？",type:"text"},{key:"lowWaterToday",label:"今天水分偏少？",type:"radio",options:uncertain},{key:"lowProteinToday",label:"今天蛋白質偏少？",type:"radio",options:uncertain},{key:"highStressOrFatigue",label:"今天壓力或疲憊偏高？",type:"radio",options:uncertain},{key:"nightCravingReason",label:"這次嘴饞最可能和什麼有關？",type:"textarea"}]}
  ] as NutritionSection[],
  formula:{title:"外食營養穩定公式",formula:"蛋白質一掌 + 蔬菜三拳 + 澱粉一拳 + 水或無糖飲",tips:["早餐店：蛋餅加蛋 + 無糖豆漿，少用奶茶當早餐","便利商店：茶葉蛋 + 雞胸 + 沙拉 + 地瓜或飯糰","便當店：主菜 + 多青菜 + 飯半碗到一碗","麵店：湯麵加蛋或肉，再補一份青菜","速食店：主餐保留，飲料換無糖，薯條減量"]},
  report:{title:"你的 7 天營養追蹤結果",earlyTitle:"你的初步營養觀察",unstable:"最常不穩的餐次",gaps:"最常出現的缺口",craving:"晚間嘴饞平均分數",drinks:"含糖飲料出現次數",observations:"初步觀察",next:"下一步建議",aiTitle:"前往 AI 能量減脂初評",aiText:"如果你已經加購 1 元 AI 能量減脂初評，點擊後即可前往填寫與領取。若尚未加購，點擊後會進入加購頁，完成後即可開始測驗。",home:"回到工具包首頁"}
} as const;

export type NutritionDayState={data:Record<string,unknown>;isCompleted:boolean;completedAt:string|null};
const list=(v:unknown)=>Array.isArray(v)?v.filter((x):x is string=>typeof x==="string"):[];
const avg=(values:number[])=>values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length*10)/10:0;
const common=(values:string[])=>Object.entries(values.reduce<Record<string,number>>((m,x)=>(m[x]=(m[x]??0)+1,m),{})).sort((a,b)=>b[1]-a[1]).slice(0,3).map(x=>x[0]);
export function buildMindfulNutritionSummary(days:Record<number,NutritionDayState>){const completed=Object.values(days).filter(x=>x.isCompleted),data=completed.map(x=>x.data),breakfastProteinMissingCount=data.filter(x=>x.breakfastProtein==="沒有"||x.breakfastProtein==="沒吃").length,lunchProteinMissingCount=data.filter(x=>x.lunchProtein==="沒有"||x.lunchProtein==="沒吃").length,lowWaterCount=data.filter(x=>x.waterEnough==="不夠").length,sugaryDrinkCount=data.filter(x=>x.sugaryDrink==="有").length,nightCravingCount=data.filter(x=>x.nightCraving==="有").length,averageNightCravingScore=avg(data.map(x=>x.nightCravingScore).filter((x):x is number=>typeof x==="number")),averageStressScore=avg(data.map(x=>x.stressScore).filter((x):x is number=>typeof x==="number")),mostCommonUnstableMeal=common(data.flatMap(x=>list(x.unstableMeal))),mostCommonNutritionGaps=common(data.flatMap(x=>list(x.nutritionGaps)));const observations=[breakfastProteinMissingCount>=3&&"你這 7 天早餐蛋白質比較不穩，下午想喝飲料或晚上嘴饞可能和白天能量不足有關。",lunchProteinMissingCount>=3&&"你的午餐穩定度可能需要優先調整。午餐蛋白質不足時，下午疲憊與晚間嘴饞通常更容易出現。",lowWaterCount>=3&&"水分不足可能讓你更容易把口渴誤認成想喝甜或嘴饞。",sugaryDrinkCount>=3&&"含糖飲料已經是你日常能量與情緒調節的一部分，建議搭配 7 天含糖飲料重置表一起使用。",averageStressScore>=7&&"你的嘴饞可能和壓力、疲憊有明顯關聯，建議搭配嘴饞前 3 分鐘身心連結工作本。",nightCravingCount>=4&&"晚間嘴饞出現頻率偏高，建議回頭檢查白天蛋白質、水分、午餐飽足感和晚餐穩定度。"].filter(Boolean) as string[];return {totalCompletedDays:completed.length,breakfastProteinMissingCount,lunchProteinMissingCount,lowWaterCount,sugaryDrinkCount,nightCravingCount,averageNightCravingScore,averageStressScore,mostCommonUnstableMeal,mostCommonNutritionGaps,observations};}
