export type ToolPreview={id:string;name:string;core:string;description:string;bullets:string[];usage:string;pdfLabel:string;mobileLabel:string;pdfImage:string;mobileImage:string};
export const salesPageAssets={creator:{image:"/game-assets/brand/chongming-profile.jpg",name:"崇銘老師"},tools:[
{id:"body-mind",name:"嘴饞前 3 分鐘身心連結工作本",core:"當你突然很想吃，先花 3 分鐘分辨：我現在真正需要的是什麼？",description:"透過簡單的身體掃描與情緒覺察，在直接開吃以前，先多停留 3 分鐘。",bullets:["太累或太煩","情緒委屈","壓力太大","只是想舒服一下"],usage:"壓力大、情緒不好、突然很想吃特定食物時。",pdfLabel:"PDF 閱讀／列印版",mobileLabel:"手機互動版",pdfImage:"/game-assets/tool-previews/body-mind/pdf-preview.png",mobileImage:"/game-assets/tool-previews/body-mind/mobile-preview.png"},
{id:"trigger-analysis",name:"下班後嘴饞觸發點分析表",core:"找出每次失控前，重複出現的時間、場景與情緒。",description:"把原本模糊的『突然嘴饞』，整理成可以看見的觸發組合。",bullets:["下班＋很累＋經過超商","沙發＋追劇＋零食在旁邊","壓力＋外送 App＋想犒賞自己"],usage:"常常在固定時間、固定場景失控的人。",pdfLabel:"PDF 紀錄／列印版",mobileLabel:"手機互動分析版",pdfImage:"/game-assets/tool-previews/trigger-analysis/pdf-preview.png",mobileImage:"/game-assets/tool-previews/trigger-analysis/mobile-preview.png"},
{id:"drink-reset",name:"7 天含糖飲料重置表",core:"不用明天開始全部戒掉，先重新找回飲料選擇權。",description:"用 7 天從記錄、降糖、拿掉加料、補水到替代選項，建立能長期執行的飲料規則。",bullets:["手搖飲與甜咖啡","糖度與加料降階","補水與替代方案"],usage:"下午一定想喝飲料，或多次戒飲料失敗的人。",pdfLabel:"PDF 紀錄／列印版",mobileLabel:"7 天互動追蹤版",pdfImage:"/game-assets/tool-previews/drink-reset/pdf-preview.png",mobileImage:"/game-assets/tool-previews/drink-reset/mobile-preview.png"},
{id:"nutrition-scan",name:"正念營養缺口掃描",core:"晚上一直想吃，問題可能早在白天就開始累積。",description:"快速檢查早餐、午餐、水分、蛋白質與下午能量，找出最需要先修補的缺口。",bullets:["早餐是否有蛋白質","午餐是否吃太少","水分與下午補給是否穩定"],usage:"白天吃很少，晚上卻特別容易爆餓的人。",pdfLabel:"PDF 自我檢查版",mobileLabel:"手機評分分析版",pdfImage:"/game-assets/tool-previews/nutrition-scan/pdf-preview.png",mobileImage:"/game-assets/tool-previews/nutrition-scan/mobile-preview.png"},
{id:"emergency-flow",name:"10 分鐘嘴饞急救流程卡",core:"已經很想打開冰箱、零食櫃或外送 App？先跟著做 10 分鐘。",description:"不是禁止你吃，而是在『想到就吃』之間，加入暫停、喝水、辨認與重新選擇。",bullets:["暫停與喝水","身體、情緒辨認","安全替換與重新選擇"],usage:"嘴饞已經來了，現在就很想吃的時候。",pdfLabel:"PDF 流程卡／列印版",mobileLabel:"手機急救流程版",pdfImage:"/game-assets/tool-previews/emergency-flow/pdf-preview.png",mobileImage:"/game-assets/tool-previews/emergency-flow/mobile-preview.png"}
] as ToolPreview[],proTools:[
{name:"含糖飲料替換清單 Pro",subtitle:"把『我要戒飲料』變成『我知道下一杯怎麼點』。",pdfImage:"/game-assets/pro-tools/drink-swap/pdf-preview.png",mobileImage:"/game-assets/pro-tools/drink-swap/mobile-preview.png"},
{name:"外食補給導航 Pro",subtitle:"到不同地方，都知道這餐缺什麼，以及下一步怎麼補。",pdfImage:"/game-assets/pro-tools/eating-navigation/pdf-preview.png",mobileImage:"/game-assets/pro-tools/eating-navigation/mobile-preview.png"}
]};
