"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {defaultDrinkRules,drinkCategories,drinkItems,favoriteContexts,feelingGuides,quickScenarios,type DrinkCategory,type DrinkFeeling} from "@/content/drinkData";
import {analyzeSevenDayObservations,buildDrinkAnalysis} from "@/lib/drink-swap-analysis";

type View="home"|"navigate"|"scenarios"|"favorites"|"rules"|"observe";
const riskLabels={sugar:"糖量風險",volume:"杯量風險",topping:"加料風險",emptyStomach:"空腹刺激",dependency:"依賴風險"};
const feelings=Object.keys(feelingGuides) as DrinkFeeling[];
const choice=(items:readonly string[],value:string|string[],set:(v:any)=>void,multi=false)=><div className="dp-choices">{items.map(item=>{const on=Array.isArray(value)?value.includes(item):value===item;return <button type="button" className={on?"on":""} key={item} onClick={()=>set(multi?(on?(value as string[]).filter(x=>x!==item):[...(value as string[]),item]):item)}>{on?"✓ ":""}{item}</button>})}</div>;

export default function DrinkSwapProClient({token}:{token:string}){
 const [view,setView]=useState<View>("home"),[category,setCategory]=useState<DrinkCategory|"">(""),[feeling,setFeeling]=useState<DrinkFeeling|"">(""),[drinkId,setDrinkId]=useState(""),[query,setQuery]=useState(""),[sugar,setSugar]=useState("半糖"),[cup,setCup]=useState("中杯"),[toppings,setToppings]=useState<string[]>(["不加料"]),[context,setContext]=useState("下午提神"),[result,setResult]=useState<any>(null),[records,setRecords]=useState<any[]>([]),[favorites,setFavorites]=useState<any[]>([]),[rules,setRules]=useState<string[]>(defaultDrinkRules),[observations,setObservations]=useState<any[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[favoriteNote,setFavoriteNote]=useState("");
 useEffect(()=>{fetch(`/api/drink-swap-pro/${token}`).then(r=>r.ok?r.json():null).then(data=>{if(data){setRecords(data.records);setFavorites(data.favorites);setRules(data.rules);setObservations(data.observations)}})},[token]);
 const selected=drinkItems.find(x=>x.id===drinkId);
 const filtered=useMemo(()=>drinkItems.filter(x=>(!category||x.category===category)&&(!query||x.name.includes(query)||x.tags.some(t=>t.includes(query)))&&(!feeling||x.tags.includes(feeling))),[category,query,feeling]);
 const preview=selected&&feeling?buildDrinkAnalysis({drinkId,feeling,sugarHabit:sugar,cupSize:cup,toppings,context}):null;
 const observationAnalysis=analyzeSevenDayObservations(observations);
 function start(){setView("navigate");setMessage("");window.scrollTo({top:0,behavior:"smooth"})}
 async function analyze(){if(!selected||!feeling)return setMessage("請先選擇想要的感覺與飲料");setBusy(true);const response=await fetch(`/api/drink-swap-pro/${token}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({drinkId,feeling,sugarHabit:sugar,toppings,cupSize:cup,context})}),data=await response.json();if(response.ok){setResult(data.analysis);setRecords(old=>[data.record,...old]);setMessage("");}else setMessage(data.error);setBusy(false)}
 async function saveFavorite(){if(!selected||!result)return;setBusy(true);const response=await fetch(`/api/drink-swap-pro/${token}/favorites`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({drinkId:selected.id,favoriteCategory:"我的常喝收藏",title:selected.name,content:result.summary,orderScript:result.oneThingRule,context,originalVersion:selected.versions.original,currentVersion:result.recommendedVersion,note:favoriteNote})}),data=await response.json();if(response.ok){setFavorites(old=>[data.favorite,...old.filter(x=>x.id!==data.favorite.id)]);setMessage(data.message)}else setMessage(data.error);setBusy(false)}
 async function removeFavorite(id:string){const response=await fetch(`/api/drink-swap-pro/${token}/favorites/${id}`,{method:"DELETE"}),data=await response.json();if(response.ok)setFavorites(old=>old.filter(x=>x.id!==id));setMessage(data.message||data.error)}
 async function saveRules(){setBusy(true);const response=await fetch(`/api/drink-swap-pro/${token}/profile`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({rules})}),data=await response.json();setMessage(data.message||data.error);setBusy(false)}
 async function saveObservation(dayNumber:number,form:HTMLFormElement){const fd=new FormData(form),payload={dayNumber,time:fd.get("time"),feeling:fd.get("feeling"),version:fd.get("version"),reflection:fd.get("reflection")};setBusy(true);const response=await fetch(`/api/drink-swap-pro/${token}/profile`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),data=await response.json();if(response.ok)setObservations(data.observations);setMessage(data.message||data.error);setBusy(false)}
 return <div className="dp-app"><header><Link href={`/access/${token}`}>← 任務道具箱</Link><b>可樂吉健康研究所｜崇銘老師</b></header><main>
  <section className="dp-hero"><span>PREMIUM DRINK NAVIGATION</span><h1>含糖飲料<br/>替換清單 Pro</h1><h2>從你平常真的會喝的那一杯開始，找到做得到的降糖版本</h2><p>不是告訴你哪些飲料不能喝，而是保留你真正想要的感覺，再找出下一個做得到的版本。</p><div><button onClick={start}>開始導航</button><button onClick={()=>setView("favorites")}>查看常喝收藏</button><button onClick={()=>setView("scenarios")}>快速情境選飲</button></div></section>
  <nav className="dp-tabs">{([['home','首頁'],['navigate','飲料導航'],['scenarios','情境選飲'],['favorites','收藏'],['rules','我的規則'],['observe','7 天觀察']] as [View,string][]).map(([key,label])=><button className={view===key?"on":""} key={key} onClick={()=>setView(key)}>{label}</button>)}</nav>

  {view==="home"&&<><section className="dp-section"><span>DRINK CATEGORIES</span><h2>今天想從哪一類開始？</h2><div className="dp-categories">{Object.entries(drinkCategories).map(([key,name])=><button key={key} onClick={()=>{setCategory(key as DrinkCategory);start()}}><small>0{Object.keys(drinkCategories).indexOf(key)+1}</small><b>{name}</b><span>{drinkItems.filter(x=>x.category===key).length} 杯導航資料</span></button>)}<button className="scenario" onClick={()=>setView("scenarios")}><small>06</small><b>情境快速選</b><span>依你現在的狀態直接找選項</span></button></div></section><section className="dp-philosophy"><span>ONE CHANGE AT A TIME</span><h2>一杯飲料，只先改一件事</h2><p>先看杯量，再看甜度，最後才看配料。保留一個最在意的滿足感，比一次全部拿掉更容易長期做到。</p></section></>}

  {view==="navigate"&&<section className="dp-section dp-navigate"><span>DRINK NAVIGATOR</span><h2>先辨認你真正想要的感覺</h2>{choice(feelings,feeling,setFeeling)}{feeling&&<aside className="dp-guide"><b>{feeling}</b><p>{feelingGuides[feeling]}</p></aside>}<h3>選擇大類或直接搜尋</h3><div className="dp-filter"><button className={!category?"on":""} onClick={()=>setCategory("")}>全部</button>{Object.entries(drinkCategories).map(([key,name])=><button className={category===key?"on":""} key={key} onClick={()=>setCategory(key as DrinkCategory)}>{name}</button>)}</div><input className="dp-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜尋：珍珠奶茶、運動飲料、拿鐵…"/><div className="dp-drinks">{filtered.map(drink=><button className={drinkId===drink.id?"on":""} key={drink.id} onClick={()=>{setDrinkId(drink.id);setResult(null)}}><span>{drinkCategories[drink.category]}</span><b>{drink.name}</b><small>{drink.tags.join(" · ")}</small></button>)}</div>{selected&&<div className="dp-settings"><h2>你現在通常怎麼喝？</h2><h3>甜度</h3>{choice(["全糖","半糖","微糖","無糖"],sugar,setSugar)}<h3>杯量</h3>{choice(["大杯","中杯","小杯"],cup,setCup)}<h3>配料</h3>{choice(["珍珠","椰果","布丁","奶蓋","不加料"],toppings,setToppings,true)}<h3>常出現的情境</h3>{choice(favoriteContexts,context,setContext)}{preview&&"totalRisk" in preview&&<RiskRadar scores={(preview as any).scores}/>}<button className="dp-primary" disabled={busy||!feeling} onClick={analyze}>{busy?"正在分析…":"產生我的四層降糖導航"}</button></div>}{message&&<p className="dp-message">{message}</p>}{result&&selected&&<DrinkResult drink={selected} result={result} context={context} note={favoriteNote} setNote={setFavoriteNote} save={saveFavorite} busy={busy}/>}</section>}

  {view==="scenarios"&&<section className="dp-section"><span>QUICK SCENARIOS</span><h2>現在沒空分析？直接從情境選</h2><div className="dp-scenarios">{quickScenarios.map(item=><details key={item.id}><summary><b>{item.title}</b><span>展開 3 個選項＋</span></summary><ol>{item.options.map(x=><li key={x}>{x}</li>)}</ol><p>{item.advice}</p></details>)}</div></section>}

  {view==="favorites"&&<section className="dp-section"><span>MY COLLECTION</span><h2>我的常喝收藏</h2>{favorites.length?<div className="dp-favorites">{favorites.map(item=><article key={item.id}><span>{item.context||"常用備案"}</span><h3>{item.title}</h3><small>原本版本</small><p>{item.originalVersion||item.content}</p><small>現在的止損版本</small><p>{item.currentVersion||item.orderScript}</p>{item.note&&<blockquote>{item.note}</blockquote>}<button onClick={()=>removeFavorite(item.id)}>移除收藏</button></article>)}</div>:<div className="dp-empty"><b>還沒有收藏</b><p>完成一次飲料導航後，就能把做得到的版本留在這裡。</p><button onClick={start}>開始第一次導航</button></div>}</section>}

  {view==="rules"&&<section className="dp-section"><span>MY FIVE RULES</span><h2>我的 5 條飲料規則</h2><p>規則不是用來責備自己，而是讓疲憊或趕時間時不用重新思考。</p><div className="dp-rules">{rules.map((rule,index)=><label key={index}><b>0{index+1}</b><textarea value={rule} onChange={e=>setRules(old=>old.map((x,i)=>i===index?e.target.value:x))}/></label>)}</div><button className="dp-primary" disabled={busy} onClick={saveRules}>儲存我的飲料規則</button>{message&&<p className="dp-message">{message}</p>}</section>}

  {view==="observe"&&<section className="dp-section"><span>7-DAY OBSERVATION</span><h2>7 天飲料模式觀察</h2><p>每天只記四個線索，不需要計算熱量。</p><div className="dp-observation-summary"><b>目前分析</b><p>{observationAnalysis.summary}</p><strong>{observationAnalysis.suggestion}</strong></div><div className="dp-days">{Array.from({length:7},(_,i)=>{const day=i+1,old=observations.find(x=>x.dayNumber===day);return <form key={day} onSubmit={e=>{e.preventDefault();saveObservation(day,e.currentTarget)}}><span>DAY {day}</span><label>最常出現的時段<input name="time" required defaultValue={old?.time||""} placeholder="例如：下午 3～5 點"/></label><label>最想要的感覺<select name="feeling" required defaultValue={old?.feeling||""}><option value="">請選擇</option>{feelings.map(x=><option key={x}>{x}</option>)}</select></label><label>今天選到的版本<input name="version" required defaultValue={old?.version||""} placeholder="例如：小杯微糖、不加料"/></label><label>回顧一句話<textarea name="reflection" required defaultValue={old?.reflection||""}/></label><button disabled={busy}>{old?"更新這天":"儲存這天"}</button></form>})}</div>{message&&<p className="dp-message">{message}</p>}</section>}
 </main></div>
}

function RiskRadar({scores}:{scores:Record<string,number>}){return <section className="dp-radar"><div><span>RISK RADAR</span><h3>這杯目前的五格風險</h3></div>{Object.entries(riskLabels).map(([key,label])=><label key={key}><span>{label}</span><b>{scores[key]} / 5</b><i><em style={{width:`${scores[key]*20}%`}}/></i></label>)}</section>}
function DrinkResult({drink,result,context,note,setNote,save,busy}:{drink:any;result:any;context:string;note:string;setNote:(x:string)=>void;save:()=>void;busy:boolean}){return <section className="dp-result"><span>PERSONAL DRINK ROUTE</span><h2>{drink.name}｜我的降糖導航</h2><p className="lead">{result.summary}</p><RiskRadar scores={result.scores}/><div className="dp-analysis"><h3>為什麼這樣判斷？</h3>{result.reasons.map((x:string)=><p key={x}>• {x}</p>)}{result.scenarioNotes.map((x:string)=><small key={x}>{x}</small>)}</div><div className="dp-versions"><article className="original"><span>原版</span><p>{result.versions.original}</p></article><article><span>第一步</span><p>{result.versions.step1}</p></article><article className="recommended"><span>現在推薦</span><p>{result.recommendedVersion}</p></article><article><span>輕量版</span><p>{result.versions.light}</p></article></div><aside><b>這次只改一件事</b><p>{result.oneThingRule}</p></aside><div className="dp-save"><h3>收藏為「{context}」備案</h3><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="備註：哪一家、什麼時候最適合…"/><button disabled={busy} onClick={save}>♡ 加入我的常喝收藏</button></div></section>}
