import { Prisma } from "@prisma/client";
import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/db";
import { authorizeWorkbook } from "@/lib/workbook";
import { rateLimit,requestIp } from "@/lib/rate-limit";
import { buildDinnerSummary,dinnerFormulaContent,generateDinnerSuggestion } from "@/content/dinnerFormula";
const text=z.string().trim().min(1).max(300),score=z.number().int().min(0).max(10);
const body=z.object({hungerScore:score,fatigueScore:score,stressScore:score,currentStates:z.array(z.string().max(30)).min(1).max(10),mealScene:z.string().refine(x=>x in dinnerFormulaContent.scenes),proteinChoice:text,vegetableChoice:text,carbChoice:text,drinkChoice:text,closingAction:text});
const select={id:true,hungerScore:true,fatigueScore:true,stressScore:true,currentStates:true,mealScene:true,proteinChoice:true,vegetableChoice:true,carbChoice:true,drinkChoice:true,closingAction:true,generatedSuggestion:true,fullnessAfterDinner:true,cravingAfterDinner:true,hadSweetDrink:true,didClosingAction:true,reflection:true,createdAt:true,updatedAt:true} as const;
export async function GET(req:Request,{params}:{params:Promise<{accessToken:string}>}){const {accessToken}=await params;if(!await rateLimit(`dinner-read:${requestIp(req)}`,60,60_000))return NextResponse.json({error:"請稍後再試"},{status:429});if(!await authorizeWorkbook(accessToken))return NextResponse.json({error:"無法開啟晚餐選擇器"},{status:404});const entries=await prisma.dinnerFormulaEntry.findMany({where:{accessToken},orderBy:{createdAt:"desc"},take:7,select});return NextResponse.json({entries,summary:buildDinnerSummary(entries)});}
export async function POST(req:Request,{params}:{params:Promise<{accessToken:string}>}){const {accessToken}=await params;if(!await rateLimit(`dinner-write:${requestIp(req)}`,60,60_000))return NextResponse.json({error:"操作太頻繁，請稍候"},{status:429});const owner=await authorizeWorkbook(accessToken);if(!owner)return NextResponse.json({error:"無法儲存晚餐選擇"},{status:404});const parsed=body.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"請完成今晚的晚餐選擇"},{status:400});const x=parsed.data,scene=dinnerFormulaContent.scenes[x.mealScene];if(!scene.protein.includes(x.proteinChoice)||!scene.vegetable.includes(x.vegetableChoice)||!scene.carb.includes(x.carbChoice)||!scene.drink.includes(x.drinkChoice)||!dinnerFormulaContent.closingActions.includes(x.closingAction as never))return NextResponse.json({error:"晚餐選項不正確，請重新選擇"},{status:400});const generatedSuggestion=generateDinnerSuggestion(x);const entry=await prisma.dinnerFormulaEntry.create({data:{...x,currentStates:x.currentStates as Prisma.InputJsonValue,generatedSuggestion,accessToken,customerId:owner.customerId,orderId:owner.orderId},select});return NextResponse.json({entry},{status:201});}
