"use client";
import {useEffect,useMemo,useState} from "react";
import {branchKeys,branchRoutes,branchTrialQuestions,type BranchKey} from "@/content/branchRoutes";
import {analyzeBranchRoutes} from "@/lib/branch-route-analysis";
import type {JourneyContext} from "@/lib/journey-context";

export default function BranchRouteTrial({values,setInput,state,journey,setBranch}:{values:any;setInput:(key:string,value:unknown)=>void;state:any;journey:JourneyContext;setBranch:(key:BranchKey)=>void}){
 const answers:Record<string,string>=values.answers||{},[manual,setManual]=useState(false);
 const previous=useMemo(()=>Object.fromEntries((state.entries||[]).filter((x:any)=>x.levelNumber<=3).map((x:any)=>[x.levelNumber,x.analysisResult||{}])),[state.entries]);
 const analysis=useMemo(()=>analyzeBranchRoutes({answers,selectedBranch:values.selectedBranch},previous,{primaryType:state.quiz?.primaryType,primaryOriginalTypeName:state.characters.primary?.originalTypeName,characterName:state.characters.primary?.characterName}),[answers,values.selectedBranch,previous,state.quiz?.primaryType,state.characters.primary]);
 useEffect(()=>{setInput("recommendedBranch",analysis.recommendedBranch);setInput("secondaryBranch",analysis.secondaryBranch);setInput("branchAnalysis",analysis)},[analysis.recommendedBranch,analysis.secondaryBranch,analysis.confidence]);
 const answered=Object.keys(answers).length;
 const choose=(id:number,label:string)=>setInput("answers",{...answers,[String(id)]:label});
 const confirm=(key:BranchKey)=>{setInput("selectedBranch",key);setBranch(key);setManual(false)};
 return <div className="route-trial"><section className="route-results"><span>目前收集到的冒險線索</span><h3>前三關與角色資料已讀取</h3><div className="route-evidence"><article><b>時間線索</b><p>{journey.timeClue.highRiskTime||"目前線索不足"}</p></article><article><b>場景線索</b><p>{journey.sceneClue.sceneTriggerCombination||"目前線索不足"}</p></article><article><b>身心線索</b><p>{journey.signalClue.primaryResult||"目前線索不足"}</p></article><article><b>角色</b><p>{journey.character?.name||"尚未建立"}</p></article></div><p>接下來 8 個情境試煉，會和這些資料各占一半權重，找出最值得優先攻略的路線。</p></section><div className="route-trial-progress">{branchTrialQuestions.map(q=><i className={answers[String(q.id)]?"done":""} key={q.id}/>)}</div>{branchTrialQuestions.map(q=><section className="route-question" key={q.id}><span>情境試煉 {q.id} / 8</span><h3>{q.question}</h3><div className="bt-choice-grid">{q.options.map(option=><button type="button" className={answers[String(q.id)]===option.label?"selected":""} key={option.label} onClick={()=>choose(q.id,option.label)}>{answers[String(q.id)]===option.label?"✓ ":""}{option.label}</button>)}</div></section>)}<section className="route-results"><span>攻略路線分析</span><h2>{answered<8?`已完成 ${answered} / 8 題`:`主要攻略路線：${branchRoutes[analysis.recommendedBranch].name}`}</h2><p>{analysis.summary}</p><div className="route-score-grid">{branchKeys.map(key=><article key={key}><small>{branchRoutes[key].name}</small><strong>{analysis.scores[key].total}</strong><span>前三關 {analysis.scores[key].prior}｜試煉 {analysis.scores[key].trial}</span></article>)}</div>{answered===8&&<><div className="route-evidence"><article><h3>前三關支持證據</h3>{analysis.primaryEvidence.length?analysis.primaryEvidence.map(x=><p key={x}>• {x}</p>):<p>前三關線索較少，本次以 8 題試煉為主。</p>}</article><article><h3>第 4 關試煉證據</h3>{analysis.trialEvidence.map(x=><p key={x}>• {x}</p>)}</article><article><h3>次要路線：{branchRoutes[analysis.secondaryBranch].name}</h3>{analysis.secondaryEvidence.map(x=><p key={x}>• {x}</p>)}</article></div><p><b>綜合模式：</b>{analysis.combinedPattern}</p><div className="route-confirm"><button type="button" className={values.selectedBranch===analysis.recommendedBranch?"selected":""} onClick={()=>confirm(analysis.recommendedBranch)}>接受推薦｜{branchRoutes[analysis.recommendedBranch].name}</button><button type="button" onClick={()=>setManual(value=>!value)}>我想自己選擇路線</button></div>{manual&&<div className="route-confirm">{branchKeys.map(key=><button type="button" className={values.selectedBranch===key?"selected":""} key={key} onClick={()=>confirm(key)}>{branchRoutes[key].name}</button>)}</div>}{values.selectedBranch&&<p className="soft-note">你選擇的是「{branchRoutes[values.selectedBranch as BranchKey].name}」。系統原本推薦「{branchRoutes[analysis.recommendedBranch].name}」；後續會以你的選擇為主，同時保留「{branchRoutes[analysis.secondaryBranch].name}」線索。</p>}</>}</section></div>
}
