"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { branches, completionFeedback, levels, recommendation, typeName } from "@/content/breakthroughPlan";

const emptyMap = { highRiskTime:"", highRiskScene:"", mainEmotion:"", bodySignal:"", nutritionGap:"", highRiskDrinkOrSnack:"", safeSwapOptions:["","",""], dinnerBackups:["","",""], rescuePlan:"", firstRescueAction:"", nextWeekAction:"" };
const emptyInputs: Record<number, Record<string, unknown>> = {
  1:{occurredTime:"",period:"下午",cravingScore:5,fatigueScore:5},
  2:{scene:"",otherScene:""},
  3:{mainEmotion:"",bodySignal:""},
  4:{},
  5:{breakfastProtein:"",lunchEnough:"",waterEnough:"",afternoonDrink:"",tooHungryBeforeDinner:""},
  6:{dinnerBackups:["","",""]},
  7:{},
};

export default function BreakthroughPlanClient({ token, initialLevel=null }: { token:string; initialLevel?:number|null }) {
  const [state,setState]=useState<any>(null),[selected,setSelected]=useState<number|null>(initialLevel),[branch,setBranch]=useState<keyof typeof branches>("swap"),[inputs,setInputs]=useState(emptyInputs),[map,setMap]=useState<any>(emptyMap),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
  useEffect(()=>{fetch(`/api/breakthrough/${token}`).then(r=>r.json()).then(x=>{setState(x);const b=x.progress?.selectedBranch||x.profile?.branch;if(b)setBranch(b)})},[token]);
  if(!state)return <main className="bt-loading">正在整理你的破關路線…</main>;
  if(!state.progress.characterCreated)return <main className="bt-loading"><h1>請先完成第 0 天角色創建</h1><p>角色建立後，第 1～7 關才會解鎖。</p><Link className="bt-complete" href={`/access/${token}/character-creation`}>開始第 0 天｜創建嘴饞角色</Link></main>;
  const completed:number[]=state.progress.completedLevels||[],current=state.progress.currentLevel||1,done=completed.length>=7,level=selected?levels[selected-1]:null,profile=recommendation(state.quiz?.primaryType);
  const setInput=(key:string,value:unknown)=>selected&&setInputs(all=>({...all,[selected]:{...all[selected],[key]:value}}));
  const setList=(target:"map"|"input",key:string,index:number,value:string)=>{if(target==="map")setMap((old:any)=>({...old,[key]:old[key].map((x:string,i:number)=>i===index?value:x)}));else setInputs(all=>({...all,6:{...all[6],dinnerBackups:(all[6].dinnerBackups as string[]).map((x,i)=>i===index?value:x)}}))};
  async function complete(){if(!level)return;setSaving(true);setMessage("");const userInputs=inputs[level.level]||{};const payload:any={levelNumber:level.level,userInputs};if(level.level===4)payload.selectedBranch=branch;if(level.level===7)payload.map=map;const response=await fetch(`/api/breakthrough/${token}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),data=await response.json();if(response.ok){setState(data);setMessage(completionFeedback(level.level))}else setMessage(data.error||"目前無法完成");setSaving(false)}
  return <div className="bt-app"><header><Link href={`/access/${token}`}>← 回到計畫首頁</Link><b>{state.progress.actionPoints} 行動點數</b></header>{level?<LevelPage token={token} level={level} state={state} branch={branch} setBranch={setBranch} values={inputs[level.level]} setInput={setInput} map={map} setMap={setMap} setList={setList} message={message} saving={saving} completed={completed.includes(level.level)} complete={complete} close={()=>setSelected(null)}/>:<main className="bt-overview"><section className="bt-hero"><span>7-DAY BREAKTHROUGH PLAN</span><h1>7 天嘴饞破關計畫</h1><h2>每天完成一個小任務，解鎖你的減脂止損地圖</h2><div className="bt-progress"><i style={{width:`${completed.length/7*100}%`}}/><span>{completed.length} / 7 關</span></div></section>{profile&&<section className="bt-route"><span>你的嘴饞角色</span><h2>{state.characters.primary?.accentIcon} {state.characters.primary?.characterName}</h2><p>對應類型：{typeName(state.quiz?.primaryType)}　·　推薦：{profile.route}</p></section>}<section className="bt-levels">{levels.map(item=>{const isDone=completed.includes(item.level),locked=item.level>current&&!isDone;return <article className={`${isDone?"done":""} ${item.level===current&&!done?"current":""} ${locked?"locked":""}`} key={item.level}><div className="bt-level-head"><span>{item.icon}</span><small>第 {item.level} 關</small><b>{isDone?"已完成":locked?"尚未解鎖":item.level===current?"今日關卡":"可重新查看"}</b></div><h3>{item.name}</h3><p>{item.task}</p><dl><div><dt>線索</dt><dd>{item.clues.join("、")}</dd></div><div><dt>徽章</dt><dd>{item.badge}</dd></div></dl><button disabled={locked} onClick={()=>setSelected(item.level)}>{isDone?"查看關卡":"開始關卡 →"}</button></article>})}</section>{done&&state.map&&<RescueMap token={token} map={state.map} points={state.progress.actionPoints}/>}</main>}</div>;
}

function Score({label,value,onChange}:{label:string;value:number;onChange:(n:number)=>void}){return <label>{label}：<b>{value}</b><input type="range" min="0" max="10" value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
function LevelInputs({level,values,setInput,map,setMap,setList}:{level:number;values:any;setInput:any;map:any;setMap:any;setList:any}){
  if(level===1)return <div className="bt-inputs"><h3>主要輸入</h3><label>最近一次嘴饞發生時間<input type="time" value={values.occurredTime} onChange={e=>setInput("occurredTime",e.target.value)}/></label><label>發生時段<select value={values.period} onChange={e=>setInput("period",e.target.value)}>{["上午","下午","晚餐前","晚餐後","睡前"].map(x=><option key={x}>{x}</option>)}</select></label><Score label="嘴饞強度" value={values.cravingScore} onChange={n=>setInput("cravingScore",n)}/><Score label="當時有多累" value={values.fatigueScore} onChange={n=>setInput("fatigueScore",n)}/></div>;
  if(level===2)return <div className="bt-inputs"><h3>嘴饞最常發生在哪裡？</h3>{["下班路上","家裡沙發","辦公室","超商","手搖飲店","外送 App","睡前","其他"].map(x=><label key={x}><input type="radio" name="scene" checked={values.scene===x} onChange={()=>setInput("scene",x)}/>{x}</label>)}{values.scene==="其他"&&<input placeholder="請填寫其他場景" value={values.otherScene} onChange={e=>setInput("otherScene",e.target.value)}/>}</div>;
  if(level===3)return <div className="bt-inputs"><h3>今天辨認到的訊號</h3><label>主要情緒<input value={values.mainEmotion} onChange={e=>setInput("mainEmotion",e.target.value)} placeholder="例如：壓力、委屈、無聊"/></label><label>身體訊號<input value={values.bodySignal} onChange={e=>setInput("bodySignal",e.target.value)} placeholder="例如：胃空、肩頸緊、很疲憊"/></label></div>;
  if(level===5)return <div className="bt-inputs"><h3>快速掃描 5 件事</h3>{[["breakfastProtein","早餐有蛋白質"],["lunchEnough","午餐沒有吃太少"],["waterEnough","今天水有喝夠"],["afternoonDrink","下午沒有靠甜飲撐精神"],["tooHungryBeforeDinner","晚餐前沒有餓過頭"]].map(([key,label])=><label key={key}>{label}<select value={values[key]} onChange={e=>setInput(key,e.target.value)}><option value="">請選擇</option><option>有</option><option>沒有</option><option>不確定</option></select></label>)}</div>;
  if(level===6)return <div className="bt-inputs"><h3>我的 3 個晚餐備案</h3>{["很累時的備案","很餓時的備案","只能吃超商時的備案"].map((label,i)=><label key={label}>{label}<input value={values.dinnerBackups[i]} onChange={e=>setList("input","dinnerBackups",i,e.target.value)}/></label>)}</div>;
  if(level===7)return <MapForm map={map} setMap={setMap} setList={setList}/>;
  return null;
}

function LevelPage({token,level,state,branch,setBranch,values,setInput,map,setMap,setList,message,saving,completed,complete,close}:any){return <main className="bt-level-page"><button className="bt-back" onClick={close}>← 回到 7 關地圖</button><section className="bt-mission"><span>第 {level.level} 關｜今日關卡</span><h1>{level.name}</h1><h2>今天的任務目標：{level.task}</h2><div className="soft-note"><b>為什麼要做這一關？</b><p>{level.description}</p></div><div className="bt-mission-meta"><b>可收集：{level.clues.join("、")}</b><b>{level.icon} {level.badge}</b><b>＋{level.points} 行動點數</b></div>{level.level===4&&<div className="bt-branches"><p>系統推薦：<strong>{branches[(state.profile?.branch||"swap") as keyof typeof branches].name}</strong>。你也可以依照今天狀況切換。</p>{Object.entries(branches).map(([key,item])=><button className={branch===key?"selected":""} key={key} onClick={()=>setBranch(key)}><strong>{item.name}</strong><span>{item.tool}</span><small>{item.description}</small></button>)}</div>}<LevelInputs level={level.level} values={values} setInput={setInput} map={map} setMap={setMap} setList={setList}/><div className="bt-tool"><span>需要使用的任務道具</span><strong>{level.level===4?branches[branch as keyof typeof branches].tool:level.tool}</strong>{level.level!==7&&<Link href={`/access/${token}/${level.level===4?branches[branch as keyof typeof branches].path:level.path}`}>開啟任務道具 →</Link>}</div>{message&&<div className="bt-earned">{message}</div>}<button className="bt-complete" disabled={saving||completed} onClick={complete}>{completed?"✓ 本關已完成":saving?"正在解鎖…":"完成任務，收集線索"}</button><p className="bt-feedback"><b>完成後回饋：</b>{level.feedback}</p>{levels[level.level]&&<p className="bt-feedback"><b>下一關預告：</b>第 {levels[level.level].level} 關｜{levels[level.level].name}</p>}</section></main>}

function MapForm({map,setMap,setList}:any){const fields=[["highRiskTime","我的破功時間"],["highRiskScene","我的高風險場景"],["mainEmotion","我的主要情緒"],["bodySignal","我的身體訊號"],["nutritionGap","我的營養缺口"],["firstRescueAction","我的第一個止損動作"],["nextWeekAction","我的下週行動"]];return <div className="bt-inputs"><h3>整理我的個人止損地圖</h3>{fields.map(([key,label])=><label key={key}>{label}<input value={map[key]} onChange={e=>setMap((old:any)=>({...old,[key]:e.target.value}))}/></label>)}<h4>3 個晚餐備案</h4>{[0,1,2].map(i=><input key={i} value={map.dinnerBackups[i]} onChange={e=>setList("map","dinnerBackups",i,e.target.value)}/>)}</div>}

export function RescueMap({token,map,points}:{token:string;map:any;points:number}){const rewardUrl=process.env.NEXT_PUBLIC_REWARD_CLAIM_URL||"https://lin.ee/UKTsrwq";return <section id="rescue-map" className="bt-rescue-map"><span>PERSONAL RESCUE MAP</span><h2>我的個人止損地圖</h2><div><article><small>嘴饞角色</small><b>{map.primaryCharacterName||typeName(map.primaryType)}</b></article><article><small>對應類型</small><b>{map.primaryOriginalTypeName||typeName(map.primaryType)}</b></article><article><small>推薦路線</small><b>{map.recommendedRoute}</b></article><article><small>破功時間／場景</small><b>{map.highRiskTime||"待觀察"}・{map.highRiskScene||"待觀察"}</b></article><article><small>情緒／身體訊號</small><b>{map.mainEmotion||"待觀察"}・{map.bodySignal||"待觀察"}</b></article><article><small>下週行動</small><b>{map.nextWeekAction||"持續收集線索"}</b></article></div><strong>總行動點數：{points}</strong>{map.rewardUnlocked&&<section className="bt-earned"><h2>破關獎勵已解鎖</h2><h3>3 天實戰減脂體驗獎勵金</h3><p>你已完成 7 天嘴饞破關計畫。接下來可以把這 7 天找到的線索帶進 3 天實戰陪跑，讓教練協助你把飲食、外食、飲料與晚餐安排落地。</p><a className="bt-complete" href={rewardUrl} target="_blank" rel="noreferrer">領取 3 天實戰獎勵 →</a><small>此獎勵不保證減重結果；實際結果依個人狀況與執行情形而異。</small></section>}<Link href={`/access/${token}`}>回到任務道具箱 →</Link></section>}
