"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {branches as branchSource,completionFeedback,kingdomCopy,levels,recommendation,typeName,validateBreakthroughLevel} from "@/content/breakthroughPlan";
import {analyzeBreakthroughLevel as analyzeLevel} from "@/lib/breakthrough-analysis";
import {badgeForLevel} from "@/content/badgeConfig";

const emptyMap:any={highRiskTime:"",highRiskScene:"",mainEmotion:"",bodySignal:"",nutritionGap:"",highRiskDrinkOrSnack:"",safeSwapOptions:["","",""],dinnerBackups:["","",""],rescuePlan:"",firstRescueAction:"",nextWeekAction:""};
const emptyInputs:any={
1:{selectedTimes:[],primaryTime:"",cravingScore:5,hungerScore:5,fatigueScore:5,stressScore:5},
2:{selectedScenes:[],selectedTriggers:[],otherScene:""},
3:{stomachScore:5,fatigueScore:5,emotionStressScore:5,specificFoodCravingScore:5,trueHungerScore:5,selectedState:""},
4:{selectedAnswer:""},
5:{breakfastScore:1,lunchScore:1,waterScore:1,proteinScore:1,afternoonEnergyScore:1},
6:{dinnerScene:"超商",selectedProtein:"",selectedVegetable:"",selectedCarb:"",selectedDrink:"",savedDinnerBackups:["","",""]},7:{}
};
const toggle=(list:string[],value:string,max=99)=>list.includes(value)?list.filter(x=>x!==value):list.length<max?[...list,value]:list;
const branches:Record<string,any>=branchSource;

export default function BreakthroughPlanClient({token,initialLevel=null}:{token:string;initialLevel?:number|null}){
 const [state,setState]=useState<any>(null),[selected,setSelected]=useState<number|null>(initialLevel),[branch,setBranch]=useState<any>("swap"),[inputs,setInputs]=useState<any>(emptyInputs),[map,setMap]=useState<any>(emptyMap),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{fetch(`/api/breakthrough/${token}`).then(r=>r.json()).then(x=>{setState(x);const hydrated={...emptyInputs};for(const entry of x.entries||[])hydrated[entry.levelNumber]={...hydrated[entry.levelNumber],...(entry.userInputs||{})};setInputs(hydrated);const a1=analyzeLevel(1,hydrated[1]),a3=analyzeLevel(3,hydrated[3]),a5=analyzeLevel(5,hydrated[5]);setMap({...emptyMap,...(x.map||{}),highRiskTime:x.map?.highRiskTime||a1.highRiskTime||hydrated[1].primaryTime,highRiskScene:x.map?.highRiskScene||(hydrated[2].selectedScenes||[]).join("＋"),mainEmotion:x.map?.mainEmotion||a3.decodedSignalType||hydrated[3].selectedState,bodySignal:x.map?.bodySignal||hydrated[3].selectedState,nutritionGap:x.map?.nutritionGap||(a5.lowestItems||[]).join("、"),dinnerBackups:x.map?.dinnerBackups||hydrated[6].savedDinnerBackups});const b=x.progress?.selectedBranch||x.profile?.branch;if(b)setBranch(b)})},[token]);
 if(!state)return <main className="bt-loading">正在整理嘴饞迷霧中的線索…</main>;
 if(!state.progress.characterCreated)return <main className="bt-loading"><h1>進入迷霧王國前，請先創建角色</h1><p>完成第 0 天後，第 1～7 關才會依照你的角色路線解鎖。</p><Link className="bt-complete" href={`/access/${token}/character-creation`}>開始第 0 天｜創建嘴饞角色</Link></main>;
 const completed:number[]=state.progress.completedLevels||[],current=state.progress.currentLevel||1,done=completed.length>=7,level=selected?levels[selected-1]:null,profile=recommendation(state.quiz?.primaryType),badgeCount=state.progress.earnedBadges.length;
 const setInput=(key:string,value:unknown)=>selected&&setInputs((all:any)=>({...all,[selected]:{...all[selected],[key]:value}}));
 const prepareMap=()=>{const a1=analyzeLevel(1,inputs[1]),a3=analyzeLevel(3,inputs[3]),a5=analyzeLevel(5,inputs[5]),next={...map,highRiskTime:map.highRiskTime||a1.highRiskTime||inputs[1].primaryTime,highRiskScene:map.highRiskScene||(inputs[2].selectedScenes||[]).join("＋"),mainEmotion:map.mainEmotion||a3.decodedSignalType||inputs[3].selectedState,bodySignal:map.bodySignal||inputs[3].selectedState,nutritionGap:map.nutritionGap||(a5.lowestItems||[]).join("、"),dinnerBackups:(map.dinnerBackups||[]).some(Boolean)?map.dinnerBackups:inputs[6].savedDinnerBackups};setMap(next);return next};
 async function complete(){if(!level)return;const userInputs={...(inputs[level.level]||{}),analysisResult:analyzeLevel(level.level,inputs[level.level]||{})};if(level.level===4){const b=branches[branch],idx=b.options.indexOf(String(userInputs.selectedAnswer));userInputs.selectedBranch=branch;userInputs.recommendedBranch=state.profile?.branch;userInputs.isCorrect=idx===b.correct;userInputs.feedbackText=b.feedback}const finalMap=level.level===7?prepareMap():map,err=validateBreakthroughLevel(level.level,userInputs,finalMap);if(err){setMessage(err);return}setSaving(true);setMessage("正在保存分析結果…");const payload:any={levelNumber:level.level,userInputs};if(level.level===4)payload.selectedBranch=branch;if(level.level===7)payload.map=finalMap;const response=await fetch(`/api/breakthrough/${token}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),data=await response.json();if(response.ok){setState((old:any)=>({...old,progress:{...old.progress,currentLevel:Math.min(7,level.level+1),completedLevels:[...new Set([...old.progress.completedLevels,level.level])],earnedBadges:[...new Set([...old.progress.earnedBadges,level.badge])]}}));setMessage(completionFeedback(level.level));const badge=badgeForLevel(level.level),continueHref=level.level===7?`/access/${token}/personal-rescue-map`:`/access/${token}/breakthrough-plan/level/${level.level+1}`;if(badge)window.dispatchEvent(new CustomEvent("badge-unlocked",{detail:{badge,actionPoints:0,continueHref}}))}else setMessage(data.error||"目前無法完成");setSaving(false)}
 return <div className="bt-app fog-kingdom"><header><Link href={`/access/${token}`}>← 回到王國入口</Link><b>已解鎖徽章 {badgeCount} / 8</b></header>{level?<LevelPage token={token} level={level} state={state} branch={branch} setBranch={setBranch} values={inputs[level.level]} setInput={setInput} map={map} setMap={setMap} message={message} saving={saving} completed={completed.includes(level.level)} complete={complete} close={()=>setSelected(null)} prepareMap={prepareMap}/>:<main className="bt-overview"><section className="bt-hero"><span>{kingdomCopy.name}</span><h1>7 天嘴饞破關計畫</h1><h2>{kingdomCopy.hero}</h2><p>{kingdomCopy.intro}</p><div className="bt-kingdom-stats"><article><small>目前關卡</small><b>第 {done?7:current} 關 / 共 7 關</b></article><article><small>已解鎖徽章</small><b>{badgeCount} / 8</b></article><article><small>今日關卡</small><b>{done?"迷霧核心已破解":levels[current-1].name}</b></article><article><small>下一關預告</small><b>{done?"個人止損地圖":levels[current]?.name||"迷霧核心"}</b></article></div></section>{profile&&<section className="bt-route"><span>迷霧旅人的角色</span><h2>{state.characters.primary?.accentIcon} {state.characters.primary?.characterName}</h2><p>對應類型：{typeName(state.quiz?.primaryType)}　·　推薦：{profile.route}</p></section>}<section className="bt-levels">{levels.map(item=>{const isDone=completed.includes(item.level),locked=item.level>current&&!isDone;return <article className={`${isDone?"done":""} ${item.level===current&&!done?"current":""} ${locked?"locked":""}`} key={item.level}><div className="bt-level-head"><span>{item.icon}</span><small>第 {item.level} 關</small><b>{isDone?"徽章已解鎖":locked?"迷霧未散":item.level===current?"今日關卡":"可重新查看"}</b></div><h3>{item.name}</h3><p>{item.task}</p><dl><div><dt>線索</dt><dd>{item.clues.join("、")}</dd></div><div><dt>徽章</dt><dd>{item.badge}</dd></div></dl><button disabled={locked} onClick={()=>setSelected(item.level)}>{isDone?"查看關卡":"進入關卡 →"}</button></article>})}</section>{done&&state.map&&<RescueMap token={token} map={state.map}/>}</main>}</div>;
}

function Score({label,value,onChange}:{label:string;value:number;onChange:(n:number)=>void}){return <label className="bt-score"><span>{label}</span><b>{value}</b><input type="range" min="0" max="10" value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
function Cards({items,selected,onToggle,max=99}:{items:string[];selected:string[];onToggle:(v:string)=>void;max?:number}){return <div className="bt-choice-grid">{items.map(x=><button type="button" className={selected.includes(x)?"selected":""} key={x} onClick={()=>onToggle(x)}>{selected.includes(x)?"✓ ":""}{x}</button>)}</div>}
function Analysis({level,values}:{level:number;values:any}){const result=analyzeLevel(level,values);return <section className="bt-analysis"><span>系統分析結果 · 信心度 {result.confidence}</span><h3>{result.primaryResult}</h3><p>{result.explanation}</p><p><b>分析線索：</b>{result.insight}</p><p><b>建議先做：</b>{result.suggestedAction}</p></section>}

function LevelInputs({level,values,setInput,map,setMap,branch,setBranch,state,prepareMap}:any){
 if(level===1){const times=["上午","午餐後","下午 3～5 點","下班前","晚餐前","晚餐後","睡前","其他"];return <div className="bt-inputs"><h3>時間雷達</h3><p>先選出最近最常嘴饞的時間，可複選，再指定最明顯的一個熱區。</p><Cards items={times} selected={values.selectedTimes} onToggle={v=>setInput("selectedTimes",toggle(values.selectedTimes,v))}/><label>主要高風險時間<select value={values.primaryTime} onChange={e=>setInput("primaryTime",e.target.value)}><option value="">請選擇</option>{values.selectedTimes.map((x:string)=><option key={x}>{x}</option>)}</select></label>{[["嘴饞強度","cravingScore"],["飢餓感","hungerScore"],["疲憊感","fatigueScore"],["壓力感","stressScore"]].map(([l,k])=><Score key={k} label={l} value={values[k]} onChange={n=>setInput(k,n)}/>)}<Analysis level={1} values={values}/></div>}
 if(level===2){const scenes=["下班路上","辦公室","家裡沙發","超商","手搖飲店","外送 App","睡前房間","車上","追劇時","其他"],triggers=["看到食物","聞到味道","手機跳外送通知","壓力很大","太累","太無聊","跟別人一起吃","食物放太近","想獎勵自己","晚餐吃太少"];return <div className="bt-inputs"><h3>選擇高風險場景</h3><Cards items={scenes} selected={values.selectedScenes} onToggle={v=>setInput("selectedScenes",toggle(values.selectedScenes,v))}/><h3>挑選 1～3 張觸發卡</h3><Cards items={triggers} selected={values.selectedTriggers} max={3} onToggle={v=>setInput("selectedTriggers",toggle(values.selectedTriggers,v,3))}/><Analysis level={2} values={values}/></div>}
 if(level===3){return <div className="bt-inputs"><h3>身心訊號解碼器</h3>{[["胃部空感","stomachScore"],["頭腦疲憊","fatigueScore"],["情緒壓力","emotionStressScore"],["想吃特定食物","specificFoodCravingScore"],["什麼都可以吃的餓","trueHungerScore"]].map(([l,k])=><Score key={k} label={l} value={values[k]} onChange={n=>setInput(k,n)}/>)}<h3>最接近我現在的狀態</h3><Cards items={["我是真的餓","我是累了","我是壓力大","我是委屈","我是無聊","我只是嘴巴想吃","我想要放鬆"]} selected={values.selectedState?[values.selectedState]:[]} onToggle={v=>setInput("selectedState",v)}/><Analysis level={3} values={values}/></div>}
 if(level===4){const b=branches[branch];return <div className="bt-inputs"><h3>選擇支線</h3><p>系統推薦：<b>{branches[(state.profile?.branch||"swap") as keyof typeof branches].name}</b>。也可以依照現在最卡住的問題切換。</p><div className="bt-branches">{Object.entries(branches).map(([k,x])=><button type="button" className={branch===k?"selected":""} key={k} onClick={()=>{setBranch(k);setInput("selectedAnswer","")}}><strong>{x.name}</strong><small>{x.description}</small></button>)}</div><section className="bt-trial"><span>支線試煉</span><h3>{b.question}</h3><Cards items={[...b.options]} selected={values.selectedAnswer?[values.selectedAnswer]:[]} onToggle={v=>setInput("selectedAnswer",v)}/>{values.selectedAnswer&&<Analysis level={4} values={{...values,selectedBranch:branch,isCorrect:b.options.indexOf(values.selectedAnswer)===b.correct}}/>}</section></div>}
 if(level===5){const items=[["早餐洞","breakfastScore","早餐有沒有蛋白質？"],["午餐洞","lunchScore","午餐有沒有吃太少？"],["水分洞","waterScore","今天水喝夠嗎？"],["蛋白洞","proteinScore","今天蛋白質夠嗎？"],["下午能量洞","afternoonEnergyScore","下午是否不必靠甜飲撐精神？"]];return <div className="bt-inputs"><h3>營養補洞盤</h3><p>0＝幾乎沒有做到，1＝有一點，2＝做得不錯</p>{items.map(([name,key,q])=><label className="bt-nutrition-hole" key={key}><span><b>{name}</b>{q}</span><select value={values[key]} onChange={e=>setInput(key,Number(e.target.value))}><option value={0}>0 分</option><option value={1}>1 分</option><option value={2}>2 分</option></select></label>)}<Analysis level={5} values={values}/></div>}
 if(level===6){const setBackup=(i:number,v:string)=>setInput("savedDinnerBackups",values.savedDinnerBackups.map((x:string,n:number)=>n===i?v:x));return <div className="bt-inputs"><h3>3-1-1 晚餐防線建造器</h3><label>今晚場景<select value={values.dinnerScene} onChange={e=>setInput("dinnerScene",e.target.value)}>{["超商","便當店","早餐店","麵店","滷味","速食","外送","自助餐","火鍋"].map(x=><option key={x}>{x}</option>)}</select></label>{[["蛋白質卡","selectedProtein",["雞胸","茶葉蛋","雞腿","魚","豆腐","滷蛋","肉片"]],["蔬菜卡","selectedVegetable",["沙拉","燙青菜","自助餐青菜","菜盤","海帶","菇類"]],["澱粉卡","selectedCarb",["地瓜","飯半碗","飯糰","麵","冬粉"]],["飲料卡","selectedDrink",["水","無糖茶","無糖豆漿","無糖拿鐵"]]].map(([title,key,items]:any)=><section key={key}><h4>{title}</h4><Cards items={items} selected={values[key]?[values[key]]:[]} onToggle={v=>setInput(key,v)}/></section>)}<Analysis level={6} values={values}/><h3>保存我的 3 組晚餐備案</h3>{["很累時的備案","很餓時的備案","只能吃超商時的備案"].map((x,i)=><label key={x}>{x}<input value={values.savedDinnerBackups[i]} onChange={e=>setBackup(i,e.target.value)} placeholder="例如：雞胸＋沙拉＋地瓜＋無糖茶"/></label>)}</div>}
 return <MapForm map={map} setMap={setMap}/>;
}

function LevelPage({token,level,state,branch,setBranch,values,setInput,map,setMap,message,saving,completed,complete,close,prepareMap}:any){const next=levels[level.level];return <main className="bt-level-page"><button className="bt-back" onClick={close}>← 回到迷霧王國</button><section className="bt-mission"><span>嘴饞迷霧王國 · 第 {level.level} 關</span><h1>{level.name}</h1><p className="bt-story">{level.story}</p><div className="soft-note"><b>本關任務</b><p>{level.task}</p></div><div className="bt-mission-meta"><b>可收集：{level.clues.join("、")}</b><b>{level.icon} {level.badge}</b></div><LevelInputs level={level.level} values={values} setInput={setInput} map={map} setMap={setMap} branch={branch} setBranch={setBranch} state={state} prepareMap={prepareMap}/><div className="bt-tool"><span>本關任務道具</span><strong>{level.level===4?branches[branch].tool:level.tool}</strong>{level.level!==7&&level.level!==4&&<Link href={`/access/${token}/${level.path}`}>開啟完整道具 →</Link>}</div><section className="bt-learning"><span>本關學習重點</span><p>{level.learning}</p></section>{message&&<div className="bt-earned">{message}</div>}<button className="bt-complete" disabled={saving||completed} onClick={complete}>{completed?"✓ 本關徽章已解鎖":saving?"正在保存分析…":"完成任務，解鎖徽章"}</button><p className="bt-feedback"><b>完成回饋：</b>{level.feedback}</p>{next&&<p className="bt-feedback"><b>下一關預告：</b>第 {next.level} 關｜{next.name}</p>}</section></main>}

function MapForm({map,setMap}:any){const fields=[["highRiskTime","我的高風險時間"],["highRiskScene","我的高風險場景"],["mainEmotion","我的情緒與身體訊號"],["nutritionGap","我的最大營養缺口"]];const actions=["嘴饞先停 3 分鐘","想喝飲料前先喝水","晚餐先用 3-1-1","零食先分裝","下班先吃穩定晚餐","壓力大先做 10 分鐘急救流程"];const setBackup=(i:number,v:string)=>setMap((old:any)=>({...old,dinnerBackups:old.dinnerBackups.map((x:string,n:number)=>n===i?v:x)}));return <div className="bt-inputs"><h3>止損地圖拼圖</h3><p>確認或微調前六關收集到的線索。</p><div className="bt-map-puzzle">{fields.map(([key,label])=><label key={key}><span>{label}</span><input value={map[key]} onChange={e=>setMap((o:any)=>({...o,[key]:e.target.value}))}/></label>)}<section><span>我的晚餐防線</span>{[0,1,2].map(i=><input key={i} value={map.dinnerBackups[i]} onChange={e=>setBackup(i,e.target.value)} placeholder={`晚餐備案 ${i+1}`}/>)}</section></div><h3>我的第一個止損動作</h3><Cards items={actions} selected={map.firstRescueAction?[map.firstRescueAction]:[]} onToggle={v=>setMap((o:any)=>({...o,firstRescueAction:v}))}/><label>我的下週任務<textarea value={map.nextWeekAction} onChange={e=>setMap((o:any)=>({...o,nextWeekAction:e.target.value}))} placeholder="例如：下午想喝飲料時先喝 300ml 水"/></label><Analysis level={7} values={map}/></div>}

export function RescueMap({token,map}:{token:string;map:any;points?:number}){return <section id="rescue-map" className="bt-rescue-map"><span>迷霧核心已破解</span><h2>我的個人止損地圖</h2><div><article><small>嘴饞角色</small><b>{map.primaryCharacterName||typeName(map.primaryType)}</b></article><article><small>推薦路線</small><b>{map.recommendedRoute}</b></article><article><small>高風險時間／場景</small><b>{map.highRiskTime||"持續觀察"}・{map.highRiskScene||"持續觀察"}</b></article><article><small>情緒與身體訊號</small><b>{map.mainEmotion||"持續觀察"}・{map.bodySignal||"持續觀察"}</b></article><article><small>最大營養缺口</small><b>{map.nutritionGap||"持續觀察"}</b></article><article><small>第一個止損動作</small><b>{map.firstRescueAction||"先停 3 分鐘"}</b></article><article><small>晚餐防線</small><b>{Array.isArray(map.dinnerBackups)?map.dinnerBackups.filter(Boolean).join("／"):""}</b></article><article><small>下週任務</small><b>{map.nextWeekAction||"持續收集線索"}</b></article></div>{map.rewardUnlocked&&<section className="bt-reward-card"><h2>破關獎勵已解鎖</h2><h3>3 天實戰減脂體驗獎勵金</h3><p>你已收集所有關鍵徽章並生成個人止損地圖。接下來可以把這些線索帶進真實生活，由教練協助你把外食、飲料、晚餐與嘴饞策略落地。</p><Link className="bt-reward-button" href={`/access/${token}/reward`}>領取 3 天實戰獎勵 →</Link><small>此獎勵不保證減重結果；實際結果依個人狀況與執行情形而異。</small></section>}<Link className="bt-toolbox-link" href={`/access/${token}`}>回到任務道具箱 →</Link></section>}
