"use client";
import {useMemo,useRef,useState} from "react";
import {dinnerScenes,dinnerSceneById,type DinnerGroup} from "@/content/dinnerSceneConfig";
import {buildDinnerPriorityProfile,generateDinnerAnalysis,type DinnerBackup,type DinnerSelection} from "@/lib/dinner-defense-analysis";
import {BranchInfluenceCard} from "./JourneyConnection";

const asList=(value:unknown)=>Array.isArray(value)?value.map(String):value?[String(value)]:[];
const labelMap={protein:"蛋白質",vegetable:"蔬菜",carb:"適量主食",drink:"穩定飲料"};

export function DinnerSceneSelector({value,onChange}:{value:string;onChange:(id:string)=>void}){return <section className="dd-stage"><span>STAGE 1</span><h3>選擇今晚戰場</h3><div className="dd-scene-grid">{dinnerScenes.map(scene=><button type="button" className={value===scene.id?"selected":""} key={scene.id} onClick={()=>onChange(scene.id)}><b>{scene.name}</b><small>{scene.description}</small></button>)}</div></section>}

function FoodGroup({group,selections,onChange}:{group:DinnerGroup;selections:DinnerSelection;onChange:(next:DinnerSelection)=>void}){const selected=asList(selections[group.id]);return <section className="dd-food-group"><h4>{group.label}{group.required&&<small>必選</small>}</h4><div className="dd-option-grid">{group.options.map(option=><button type="button" className={selected.includes(option)?"selected":""} key={option} onClick={()=>{const next=group.multiple?(selected.includes(option)?selected.filter(x=>x!==option):[...selected,option]):option;onChange({...selections,[group.id]:next})}}>{selected.includes(option)?"✓ ":""}{option}</button>)}</div></section>}

export function SceneSpecificFoodBuilder({sceneId,selections,onChange}:{sceneId:string;selections:DinnerSelection;onChange:(next:DinnerSelection)=>void}){const scene=dinnerSceneById[sceneId];if(!scene)return null;return <section className="dd-stage"><span>STAGE 3</span><h3>{scene.name}專屬食物卡</h3><p>{scene.selectionStructure}｜{scene.description}</p>{scene.foodGroups.map(group=><FoodGroup key={group.id} group={group} selections={selections} onChange={onChange}/>)}</section>}

export function DinnerDefenseScore({score,structure,fit}:{score:number;structure:number;fit:number}){return <section className="dd-score"><div><small>你的晚餐防線</small><strong>{score}<i>/100</i></strong></div><div><span>餐點結構 <b>{structure}/60</b></span><span>個人適配 <b>{fit}/40</b></span></div></section>}

export function MinimalUpgradeCard({upgrade,before,after,onApply}:{upgrade:ReturnType<typeof generateDinnerAnalysis>["minimalUpgrade"];before:number;after:number;onApply:()=>void}){if(!upgrade)return <aside className="dd-upgrade complete"><b>目前不需要硬湊四格</b><p>這份組合和你現在的狀態已相對適配，可以直接保存。</p></aside>;return <aside className="dd-upgrade"><span>最小升級</span><h4>{upgrade.label}</h4><p>{upgrade.reason}</p><strong>{before} → {after}</strong><button type="button" onClick={onApply}>＋ {upgrade.label}</button></aside>}

export function DinnerAnalysisPanel({analysis,onApply}:{analysis:ReturnType<typeof generateDinnerAnalysis>;onApply:()=>void}){return <section className="dd-stage"><span>STAGE 4–5</span><h3>即時防線分析</h3><DinnerDefenseScore score={analysis.totalScore} structure={analysis.structureScore} fit={analysis.personalFitScore}/><div className="dd-analysis-grid"><article><h4>做得好的地方</h4>{analysis.strengths.length?analysis.strengths.map(x=><p key={x}>✓ {x}</p>):<p>餐點仍在組合中，先完成一個主要選擇。</p>}</article><article><h4>目前最大的漏洞</h4>{analysis.vulnerabilities.length?analysis.vulnerabilities.map(x=><p key={x}>• {x}</p>):<p>目前沒有明顯的大漏洞。</p>}</article><article><h4>和前五關的連動</h4>{analysis.crossLevelInsights.length?analysis.crossLevelInsights.map(x=><p key={x}>• {x}</p>):<p>目前線索還不夠完整，系統會先依這餐本身分析。</p>}</article></div><aside className="branch-influence"><span>支線適配 {analysis.branchFit.score}/10</span><p>{analysis.branchFit.insight}</p></aside><p className="dd-summary">{analysis.analysisSummary}</p><MinimalUpgradeCard upgrade={analysis.minimalUpgrade} before={analysis.totalScore} after={analysis.upgradedScore} onApply={onApply}/></section>}

export function SaveDinnerBackupModal({open,defaultName,onCancel,onSave}:{open:boolean;defaultName:string;onCancel:()=>void;onSave:(name:string,scenario:string)=>void}){const [name,setName]=useState(defaultName),[scenario,setScenario]=useState("tired");if(!open)return null;return <div className="dd-modal" role="dialog" aria-modal="true"><section><h3>收藏這座晚餐防線</h3><label>備案名稱<input value={name} onChange={e=>setName(e.target.value)} placeholder="例如：加班超商版"/></label><div className="dd-scenario-picks">{[["tired","很累時"],["hungry","很餓時"],["rush","趕時間時"],["convenience","只能吃超商時"],["overtime","加班時"],["custom","自訂"]].map(([id,label])=><button type="button" className={scenario===id?"selected":""} key={id} onClick={()=>setScenario(id)}>{label}</button>)}</div><div><button type="button" onClick={onCancel}>取消</button><button type="button" disabled={!name.trim()} onClick={()=>onSave(name.trim(),scenario)}>確認收藏</button></div></section></div>}

export function CloneDinnerBackup({backup,onClone}:{backup:DinnerBackup;onClone:(backup:DinnerBackup)=>void}){return <button type="button" onClick={()=>onClone({...backup,id:crypto.randomUUID(),name:`${backup.name}（複製）`,scenarioType:"custom",createdAt:new Date().toISOString()})}>複製這組</button>}

export function GeneratedBackupVariations({items,onUse}:{items:DinnerBackup[];onUse:(backup:DinnerBackup)=>void}){if(!items.length)return null;return <section className="dd-variations"><h3>系統幫我生成相似備案</h3><div>{items.map(item=><article key={item.id}><span>{item.name}</span><b>{item.score} 分</b><p>{Object.values(item.selections).flatMap(asList).join("＋")}</p><button type="button" onClick={()=>onUse(item)}>確認收藏</button></article>)}</div></section>}

export function DinnerDefenseSummary({backups}:{backups:DinnerBackup[];onRemove?:()=>void;onClone?:()=>void}){return <section className="dd-stage dd-backups"><span>STAGE 6–8</span><h3>我的三座晚餐防線</h3>{backups.length>0&&backups.length<3&&<p className="dd-ready">✓ 已建立第 {backups.length} 組。請回到上方選擇場景，繼續建立第 {backups.length+1} 組。</p>}{backups.length?<div>{backups.map(item=><article key={item.id}><small>{dinnerSceneById[item.dinnerScene]?.name||item.dinnerScene}</small><h4>{item.name}</h4><b>{item.score} 分</b><p>{Object.values(item.selections).flatMap(asList).join("＋")}</p></article>)}</div>:<p>先完成一份晚餐組合，按下「建立第一組晚餐防線」。</p>}<p className={backups.length>=3&&new Set(backups.map(x=>x.scenarioType)).size>=2?"dd-ready":"dd-rule"}>{backups.length>=3&&new Set(backups.map(x=>x.scenarioType)).size>=2?"✓ 三座晚餐防線已完成，可以解鎖徽章。":"過關條件：3 組有名稱、經過分析的備案，且至少 2 種不同情境。"}</p></section>}

export default function DinnerDefenseBuilder({values,setInput,state}:{values:any;setInput:(key:string,value:unknown)=>void;state:any}){
 const previousResults=useMemo(()=>Object.fromEntries((state.entries||[]).filter((x:any)=>x.levelNumber<=5).map((x:any)=>[x.levelNumber,x.analysisResult||{}])),[state.entries]);
 const profile=useMemo(()=>buildDinnerPriorityProfile(previousResults,{hungerScore:values.currentHungerScore}),[previousResults,values.currentHungerScore]);
 const sceneId=values.dinnerSceneId||"",selections: DinnerSelection=values.selections||{},backups:DinnerBackup[]=Array.isArray(values.savedDinnerBackups)?values.savedDinnerBackups.filter((x:any)=>x&&typeof x==="object"):[];
 const analysis=useMemo(()=>generateDinnerAnalysis(sceneId,selections,profile),[sceneId,selections,profile]);
 const [saveOpen,setSaveOpen]=useState(false);
 const sceneTopRef=useRef<HTMLDivElement>(null);
 const updateSelections=(next:DinnerSelection)=>{setInput("selections",next);setInput("analysisResult",generateDinnerAnalysis(sceneId,next,profile))};
 const applyUpgrade=()=>{const u=analysis.minimalUpgrade;if(!u)return;const group=dinnerSceneById[sceneId].foodGroups.find(x=>x.id===u.groupId),old=asList(selections[u.groupId]);updateSelections({...selections,[u.groupId]:group?.multiple?[...new Set([...old,u.option])]:u.option})};
 const addBackup=(backup:DinnerBackup)=>setInput("savedDinnerBackups",[...backups.filter(x=>x.id!==backup.id),backup].slice(0,3));
 const save=(name:string,scenarioType:string)=>{addBackup({id:crypto.randomUUID(),name,scenarioType,dinnerScene:sceneId,selections,analysisResult:analysis,score:analysis.totalScore,createdAt:new Date().toISOString()});setSaveOpen(false);setInput("dinnerSceneId","");setInput("selections",{});requestAnimationFrame(()=>sceneTopRef.current?.scrollIntoView({behavior:"smooth",block:"start"}))};
 return <div className="dinner-defense-builder"><BranchInfluenceCard branch={profile.selectedBranch} title="第 4 關路線正在影響今晚分析"/><div ref={sceneTopRef}><DinnerSceneSelector value={sceneId} onChange={id=>{setInput("dinnerSceneId",id);setInput("selections",{})}}/></div><section className="dd-priority"><span>STAGE 2｜讀取前五關線索</span><h3>今晚請特別注意</h3><div>{profile.warningTags.length?profile.warningTags.map(x=><b key={x}>{x}</b>):<b>目前前五關線索較少，先依今晚狀態建造</b>}</div><p>今晚防線優先目標：<strong>{labelMap[profile.primaryPriority]}＋{labelMap[profile.secondaryPriority]}</strong></p><label>我現在的飢餓程度 <strong>{profile.hungerScore}/10</strong><input type="range" min="0" max="10" value={profile.hungerScore} onChange={e=>setInput("currentHungerScore",Number(e.target.value))}/></label></section>{sceneId&&<><SceneSpecificFoodBuilder sceneId={sceneId} selections={selections} onChange={updateSelections}/><DinnerAnalysisPanel analysis={analysis} onApply={applyUpgrade}/></>}<div className="dd-actions"><button type="button" disabled={!sceneId||analysis.totalScore===0||backups.length>=3} onClick={()=>setSaveOpen(true)}>{backups.length>=3?"三組晚餐防線已建立":`建立第${["一","二","三"][backups.length]}組晚餐防線`}</button></div><DinnerDefenseSummary backups={backups} onRemove={()=>{}} onClone={()=>{}}/><SaveDinnerBackupModal open={saveOpen} defaultName={`${dinnerSceneById[sceneId]?.name||"晚餐"}備案`} onCancel={()=>setSaveOpen(false)} onSave={save}/></div>
}
