"use client";
import Link from "next/link";
import {useParams} from "next/navigation";
import {useState} from "react";
import {branchRoutes} from "@/content/branchRoutes";
import {clueUsage,previousCluesForLevel,type JourneyContext} from "@/lib/journey-context";
export function PreviousClueCard({label,value}:{label:string;value:string}){return <article className="journey-clue-card"><small>{label}</small><b>{value}</b></article>}
export function JourneyConnectionPanel({level,journey}:{level:number;journey:JourneyContext}){const clues=previousCluesForLevel(level,journey),params=useParams<{accessToken:string}>(),token=String(params?.accessToken||""),[resetting,setResetting]=useState(false),previousHref=level===1?`/access/${token}/character-creation`:`/access/${token}/breakthrough-plan/level/${level-1}`;async function reset(){if(!confirm(`確定要重新填寫第 ${level} 關嗎？本關與後續關卡的進度會重置，前面線索會保留。`))return;setResetting(true);const response=await fetch(`/api/breakthrough/${token}/reset`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({fromLevel:level})});if(response.ok)location.href=`/access/${token}/breakthrough-plan/level/${level}`;else{alert("目前無法重置關卡，請稍後再試。");setResetting(false)}}return <section className="journey-connection"><nav className="journey-level-tools"><Link href={previousHref}>← {level===1?"回到第 0 天":"回到上一關"}</Link><button type="button" disabled={resetting} onClick={reset}>{resetting?"正在重置…":"重新填寫本關"}</button></nav><span>來自前面關卡的線索</span><h2>{level===1?"角色已建立，第一段迷霧即將展開":"系統記得你前面留下的答案"}</h2><div>{clues.length?clues.map(x=><PreviousClueCard key={`${x.label}-${x.value}`} {...x}/>):<p>目前線索還不多；完成本關後，後面的推薦會開始變得更個人化。</p>}</div><p>今天的任務會把這些線索帶進新的分析，不會從零開始。</p></section>}
export function ThisClueWillBeUsedFor({level}:{level:number}){return <section className="journey-usage"><span>這條線索接下來會用在哪裡？</span><div>{(clueUsage[level]||[]).map(x=><b key={x}>→ {x}</b>)}</div></section>}
export function NextLevelPreview({currentLevel}:{currentLevel:number}){const names=["","時間迷霧","場景迷宮","情緒之門","支線岔路","補給裂縫","晚餐防線","迷霧核心"];return currentLevel<7?<p className="journey-next-preview"><b>下一關預告：</b>第 {currentLevel+1} 關｜{names[currentLevel+1]}</p>:<p className="journey-next-preview"><b>下一步：</b>查看我的個人止損地圖</p>}
export function LevelCompletionActions({currentLevel,menuHref,nextHref,isFinalLevel=false}:{currentLevel:number;nextLevel?:number;nextLevelName?:string;menuHref:string;nextHref:string;isFinalLevel?:boolean}){const names=["","時間迷霧","場景迷宮","情緒之門","支線岔路","補給裂縫","晚餐防線","迷霧核心"],label=currentLevel===0?"進入第 1 關｜時間迷霧":isFinalLevel?"查看我的止損地圖":`進入第 ${currentLevel+1} 關｜${names[currentLevel+1]}`;return <nav className="level-completion-actions"><Link className="primary" href={nextHref}>{label} →</Link><Link href={menuHref}>回到主選單</Link></nav>}
export function BranchInfluenceCard({branch,title="支線加成"}:{branch:string|null|undefined;title?:string}){if(!branch)return null;const item=branchRoutes[branch as keyof typeof branchRoutes];if(!item)return null;return <section className="branch-influence"><span>{title}</span><h3>{item.name}</h3><p>{item.description}</p><b>專屬止損動作：{item.exclusiveAction}</b></section>}
export function BranchExtraTask({branch,value,onChange}:{branch:string|null|undefined;value:string;onChange:(value:string)=>void}){if(!branch)return null;const config={drink_loop:{question:"今天有沒有用飲料代替真正的食物？",options:["沒有","有一次","有兩次以上"]},energy_refill:{question:"今天哪一餐最容易吃不夠？",options:["早餐","午餐","下午","晚餐"]},stress_rescue:{question:"今天哪一次想吃，其實更像是情緒？",options:["壓力","委屈","無聊","犒賞","沒有"]},habit_break:{question:"今天最容易自動啟動嘴饞的場景？",options:["沙發","辦公桌","超商","外送 App","追劇","其他"]}}[branch as keyof typeof branchRoutes];if(!config)return null;return <section className="branch-extra-task"><span>第 5 關支線任務</span><h3>{branchRoutes[branch as keyof typeof branchRoutes].name}加成</h3><label>{config.question}<select value={value} onChange={e=>onChange(e.target.value)}><option value="">請選擇</option>{config.options.map(x=><option key={x}>{x}</option>)}</select></label></section>}
export function JourneySummaryCard({journey}:{journey:JourneyContext}){return <section className="journey-summary"><span>目前冒險情報</span><h2>{journey.character?.name||"角色尚未建立"}</h2><div><article><small>主要攻略路線</small><b>{journey.selectedBranch?branchRoutes[journey.selectedBranch].name:"尚待第 4 關判定"}</b></article><article><small>次要線索</small><b>{journey.secondaryBranch?branchRoutes[journey.secondaryBranch].name:"持續收集中"}</b></article><article><small>最新收集線索</small>{journey.latestClues.slice(-3).map(x=><p key={x}>{x}</p>)}</article></div></section>}
export function AdventureLog({journey}:{journey:JourneyContext}){const rows=[[0,"角色創建完成"],[1,"找到時間線索"],[2,"找到場景線索"],[3,"完成身心解碼"],[4,"選定攻略支線"],[5,"找到營養缺口"],[6,"建立晚餐防線"],[7,"完成止損地圖"]] as const;return <section className="adventure-log"><span>ADVENTURE LOG</span><h2>冒險紀錄</h2><div>{rows.map(([level,label])=>{const done=level===0?Boolean(journey.character):journey.completedLevels.includes(level);return <article className={done?"done":"locked"} key={level}><b>{level===0?"第 0 天":`第 ${level} 關`}</b><p>{label}</p><span>{done?"✓ 已完成":"🔒 未完成"}</span></article>})}</div></section>}
