"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { buildTriggerSummary,emptyTriggerEntry,triggerAnalysisContent as c,type TriggerEntry,type TriggerSummary } from "@/content/cravingTriggerAnalysis";
import { TriggerEntryForm } from "./TriggerEntryForm";
import { TriggerEntryCard } from "./TriggerEntryCard";
import { TriggerSummaryCard } from "./TriggerSummaryCard";
import { SuggestedNextStepCard } from "./SuggestedNextStepCard";

export function TriggerAnalysisHome({accessToken}:{accessToken:string}){const [entries,setEntries]=useState<TriggerEntry[]>([]),[summary,setSummary]=useState<TriggerSummary>(()=>buildTriggerSummary([])),[editing,setEditing]=useState<TriggerEntry|null|"new">(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("");async function load(){try{const response=await fetch(`/api/trigger-analysis/${accessToken}`),body=await response.json();if(!response.ok)throw new Error();setEntries(body.entries.map(normalize));setSummary(body.summary)}catch{setError(c.errors.load)}finally{setLoading(false)}}useEffect(()=>{load()},[accessToken]);function normalize(entry:TriggerEntry){return {...entry,occurredAt:entry.occurredAt??entry.createdAt,afterFeeling:Array.isArray(entry.afterFeeling)?entry.afterFeeling:[],triggerTypes:Array.isArray(entry.triggerTypes)?entry.triggerTypes:[]}}async function save(entry:TriggerEntry){const updating=Boolean(entry.id),url=updating?`/api/trigger-analysis/${accessToken}/${entry.id}`:`/api/trigger-analysis/${accessToken}`;try{const response=await fetch(url,{method:updating?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(entry)});if(!response.ok)throw new Error();await load();setEditing(null);setNotice(c.saved);setTimeout(()=>setNotice(""),4000)}catch{setError(c.errors.save)}}async function remove(entry:TriggerEntry){if(!entry.id||!confirm(c.deleteConfirm))return;try{const response=await fetch(`/api/trigger-analysis/${accessToken}/${entry.id}`,{method:"DELETE"});if(!response.ok)throw new Error();await load()}catch{setError(c.errors.remove)}}if(loading)return <main className="ta-shell"><div className="ta-loading">正在整理你的觸發點…</div></main>;if(editing)return <main className="ta-shell"><TriggerEntryForm initial={editing==="new"?{...emptyTriggerEntry,occurredAt:new Date().toISOString().slice(0,16)}:editing} onSave={save} onCancel={()=>setEditing(null)}/></main>;return <main className="ta-shell"><header className="ta-header"><Link href={`/access/${accessToken}`}>← 回到工具包</Link><span>可樂吉健康研究所</span></header><div className="ta-home"><section className="ta-hero"><span className="ta-kicker">CRAVING PATTERN FINDER</span><h1>{c.title}</h1><p>{c.intro}</p><small>{c.positioning}</small><button className="btn" type="button" onClick={()=>setEditing("new")}><span>{c.newEntry}</span><span>＋</span></button></section>{notice&&<div className="ta-notice">✓ {notice}</div>}{error&&<div className="ta-error">{error}</div>}<section className="ta-list"><div className="ta-section-title"><span>YOUR LOGS</span><h2>{c.list.title}</h2></div>{entries.length?<div className="ta-entry-grid">{entries.map(entry=><TriggerEntryCard key={entry.id} entry={entry} onEdit={()=>setEditing(entry)} onDelete={()=>remove(entry)}/>)}</div>:<p className="ta-empty">{c.empty}</p>}</section><TriggerSummaryCard summary={summary}/><SuggestedNextStepCard accessToken={accessToken} summary={summary}/></div></main>}
