"use client";
import { threeMinuteCheckContent as c,type ThreeMinuteData } from "@/content/threeMinuteCheck";
import { LargeCheckboxGroup,LargeRadioGroup,SliderField } from "./ThreeMinuteFields";

type Props={data:ThreeMinuteData;update:<K extends keyof ThreeMinuteData>(key:K,value:ThreeMinuteData[K])=>void};
export function ThreeMinuteStartStep({onStart,busy}:{onStart:()=>void;busy:boolean}){return <section className="tm-start"><div className="tm-clock"><strong>3</strong><span>MIN</span></div><span className="tm-kicker">S · E · C CHECK-IN</span><h1>{c.start.title}</h1><p>{c.start.text}</p><div className="tm-sec">{c.sec.map(item=><article key={item.key}><b>{item.key}</b><div><strong>{item.title}</strong><p>{item.text}</p></div></article>)}</div><button className="btn" type="button" onClick={onStart} disabled={busy}><span>{busy?"正在準備…":c.start.button}</span><span>→</span></button></section>}

export function ThreeMinuteContextStep({data,update}:Props){return <section className="tm-step-card"><span className="tm-kicker">先記下此刻</span><h1>{c.context.title}</h1><label className="tm-text-field">{c.context.cravingItem}<input value={data.cravingItem??""} onChange={e=>update("cravingItem",e.target.value)} placeholder={c.context.cravingPlaceholder}/></label><label className="tm-text-field">{c.context.location}<input value={data.location??""} onChange={e=>update("location",e.target.value)} placeholder={c.context.locationPlaceholder}/></label><label className="tm-text-field">{c.context.beforeActivity}<textarea rows={4} value={data.beforeActivity??""} onChange={e=>update("beforeActivity",e.target.value)} placeholder={c.context.activityPlaceholder}/></label></section>}

export function ThreeMinuteBodyScanStep({data,update}:Props){return <section className="tm-step-card"><span className="tm-kicker">STOP · 01:00</span><h1>{c.body.title}</h1><p>{c.body.description}</p><LargeCheckboxGroup options={c.body.signals} value={data.bodySignals} onChange={value=>update("bodySignals",value)}/><div className="tm-sliders"><SliderField label={c.body.hunger} value={data.hungerScore} onChange={value=>update("hungerScore",value)}/><SliderField label={c.body.mouth} value={data.mouthCravingScore} onChange={value=>update("mouthCravingScore",value)}/><SliderField label={c.body.fatigue} value={data.fatigueScore} onChange={value=>update("fatigueScore",value)}/></div></section>}

export function ThreeMinuteEmotionStep({data,update}:Props){return <section className="tm-step-card"><span className="tm-kicker">EXAMINE · 02:00</span><h1>{c.emotion.title}</h1><div className="tm-sliders"><SliderField label={c.emotion.stress} value={data.stressScore} onChange={value=>update("stressScore",value)}/><SliderField label={c.emotion.comfort} value={data.comfortNeedScore} onChange={value=>update("comfortNeedScore",value)}/><SliderField label={c.emotion.sugaryDrink} value={data.sugaryDrinkScore} onChange={value=>update("sugaryDrinkScore",value)}/></div><h2>此刻最接近哪些感受？</h2><LargeCheckboxGroup options={c.emotion.tags} value={data.emotionTags} onChange={value=>update("emotionTags",value)}/><h2>{c.emotion.needLabel}</h2><LargeRadioGroup options={c.emotion.needTypes} value={data.needType} onChange={value=>update("needType",value)}/></section>}

export function ThreeMinuteChooseStep({data,update}:Props){return <section className="tm-step-card"><span className="tm-kicker">CHOOSE · 03:00</span><h1>{c.choose.title}</h1><h2>{c.choose.actionLabel}</h2><LargeRadioGroup options={c.choose.actions} value={data.chosenAction} onChange={value=>update("chosenAction",value)}/><h2>{c.choose.changeLabel}</h2><LargeRadioGroup options={c.choose.changes} value={data.cravingChange} onChange={value=>update("cravingChange",value)}/><label className="tm-text-field">{c.choose.finalChoice}<textarea rows={3} value={data.finalChoice??""} onChange={e=>update("finalChoice",e.target.value)}/></label><label className="tm-text-field">{c.choose.selfReminder}<textarea rows={3} value={data.selfReminder??""} onChange={e=>update("selfReminder",e.target.value)}/></label></section>}
