"use client";
import Link from "next/link";
import { useEffect,useRef,useState } from "react";
import { buildDrinkResetReport,drinkResetContent,type DrinkDayState,type DrinkField } from "@/content/drinkReset";

type SaveState="idle"|"saving"|"saved"|"error";
function Field({field,value,onChange}:{field:DrinkField;value:unknown;onChange:(value:unknown)=>void}){
  if(field.type==="slider"){const current=typeof value==="number"?value:5;return <label className="drink-field"><span className="drink-slider-label">{field.label}<b>{current} / 10</b></span><input className="drink-slider" type="range" min="0" max="10" value={current} onChange={e=>onChange(Number(e.target.value))}/></label>}
  if(field.type==="radio"||field.type==="checkbox"){const selected=Array.isArray(value)?value as string[]:[];return <fieldset className="drink-field"><legend>{field.label}</legend><div className="drink-options">{field.options?.map(option=>{const checked=field.type==="radio"?value===option:selected.includes(option);return <label className={checked?"selected":""} key={option}><input type={field.type} checked={checked} onChange={e=>onChange(field.type==="radio"?option:e.target.checked?[...selected,option]:selected.filter(x=>x!==option))}/><span>{option}</span></label>})}</div></fieldset>}
  if(field.type==="textArray"){const values=Array.isArray(value)?value as string[]:[];return <div className="drink-field"><span>{field.label}</span>{[0,1,2].map(i=><input key={i} value={values[i]??""} placeholder={`第 ${i+1} 名`} onChange={e=>{const next=[...values];next[i]=e.target.value;onChange(next)}}/>)}</div>}
  const current=typeof value==="string"?value:"";
  return <label className="drink-field"><span>{field.label}</span>{field.type==="textarea"?<textarea rows={4} value={current} placeholder={field.placeholder} onChange={e=>onChange(e.target.value)}/>:<input value={current} placeholder={field.placeholder} onChange={e=>onChange(e.target.value)}/>}</label>;
}
function Report({days}:{days:Record<number,DrinkDayState>}){const report=buildDrinkResetReport(days),copy=drinkResetContent.report;return <section className="drink-report"><span className="drink-kicker">YOUR 7-DAY REPORT</span><h2>{copy.title}</h2><p className="drink-disclaimer">{drinkResetContent.disclaimer}</p><div className="drink-report-grid"><article><small>{copy.recordedDays}</small><strong>{report.recordedDays} / 7 天</strong></article><article><small>{copy.sugar}</small><strong>{report.sugar}</strong></article><article><small>{copy.topping}</small><strong>{report.topping}</strong></article><article><small>{copy.trigger}</small><strong>{report.trigger}</strong></article><article><small>{copy.emotion}</small><strong>{report.emotion}</strong></article><article><small>{copy.highRiskTime}</small><strong>{report.highRisk?"有相關紀錄":"目前不明顯"}</strong></article><article><small>{copy.waterWorked}</small><strong>{report.waterWorked?"有下降紀錄":"尚未觀察到"}</strong></article></div><div className="drink-pattern"><small>{copy.patterns}</small><div>{report.patterns.length?report.patterns.map(x=><b key={x}>{x}</b>):<b>持續記錄，就能看見更清楚的模式</b>}</div></div><div className="drink-report-cta"><h3>{copy.ctaTitle}</h3><p>{copy.ctaText}</p><a href="https://gomypay-emotional-eating-funnel.vercel.app/ai-energy-assessment">{copy.cta} →</a></div></section>}

export default function DrinkResetClient({accessToken}:{accessToken:string}){
  const [days,setDays]=useState<Record<number,DrinkDayState>>({}),[selected,setSelected]=useState<number|null>(null),[loading,setLoading]=useState(true),[save,setSave]=useState<Record<number,SaveState>>({});
  const timers=useRef<Record<number,ReturnType<typeof setTimeout>>>({});
  useEffect(()=>{fetch(`/api/drink-reset/${accessToken}`).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(result=>{const mapped:Record<number,DrinkDayState>={};result.days.forEach((x:DrinkDayState&{dayNumber:number})=>mapped[x.dayNumber]={data:x.data,isCompleted:x.isCompleted,completedAt:x.completedAt});setDays(mapped)}).finally(()=>setLoading(false))},[accessToken]);
  const completed=Object.values(days).filter(x=>x.isCompleted).length;
  async function saveDay(day:number,data:Record<string,unknown>){setSave(s=>({...s,[day]:"saving"}));try{const r=await fetch(`/api/drink-reset/${accessToken}/day/${day}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({data})});if(!r.ok)throw new Error();setSave(s=>({...s,[day]:"saved"}))}catch{setSave(s=>({...s,[day]:"error"}))}}
  function update(day:number,key:string,value:unknown){const data={...(days[day]?.data??{}),[key]:value};setDays(current=>({...current,[day]:{data,isCompleted:current[day]?.isCompleted??false,completedAt:current[day]?.completedAt??null}}));setSave(s=>({...s,[day]:"saving"}));clearTimeout(timers.current[day]);timers.current[day]=setTimeout(()=>saveDay(day,data),500)}
  async function complete(day:number){clearTimeout(timers.current[day]);const data=days[day]?.data??{};setSave(s=>({...s,[day]:"saving"}));try{const r=await fetch(`/api/drink-reset/${accessToken}/day/${day}/complete`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({data})});if(!r.ok)throw new Error();const result=await r.json();setDays(current=>({...current,[day]:{data,isCompleted:true,completedAt:result.completedAt}}));setSave(s=>({...s,[day]:"saved"}));setSelected(day<7?day+1:null)}catch{setSave(s=>({...s,[day]:"error"}))}}
  if(loading)return <main className="drink-loading">正在準備你的飲料重置表…</main>;
  const day=selected?drinkResetContent.days[selected-1]:null,state=selected?save[selected]??"idle":"idle";
  return <div className="drink-app"><header className="drink-header"><div><Link href={`/access/${accessToken}`}>← 回到工具包</Link><span>{completed} / 7 天完成</span></div><div><i style={{width:`${completed/7*100}%`}}/></div></header>{!day?<main className="drink-overview"><section className="drink-hero"><span className="drink-kicker">SUGAR DRINK RESET</span><h1>{drinkResetContent.title}</h1><p>{drinkResetContent.subtitle}</p><div>{drinkResetContent.overview}</div></section><section className="drink-day-grid">{drinkResetContent.days.map(item=><button key={item.day} className={days[item.day]?.isCompleted?"completed":""} onClick={()=>setSelected(item.day)}><span>DAY {item.day}</span><strong>{item.title}</strong><small>{days[item.day]?.isCompleted?"✓ 已完成":"開始填寫 →"}</small></button>)}</section>{days[7]?.isCompleted&&<Report days={days}/>}</main>:<main className="drink-day"><button className="drink-back" onClick={()=>setSelected(null)}>← {drinkResetContent.back}</button><section className="drink-day-title"><span>DAY {day.day}</span><h1>{day.title}</h1><p>{day.intro}</p><small className={state}>{state==="saving"?drinkResetContent.saving:state==="saved"?drinkResetContent.saved:state==="error"?drinkResetContent.saveError:"填寫後會自動儲存"}</small></section><section className="drink-form">{day.fields.map(field=><Field key={field.key} field={field} value={days[day.day]?.data[field.key]} onChange={value=>update(day.day,field.key,value)}/>)}</section><nav className="drink-actions"><button disabled={day.day===1} onClick={()=>setSelected(day.day-1)}>← {drinkResetContent.previous}</button><button onClick={()=>saveDay(day.day,days[day.day]?.data??{})}>儲存今天</button><button className="primary" onClick={()=>complete(day.day)}>{days[day.day]?.isCompleted?"✓ 已完成":drinkResetContent.complete}</button><button disabled={day.day===7} onClick={()=>setSelected(day.day+1)}>{drinkResetContent.next} →</button></nav></main>}</div>;
}
