import { Prisma } from "@prisma/client";
import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/db";
import { authorizeWorkbook } from "@/lib/workbook";
import { rateLimit,requestIp } from "@/lib/rate-limit";
import { buildSwapSummary,getSwapRecommendations,safeSwapContent } from "@/content/safeSwap";
const body=z.object({cravingCategory:z.string().refine(x=>x in safeSwapContent.categories),originalChoice:z.string().trim().min(1).max(100),cravingIntensity:z.number().int().min(0).max(10)});
const selection={id:true,cravingCategory:true,originalChoice:true,cravingIntensity:true,recommendedOptions:true,createdAt:true} as const;
export async function GET(req:Request,{params}:{params:Promise<{accessToken:string}>}){const {accessToken}=await params;if(!await rateLimit(`swap-read:${requestIp(req)}`,60,60_000))return NextResponse.json({error:"請稍後再試"},{status:429});if(!await authorizeWorkbook(accessToken))return NextResponse.json({error:"無法開啟安全替換清單"},{status:404});const [records,favorites]=await Promise.all([prisma.safeSwapRecord.findMany({where:{accessToken},orderBy:{createdAt:"desc"},take:30,select:selection}),prisma.safeSwapFavorite.findMany({where:{accessToken},orderBy:{createdAt:"desc"},take:30,select:{id:true,favoriteCategory:true,title:true,content:true,createdAt:true}})]);return NextResponse.json({records:records.slice(0,7),favorites,summary:buildSwapSummary(records)});}
export async function POST(req:Request,{params}:{params:Promise<{accessToken:string}>}){const {accessToken}=await params;if(!await rateLimit(`swap-write:${requestIp(req)}`,60,60_000))return NextResponse.json({error:"操作太頻繁，請稍候"},{status:429});if(!await authorizeWorkbook(accessToken))return NextResponse.json({error:"無法儲存替換紀錄"},{status:404});const parsed=body.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"請完成需求、原本選項與嘴饞強度"},{status:400});if(!safeSwapContent.choices[parsed.data.cravingCategory]?.includes(parsed.data.originalChoice))return NextResponse.json({error:"替換選項不正確"},{status:400});const recommendedOptions=getSwapRecommendations(parsed.data.cravingCategory,parsed.data.originalChoice);const record=await prisma.safeSwapRecord.create({data:{...parsed.data,accessToken,recommendedOptions:recommendedOptions as unknown as Prisma.InputJsonValue},select:selection});return NextResponse.json({record,recommendedOptions},{status:201});}
