import { salesPage as c } from "@/content/emotionalEatingSalesPage";
import { PrimaryCTA, ProductBundleMockup, QuizPreview, SectionHeading, StickyCheckoutBar, TrustPill, WorkbookPreview } from "@/components/ui/BrandUI";
import SalesLeadForm from "@/app/sales/emotional-eating/SalesLeadForm";

const painIcons=["月","夜","壓","飲","餓","撐"];
const bonusIcons=["測","心","析","飲","記","救","餐","換"];

export function HeroSection(){return <section className="hero-section"><div className="hero-orb"/><div className="container hero-grid"><div className="hero-copy"><div className="hero-badges"><TrustPill>數位工具包</TrustPill><TrustPill>適合外食族</TrustPill><TrustPill>手機可用</TrustPill></div><p className="hero-eyebrow">{c.hero.eyebrow}</p><h1>{c.hero.title}</h1><p className="hero-subtitle">{c.hero.subtitle}</p><div className="hero-offer"><div><span>原價 <s>{c.hero.originalPrice}</s></span><strong><small>今日體驗價</small>{c.hero.price}</strong></div><PrimaryCTA>{c.hero.cta}</PrimaryCTA></div><p className="microcopy">數位產品，非實體寄送 · 購買後立即取得</p></div><ProductBundleMockup/></div><div className="container trust-strip">{c.hero.trust.map(x=><div key={x}><span>✓</span>{x}</div>)}<div><span>♡</span>溫和調整，不靠極端節食</div></div></section>}

export function PainPointsSection(){return <section className="section pain-section"><div className="container"><SectionHeading eyebrow="下班後的熟悉循環" title={c.pain.title} description={c.pain.paragraphs.slice(0,2).join(" ")}/><div className="pain-grid">{c.pain.bullets.map((x,i)=><article className="pain-card" key={x}><span>{painIcons[i]}</span><p>{x}</p></article>)}</div><div className="story-callout"><span>「</span><div>{c.pain.paragraphs.slice(2).map(p=><p key={p}>{p}</p>)}</div></div></div></section>}

export function BeliefShiftSection(){const reasons=["壓力太大，想用食物放鬆","太累，沒有力氣做選擇","白天吃太少，晚上身體開始討食物","每天靠含糖飲料撐過下午"] ;return <section className="section belief-section"><div className="container split-layout"><div><SectionHeading align="left" eyebrow="先別急著責備自己" title={c.shift.title}/><div className="belief-copy">{c.shift.paragraphs.slice(0,2).map(p=><p key={p}>{p}</p>)}</div><div className="soft-note">{c.shift.paragraphs.slice(3).map(p=><p key={p}>{p}</p>)}</div></div><div className="reason-stack"><span className="stack-label">其實更可能是…</span>{reasons.map((x,i)=><article key={x}><b>0{i+1}</b><p>{x}</p></article>)}</div></div></section>}

export function ProductBundleSection(){return <section className="section product-section"><div className="container product-grid"><div className="product-visual"><ProductBundleMockup/></div><div><SectionHeading align="left" eyebrow="不是另一份不能吃的規則" title={c.product.title} description={c.product.subtitle}/><div className="product-copy">{c.product.paragraphs.map(p=><p key={p}>{p}</p>)}</div><PrimaryCTA>{c.product.cta}</PrimaryCTA></div></div></section>}

export function AudienceSection(){return <section className="section audience-section"><div className="container audience-grid"><article className="audience-card good"><span className="card-kicker">適合從小地方開始的你</span><h2>{c.audience.suitableTitle}</h2><ul>{c.suitable.map(x=><li key={x}><span>✓</span>{x}</li>)}</ul></article><article className="audience-card notice"><span className="card-kicker">一個溫柔但重要的提醒</span><h2>{c.audience.unsuitableTitle}</h2>{c.unsuitable.map(p=><p key={p}>{p}</p>)}</article></div></section>}

export function TimelineSection(){return <section className="section timeline-section"><div className="container"><SectionHeading eyebrow={c.mainProduct.eyebrow} title={c.mainProduct.title} description="每天 5–10 分鐘，從看懂模式，到建立自己的止損流程。"/><div className="timeline">{c.days.map((x,i)=>{const [day,title]=x.split("：");return <article key={x}><div className="day-dot">{i+1}</div><span>{day}</span><h3>{title}</h3><p>{i<3?"先看見觸發點，不急著要求自己立刻改變。":i<6?"把看見的模式，轉成生活中可執行的小步驟。":"整理成一套屬於你的日常止損計畫。"}</p></article>})}</div></div></section>}

export function ProductPreviewSection(){return <section className="section preview-section"><div className="container"><SectionHeading eyebrow="不是空泛知識，而是可以真的動手寫" title="先看看你的工具包會長什麼樣子" description="以下為內容版型示意，正式連結可在完成 PDF、Notion 或測驗表單後直接替換。"/><div className="preview-grid"><WorkbookPreview/><QuizPreview/></div></div></section>}

export function BonusGridSection(){return <section className="section bonus-section"><div className="container"><SectionHeading eyebrow="完整工具組合" title={c.bonusTitle} description="不是一份薄薄的電子檔，而是一套能陪你看見、記錄、調整的行動工具。"/><div className="bonus-grid">{c.bonuses.map((b,i)=><article className="bonus-card" key={b[0]}><div className="bonus-top"><span className="bonus-icon">{bonusIcons[i]}</span><small>BONUS {String(i+1).padStart(2,"0")}</small></div><h3>{b[0]}</h3><p>{b[1]}</p><span className="included-label">工具包內含</span></article>)}</div><div className="value-stack"><div><span>主計畫＋8 份實用工具</span><strong>完整數位工具包</strong></div><div><s>{c.offer.originalPrice}</s><strong>{c.offer.price}</strong></div></div></div></section>}

export function WhyItWorksSection(){return <section className="section why-section"><div className="container"><SectionHeading eyebrow="三個簡單步驟" title={c.whySection.title} description={c.whySection.intro}/><div className="why-grid">{c.why.map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0].split("：")[1]}</h3><p>{x[1]}</p></article>)}</div><p className="why-conclusion">{c.whySection.conclusion}</p></div></section>}

export function TrustFlowSection(){const steps=["購買後立即取得","先完成 6 型測驗","每天花 5–10 分鐘填寫","找出自己的嘴饞模式","再決定是否需要進一步協助"];return <section className="section trust-flow-section"><div className="container"><SectionHeading eyebrow="使用方式很簡單" title="你將如何使用這份工具包"/><div className="use-flow">{steps.map((x,i)=><article key={x}><span>{i+1}</span><p>{x}</p></article>)}</div><div className="brand-trust"><div className="brand-seal">可樂吉<br/><b>健康研究所</b></div><div><strong>{c.brand}</strong><p>一般健康教育與自我觀察工具 · 手機、電腦皆可使用 · 數位產品購買後立即取得</p></div></div></div></section>}

export function PricingSection(){return <section className="section pricing-section"><div className="container pricing-card"><div className="pricing-list"><span className="eyebrow light">今天就從一個小問題開始</span><h2>{c.offer.title}</h2><ul>{c.included.map(x=><li key={x}><span>✓</span>{x}</li>)}</ul></div><div className="pricing-action"><span className="save-tag">一次取得完整 9 項工具</span><s>{c.offer.originalPrice}</s><strong>{c.offer.price}</strong><PrimaryCTA>{c.offer.cta}</PrimaryCTA><small>GoMyPay 安全付款 · 本站不儲存信用卡資料</small></div></div></section>}

export function FAQSection(){return <section className="section faq-section"><div className="container narrow"><SectionHeading eyebrow="購買前常見問題" title={c.faqTitle}/><div className="faq-list">{c.faqs.map((x,i)=><details key={x[0]}><summary><span>{String(i+1).padStart(2,"0")}</span>{x[0]}<i>＋</i></summary><p>{x[1]}</p></details>)}</div></div></section>}

export function CheckoutLeadSection(){return <section className="section lead-section"><div className="container lead-grid"><div><SectionHeading align="left" eyebrow="準備開始了嗎？" title={c.finalCta.title} description={c.finalCta.note}/><div className="mini-trust"><span>✓ 購買後立即取得</span><span>✓ 手機與電腦皆可使用</span><span>✓ GoMyPay 安全付款</span></div></div><SalesLeadForm/></div></section>}

export function SalesFooter(){return <><footer className="sales-footer"><div className="container"><strong>{c.brand}</strong><p>{c.disclaimer}</p></div></footer><StickyCheckoutBar/></>}
