import Image from "next/image";
import { salesPage as c } from "@/content/emotionalEatingSalesPage";
import { PrimaryCTA, ProductBundleMockup, SectionHeading, StickyCheckoutBar } from "@/components/ui/BrandUI";
import { cravingCharacters } from "@/content/cravingCharacters";
import SalesHeroCheckoutGate from "./SalesHeroCheckoutGate";

const painIcons=["🧋","🛵","🍰","⏸","🧭"];

export function HeroSection(){return <section className="hero-section scroll-world-sales-hero" data-sales-hero><SalesHeroCheckoutGate/><div className="hero-orb"/><div className="hero-quest-ambient"/><div className="container hero-grid"><div className="hero-copy"><p className="hero-eyebrow">7-DAY CRAVING QUEST</p><h1>《7 天嘴饞破關計畫》</h1><p className="hero-subtitle">不用每天計算熱量，<br/>不用立刻戒掉喜歡的食物。<br/><br/>透過角色、關卡與互動工具，<br/>一步步找出你反覆嘴饞的時間、<br/>場景、情緒與飲食缺口。<br/><br/>每天完成一個任務，<br/>逐步建立屬於自己的止損路線。</p><div className="hero-reward-tag">🎁 完成第 7 關後，神秘禮物正式解鎖</div><PrimaryCTA href="#adventure-content" className="hero-soft-cta">查看 7 天冒險內容</PrimaryCTA><p className="microcopy">往下看完整冒險內容，購買資訊會在後方出現。</p></div><div className="hero-quest-visual" aria-hidden="true"><div className="quest-mirror"><span/><i/></div><div className="quest-card quest-card-a">TIME<br/>SCENE</div><div className="quest-card quest-card-b">ROLE<br/>ROUTE</div><div className="quest-card quest-card-c">FINAL<br/>MAP</div></div></div></section>}

export function PainPointsSection(){return <section className="section pain-section"><div className="container"><SectionHeading eyebrow="下班後的熟悉循環" title={c.pain.title} description={c.pain.paragraphs.slice(0,2).join(" ")}/><div className="pain-grid">{c.pain.bullets.map((x,i)=><article className="pain-card" key={x}><span>{painIcons[i]}</span><p>{x}</p></article>)}</div><div className="story-callout"><span aria-hidden="true">「</span><div>{c.pain.paragraphs.slice(2).map(p=><p key={p}>{p}</p>)}</div><span className="story-callout-close" aria-hidden="true">」</span></div></div></section>}

export function ProductBundleSection(){return <section className="section product-section"><div className="container product-grid"><div className="product-visual"><ProductBundleMockup/></div><div><SectionHeading align="left" eyebrow="不是另一份不能吃的規則" title={c.product.title} description={c.product.subtitle}/><span className="product-value">主商品 {c.product.value}</span><div className="product-copy">{c.product.paragraphs.map(p=><p key={p}>{p}</p>)}</div><PrimaryCTA>{c.product.cta}</PrimaryCTA></div></div></section>}

export function AudienceSection(){return <section className="section audience-section"><div className="container audience-grid"><article className="audience-card good"><span className="card-kicker">適合從小地方開始的你</span><h2>{c.audience.suitableTitle}</h2><ul>{c.suitable.map(x=><li key={x}><span>✓</span>{x}</li>)}</ul></article><article className="audience-card notice"><span className="card-kicker">一個溫柔但重要的提醒</span><h2>{c.audience.unsuitableTitle}</h2>{c.unsuitable.map(p=><p key={p}>{p}</p>)}</article></div></section>}

export function CharacterCreationSection(){return <section className="section character-section"><div className="container"><SectionHeading eyebrow="DAY 0 · CHARACTER CREATION" title="第 0 天｜先創建你的嘴饞角色" description="角色名稱是遊戲化引導；每張卡片同時保留原本的情緒性進食類型。完成測驗後，系統會依照結果安排破關路線。"/><div className="bonus-grid">{Object.values(cravingCharacters).map(item=><article className="bonus-card" key={item.typeKey}><div className="bonus-top"><span className="bonus-icon">{item.accentIcon}</span><small>{item.originalTypeName}</small></div><h3>{item.characterName}</h3><p>{item.characterDescription}</p><div className="bonus-value"><span>推薦路線</span><strong>{item.recommendedRoute}</strong></div></article>)}</div></div></section>}

export function ProductPreviewSection(){const previews=[{src:"/previews/action-workbook.png",title:"7 天嘴饞破關計畫",tag:"實際內頁"},{src:"/previews/quiz-guide.png",title:"第 0 天角色創建測驗",tag:"實際解讀頁"},{src:"/previews/drink-reset.png",title:"飲料降糖支線道具",tag:"實際填寫頁"}];return <section className="section preview-section"><div className="container"><SectionHeading eyebrow="不是一堆 PDF，而是一套破關系統" title="先看看你的任務道具會長什麼樣子" description="購買後可使用手機互動任務，也能保留 PDF 閱讀版。"/><div className="real-preview-grid">{previews.map(item=><article key={item.src}><div><Image src={item.src} alt={`${item.title}${item.tag}`} width={706} height={999} sizes="(max-width: 640px) 88vw, 30vw"/></div><span>{item.tag}</span><h3>{item.title}</h3></article>)}</div><p className="preview-note">每天只需要開啟當天任務需要的道具，不必一次看完所有內容。</p></div></section>}

export function TestimonialsSection(){return <section className="section testimonial-section"><div className="container"><SectionHeading eyebrow="工具如何進入真實生活" title="她們怎麼破關？" description="從原本卡住的關卡，到選擇真正適合自己的任務道具，每個人都可以從不同地方開始。"/><div className="testimonial-grid">{c.testimonials.map(item=><article key={item.name}><header><span>{item.name.slice(0,1)}</span><div><h3>{item.name}</h3><small>{item.meta}</small></div></header><blockquote>「{item.quote}」</blockquote><p><b>使用的任務道具</b><br/>{item.tools}</p><strong>{item.result}</strong></article>)}</div><p className="testimonial-disclaimer">{c.testimonialDisclaimer}</p></div></section>}

export function AddOnProductsSection(){return <section className="section addon-products-section"><div className="container"><SectionHeading eyebrow="卡關時可解鎖" title="兩項進階任務道具" description="主計畫已可完整破關；如果飲料或外食是最常卡住的地方，可額外解鎖更聚焦的攻略。"/><div className="addon-product-grid">{c.addOns.map((item,index)=><article key={item.name} className={index===0?"drink-addon":"meal-addon"}><span>{item.price}</span><h3>{item.name}</h3><p>{item.description}</p><ul>{item.features.map(x=><li key={x}>✓ {x}</li>)}</ul><a href="/checkout">前往結帳解鎖 →</a></article>)}</div></div></section>}

export function WhyItWorksSection(){return <section className="section why-section"><div className="container"><SectionHeading eyebrow="三個簡單步驟" title={c.whySection.title} description={c.whySection.intro}/><div className="why-grid">{c.why.map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0].split("：")[1]}</h3><p>{x[1]}</p></article>)}</div><p className="why-conclusion">{c.whySection.conclusion}</p></div></section>}

export function TrustFlowSection(){const steps=["購買後解鎖破關系統","第 0 天完成角色創建","每天完成一個今日關卡","收集線索、徽章與行動點數","第 7 關生成個人止損地圖"];return <section className="section trust-flow-section"><div className="container"><SectionHeading eyebrow="每天只做一件事" title="你的 7 天破關路線"/><div className="use-flow">{steps.map((x,i)=><article key={x}><span>{i+1}</span><p>{x}</p></article>)}</div><div className="brand-trust"><div className="brand-seal">可樂吉<br/><b>健康研究所</b></div><div><strong>{c.brand}</strong><p>一般健康教育與自我觀察工具 · 手機、電腦皆可使用 · 數位產品購買後立即取得</p></div></div></div></section>}

export function PricingSection(){return <section className="section pricing-section"><div className="container pricing-card"><div className="pricing-list"><span className="eyebrow light">今天就從一個小問題開始</span><h2>{c.offer.title}</h2><ul>{c.included.map(x=><li key={x}><span>✓</span>{x}</li>)}</ul></div><div className="pricing-action"><span className="save-tag">完整破關系統＋7 項日常道具</span><s>{c.offer.originalPrice}</s><strong>{c.offer.price}</strong><PrimaryCTA>{c.offer.cta}</PrimaryCTA><small>GoMyPay 安全付款 · 本站不儲存信用卡資料</small></div></div></section>}

export function FAQSection(){return <section className="section faq-section"><div className="container narrow"><SectionHeading eyebrow="購買前常見問題" title={c.faqTitle}/><div className="faq-list">{c.faqs.map((x,i)=><details key={x[0]}><summary><span>{String(i+1).padStart(2,"0")}</span>{x[0]}<i>＋</i></summary><p>{x[1]}</p></details>)}</div></div></section>}

export function SalesFooter(){return <><footer className="sales-footer"><div className="container footer-grid"><div><strong>{c.brand}</strong><p>{c.disclaimer}</p></div><div className="footer-contacts"><span>聯絡我們</span>{c.contacts.map(item=><a href={item.href} target="_blank" rel="noreferrer" key={item.label}><b>{item.label}</b><small>{item.handle} ↗</small></a>)}</div></div></footer><StickyCheckoutBar/></>}
