import Image from "next/image";
import { salesPage as c } from "@/content/emotionalEatingSalesPage";
import { PrimaryCTA, ProductBundleMockup, SectionHeading, StickyCheckoutBar, TrustPill } from "@/components/ui/BrandUI";
import SalesLeadForm from "@/app/sales/emotional-eating/SalesLeadForm";
import { cravingCharacters } from "@/content/cravingCharacters";

const painIcons=["月","夜","壓","飲","餓","撐"];
const bonusIcons=["心","析","營","救","飲","餐","換"];

export function HeroSection(){return <section className="hero-section"><div className="hero-orb"/><div className="container hero-grid"><div className="hero-copy"><div className="hero-badges"><TrustPill>互動破關系統</TrustPill><TrustPill>適合外食族</TrustPill><TrustPill>手機可玩</TrustPill></div><p className="hero-eyebrow">{c.hero.eyebrow}</p><h1>{c.hero.promise}</h1><h2 className="hero-question">{c.hero.title}</h2><p className="hero-subtitle">{c.hero.subtitle}</p><div className="hero-reward-tag">🎁 7 天破關完成後，還有神秘禮物等你解鎖</div><ul className="hero-game-highlights">{c.hero.gameHighlights.map(item=><li key={item}><span>✓</span>{item}</li>)}</ul><div className="hero-offer"><div><span className="original-price">原價 <s>{c.hero.originalPrice}</s></span><strong><small>今日體驗價</small>{c.hero.price}</strong></div><PrimaryCTA>{c.hero.cta}</PrimaryCTA></div><p className="microcopy">數位產品，非實體寄送 · 購買後立即取得</p></div><ProductBundleMockup/></div><div className="container trust-strip">{c.hero.trust.map(x=><div key={x}><span>✓</span>{x}</div>)}<div><span>♡</span>溫和調整，不靠極端節食</div></div></section>}

export function PainPointsSection(){return <section className="section pain-section"><div className="container"><SectionHeading eyebrow="下班後的熟悉循環" title={c.pain.title} description={c.pain.paragraphs.slice(0,2).join(" ")}/><div className="pain-grid">{c.pain.bullets.map((x,i)=><article className="pain-card" key={x}><span>{painIcons[i]}</span><p>{x}</p></article>)}</div><div className="story-callout"><span>「</span><div>{c.pain.paragraphs.slice(2).map(p=><p key={p}>{p}</p>)}</div></div></div></section>}

export function ProductBundleSection(){return <section className="section product-section"><div className="container product-grid"><div className="product-visual"><ProductBundleMockup/></div><div><SectionHeading align="left" eyebrow="不是另一份不能吃的規則" title={c.product.title} description={c.product.subtitle}/><span className="product-value">主商品 {c.product.value}</span><div className="product-copy">{c.product.paragraphs.map(p=><p key={p}>{p}</p>)}</div><PrimaryCTA>{c.product.cta}</PrimaryCTA></div></div></section>}

export function AudienceSection(){return <section className="section audience-section"><div className="container audience-grid"><article className="audience-card good"><span className="card-kicker">適合從小地方開始的你</span><h2>{c.audience.suitableTitle}</h2><ul>{c.suitable.map(x=><li key={x}><span>✓</span>{x}</li>)}</ul></article><article className="audience-card notice"><span className="card-kicker">一個溫柔但重要的提醒</span><h2>{c.audience.unsuitableTitle}</h2>{c.unsuitable.map(p=><p key={p}>{p}</p>)}</article></div></section>}

export function TimelineSection(){return <section className="section timeline-section"><div className="container"><SectionHeading eyebrow={c.mainProduct.eyebrow} title={c.mainProduct.title} description="每天 5–10 分鐘，從看懂模式，到建立自己的止損流程。"/><div className="timeline">{c.days.map((x,i)=>{const [day,title]=x.split("：");return <article key={x}><div className="day-dot">{i}</div><span>{day}</span><h3>{title}</h3><p>{i<3?"先看見觸發點，不急著要求自己立刻改變。":i<6?"把看見的模式，轉成生活中可執行的小步驟。":"整理個人止損地圖，完成最終挑戰。"}</p></article>})}</div><div className="timeline-reward"><b>🎁 完成第 7 關「迷霧核心」</b><p>除了生成自己的個人止損地圖，還會解鎖一份只有完成破關者才能領取的神秘禮物。</p></div></div></section>}

export function CharacterCreationSection(){return <section className="section character-section"><div className="container"><SectionHeading eyebrow="DAY 0 · CHARACTER CREATION" title="第 0 天｜先創建你的嘴饞角色" description="角色名稱是遊戲化引導；每張卡片同時保留原本的情緒性進食類型。完成測驗後，系統會依照結果安排破關路線。"/><div className="bonus-grid">{Object.values(cravingCharacters).map(item=><article className="bonus-card" key={item.typeKey}><div className="bonus-top"><span className="bonus-icon">{item.accentIcon}</span><small>{item.originalTypeName}</small></div><h3>{item.characterName}</h3><p>{item.characterDescription}</p><div className="bonus-value"><span>推薦路線</span><strong>{item.recommendedRoute}</strong></div></article>)}</div></div></section>}

export function ProductPreviewSection(){const previews=[{src:"/previews/action-workbook.png",title:"7 天嘴饞破關計畫",tag:"實際內頁"},{src:"/previews/quiz-guide.png",title:"第 0 天角色創建測驗",tag:"實際解讀頁"},{src:"/previews/drink-reset.png",title:"飲料降糖支線道具",tag:"實際填寫頁"}];return <section className="section preview-section"><div className="container"><SectionHeading eyebrow="不是一堆 PDF，而是一套破關系統" title="先看看你的任務道具會長什麼樣子" description="購買後可使用手機互動任務，也能保留 PDF 閱讀版。"/><div className="real-preview-grid">{previews.map(item=><article key={item.src}><div><Image src={item.src} alt={`${item.title}${item.tag}`} width={706} height={999} sizes="(max-width: 640px) 88vw, 30vw"/></div><span>{item.tag}</span><h3>{item.title}</h3></article>)}</div><p className="preview-note">每天只需要開啟當天任務需要的道具，不必一次看完所有內容。</p></div></section>}

export function TestimonialsSection(){return <section className="section testimonial-section"><div className="container"><SectionHeading eyebrow="工具如何進入真實生活" title="她們怎麼破關？" description="從原本卡住的關卡，到選擇真正適合自己的任務道具，每個人都可以從不同地方開始。"/><div className="testimonial-grid">{c.testimonials.map(item=><article key={item.name}><header><span>{item.name.slice(0,1)}</span><div><h3>{item.name}</h3><small>{item.meta}</small></div></header><blockquote>「{item.quote}」</blockquote><p><b>使用的任務道具</b><br/>{item.tools}</p><strong>{item.result}</strong></article>)}</div><p className="testimonial-disclaimer">{c.testimonialDisclaimer}</p></div></section>}

export function AddOnProductsSection(){return <section className="section addon-products-section"><div className="container"><SectionHeading eyebrow="卡關時可解鎖" title="兩項進階任務道具" description="主計畫已可完整破關；如果飲料或外食是最常卡住的地方，可額外解鎖更聚焦的攻略。"/><div className="addon-product-grid">{c.addOns.map((item,index)=><article key={item.name} className={index===0?"drink-addon":"meal-addon"}><span>{item.price}</span><h3>{item.name}</h3><p>{item.description}</p><ul>{item.features.map(x=><li key={x}>✓ {x}</li>)}</ul><a href="/checkout">前往結帳解鎖 →</a></article>)}</div></div></section>}

export function BonusGridSection(){return <section className="section bonus-section"><div className="container"><SectionHeading eyebrow="MISSION TOOLBOX" title="解鎖 7 項超實用解嘴饞道具" description="跟著關卡使用，也能在日常生活中依照自己的需要，單獨打開使用。"/><div className="bonus-grid">{c.bonuses.map((b,i)=><article className="bonus-card" key={b[0]}><div className="bonus-top"><span className="bonus-icon">{bonusIcons[i]}</span><small>TOOL {String(i+1).padStart(2,"0")}</small></div><h3>{b[0]}</h3><p>{b[1]}</p><div className="tool-format-tags"><span>📱 線上互動版</span><span>📄 PDF 使用版</span></div></article>)}</div><div className="value-stack"><div><span>完整任務道具箱</span><strong>7 項可反覆使用</strong></div><div><s>{c.offer.originalPrice}</s><strong>{c.offer.price}</strong></div></div></div></section>}

export function WhyItWorksSection(){return <section className="section why-section"><div className="container"><SectionHeading eyebrow="三個簡單步驟" title={c.whySection.title} description={c.whySection.intro}/><div className="why-grid">{c.why.map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0].split("：")[1]}</h3><p>{x[1]}</p></article>)}</div><p className="why-conclusion">{c.whySection.conclusion}</p></div></section>}

export function TrustFlowSection(){const steps=["購買後解鎖破關系統","第 0 天完成角色創建","每天完成一個今日關卡","收集線索、徽章與行動點數","第 7 關生成個人止損地圖"];return <section className="section trust-flow-section"><div className="container"><SectionHeading eyebrow="每天只做一件事" title="你的 7 天破關路線"/><div className="use-flow">{steps.map((x,i)=><article key={x}><span>{i+1}</span><p>{x}</p></article>)}</div><div className="brand-trust"><div className="brand-seal">可樂吉<br/><b>健康研究所</b></div><div><strong>{c.brand}</strong><p>一般健康教育與自我觀察工具 · 手機、電腦皆可使用 · 數位產品購買後立即取得</p></div></div></div></section>}

export function PricingSection(){return <section className="section pricing-section"><div className="container pricing-card"><div className="pricing-list"><span className="eyebrow light">今天就從一個小問題開始</span><h2>{c.offer.title}</h2><ul>{c.included.map(x=><li key={x}><span>✓</span>{x}</li>)}</ul></div><div className="pricing-action"><span className="save-tag">完整破關系統＋7 項日常道具</span><s>{c.offer.originalPrice}</s><strong>{c.offer.price}</strong><PrimaryCTA>{c.offer.cta}</PrimaryCTA><small>GoMyPay 安全付款 · 本站不儲存信用卡資料</small></div></div></section>}

export function FAQSection(){return <section className="section faq-section"><div className="container narrow"><SectionHeading eyebrow="購買前常見問題" title={c.faqTitle}/><div className="faq-list">{c.faqs.map((x,i)=><details key={x[0]}><summary><span>{String(i+1).padStart(2,"0")}</span>{x[0]}<i>＋</i></summary><p>{x[1]}</p></details>)}</div></div></section>}

export function CheckoutLeadSection(){return <section className="section lead-section"><div className="container lead-grid"><div><SectionHeading align="left" eyebrow="你的角色，正在等待創建" title={c.finalCta.title} description={c.finalCta.note}/><div className="final-adventure-flow"><span>創建角色</span><i>→</i><span>穿越 7 關</span><i>→</i><span>解鎖 7 種道具</span><i>→</i><span>領取神秘禮物</span></div><p className="final-reward-note">🎁 完成第 7 關後，神秘禮物正式解鎖</p><div className="mini-trust"><span>✓ 購買後立即取得</span><span>✓ 手機與電腦皆可使用</span><span>✓ GoMyPay 安全付款</span></div></div><SalesLeadForm/></div></section>}

export function SalesFooter(){return <><footer className="sales-footer"><div className="container footer-grid"><div><strong>{c.brand}</strong><p>{c.disclaimer}</p></div><div className="footer-contacts"><span>聯絡我們</span>{c.contacts.map(item=><a href={item.href} target="_blank" rel="noreferrer" key={item.label}><b>{item.label}</b><small>{item.handle} ↗</small></a>)}</div></div></footer><StickyCheckoutBar/></>}
