import {PrimaryCTA,SectionHeading} from "@/components/ui/BrandUI";
import {salesPageAssets} from "@/content/salesPageAssets";
import SalesAssetImage from "./SalesAssetImage";
import MysteryRewardCard from "./MysteryRewardCard";

export function MistKingdomSection(){const flow=["創建角色","進入迷霧王國","穿越 7 個關卡","解鎖 7 種任務道具","完成迷霧核心","解鎖神秘禮物"];return <section className="section mist-kingdom-section"><div className="container mist-kingdom-grid"><div className="mist-cover"><SalesAssetImage src={salesPageAssets.mistKingdomCover} alt="7 天嘴饞破關計畫迷霧王國 RPG 遊戲封面" label="迷霧王國 RPG 遊戲封面"/></div><div className="mist-copy"><span>歡迎進入｜迷霧王國</span><h2>你的 7 天破關旅程，即將開始</h2><p>在迷霧王國裡，很多人每天都會被同樣的迷霧困住。下午想喝手搖飲、下班後突然很想吃、壓力大想找甜食、晚餐後坐上沙發就開始嘴饞。</p><p>你可能以為自己需要更多自制力。但在這場冒險裡，你的任務，是一步一步收集線索，找出每次迷霧出現的時間、場景、情緒與飲食缺口。</p><p>你會先創建自己的嘴饞角色，接著穿越 7 個關卡、解鎖 7 種日常任務道具，最後進入「迷霧核心」。完成最後一關後，你將生成自己的個人止損地圖，並解鎖只有完成破關者才能領取的神秘禮物。</p><div className="mist-flow">{flow.map((item,index)=><div key={item}><b>{item}</b>{index<flow.length-1&&<span>→</span>}</div>)}</div><MysteryRewardCard/></div></div></section>}

export function CreatorStorySection(){return <section className="section creator-story"><div className="container creator-grid"><div className="creator-photo"><SalesAssetImage src={salesPageAssets.creator.image} alt="崇銘老師人物照片" label="崇銘老師真人照片"/><span><b>崇銘老師</b><br/>可樂吉健康研究所</span></div><div className="creator-copy"><SectionHeading align="left" eyebrow="ABOUT THE CREATOR" title="這套破關計畫，是誰設計的？" description="從工程師到體態管理教練，把『找問題、拆問題、建立流程』的習慣，帶進體態管理。"/><h3>你好，我是崇銘老師。</h3><p>我是可樂吉健康研究所的體態管理教練。在進入健康產業以前，我曾經是一名工程師。過去的工作，讓我很習慣不急著只看表面，而是找出問題何時發生、哪些條件讓它反覆出現，以及能不能拆成一個個可以處理的步驟。</p><p>後來陪伴上班族、外食族與忙碌女性調整體態，我發現嘴饞也很像一個需要拆解的問題。真正困難的，往往是下午累到想喝飲料、下班後餓到什麼都想吃，或晚上坐上沙發就習慣打開零食的那個瞬間。</p><p>一層一層往下找，經常會看見時間、場景、壓力、疲憊、營養不足、情緒補償與重複太久的習慣。於是，我把工程師的系統思考和第一線陪伴經驗結合，開發《7 天嘴饞破關計畫》。</p><blockquote>嘴饞不是一個單一問題。<br/>它更像一套由時間、場景、情緒、疲憊、營養與習慣組成的系統。<small>找到系統裡最常出錯的地方，才比較知道下一步要從哪裡調整。</small></blockquote><strong className="creator-brand-line">我不想再只告訴你「不要吃」。我更想陪你找出：為什麼每次都在同一個地方卡住。</strong></div></div></section>}

export function WhyJourneySection(){const stages=["時間迷霧","場景迷宮","情緒之門","支線岔路","補給裂縫","晚餐防線","迷霧核心"];return <section className="section why-journey"><div className="container narrow"><SectionHeading eyebrow="FROM KNOWING TO USING" title="為什麼我要把嘴饞，做成一場 7 天破關旅程？"/><div className="journey-copy"><p>很多減脂工具，看完時很有道理，真正嘴饞的那一刻卻還是不知道該做什麼。所以這次，我不想只做一份讓你「閱讀」的教材。</p><p>我希望你能在下午想喝手搖飲、下班後很餓、壓力大想吃甜食，或不知道晚餐怎麼選時，直接打開工具使用；失控之後，也能回頭找線索，而不是只剩下責備。</p></div><div className="journey-stages">{stages.map((x,i)=><span key={x}><b>{i+1}</b>{x}</span>)}</div><p className="journey-highlight">下一次嘴饞再出現時，你會比以前多一個選擇。</p></div></section>}

export function UsageModesSection(){const situations=[["今天壓力很大","3 分鐘身心連結"],["晚上突然想吃","10 分鐘嘴饞急救流程"],["每天下午想喝飲料","7 天含糖飲料重置"],["下班後常失控","嘴饞觸發點分析表"],["最近晚上特別餓","白天營養缺口掃描"]];return <section className="section usage-modes"><div className="container"><SectionHeading eyebrow="ONE SYSTEM · THREE WAYS" title="一套計畫，依照你現在的需要使用" description="完整破關、單項救援，或進一步延伸到飲料與外食情境。"/><div className="usage-layer-grid"><article><span>01</span><h3>完整破關</h3><p>第 0 天創建角色，完成 7 個關卡、收集成就徽章、生成個人止損地圖，並解鎖神秘禮物。</p></article><article><span>02</span><h3>單一道具救援</h3><p>不必照順序。壓力、晚間嘴饞、飲料或營養問題出現時，直接打開 7 種道具中的一項。</p></article><article><span>03</span><h3>進階生活應用</h3><p>想把方法帶進手搖飲與外食場景，可以再使用兩項進階任務道具。</p></article></div><div className="format-cards"><article><b>📱 線上互動版</b><p>直接用手機完成選擇、評分、記錄與互動分析，適合嘴饞當下快速使用。</p></article><article><b>📄 PDF 使用版</b><p>可以閱讀、收藏或列印手寫，適合長期紀錄與習慣紙本操作的人。</p></article></div><div className="usage-emphasis"><strong>你不一定要把它當成遊戲。</strong><p>想完整體驗，可以從第 0 天一路破關；只想先處理一個問題，也可以直接打開需要的工具。</p></div><div className="situation-grid">{situations.map(x=><article key={x[0]}><span>{x[0]}</span><b>→ {x[1]}</b></article>)}</div><p className="usage-closing">這 7 項工具不是只有破關時能用。完成 7 天後，依然可以在真實生活中反覆打開救援。</p></div></section>}

export function ToolPreviewSection(){const order=["body-mind","trigger-analysis","nutrition-scan","emergency-flow","drink-reset"],tools=order.map(id=>salesPageAssets.tools.find(tool=>tool.id===id)).filter(Boolean) as typeof salesPageAssets.tools;return <section className="section tool-showcase"><div className="container"><SectionHeading eyebrow="PDF＋MOBILE" title="每個任務道具，都有互動版與 PDF 版" description="手機直接操作，也能下載保存、閱讀或列印使用。"/><p className="showcase-intro">跟著 7 天流程，可以一步一步找出模式；如果只想先處理其中一個問題，也能直接打開需要的任務道具。</p><div className="tool-preview-list">{tools.map((tool,index)=><article className="tool-preview-card" key={tool.id}><div className="tool-preview-copy"><span>TOOL {String(index+1).padStart(2,"0")}</span><h3>{tool.name}</h3><strong>{tool.core}</strong><p>{tool.description}</p><ul>{tool.bullets.map(x=><li key={x}>✓ {x}</li>)}</ul><small>適合使用時機</small><p>{tool.usage}</p><div><b>📱 {tool.mobileLabel}</b><b>📄 {tool.pdfLabel}</b></div></div><div className="tool-preview-visual"><div className="pdf-mock"><span>PDF</span><SalesAssetImage src={tool.pdfImage} alt={`${tool.name} PDF 預覽`} label={`${tool.name} PDF 預覽`}/></div><div className="mobile-mock"><span>MOBILE</span><SalesAssetImage src={tool.mobileImage} alt={`${tool.name}手機互動版`} label={`${tool.name}手機截圖`}/></div></div></article>)}</div></div></section>}

export function PurchaseStartSection(){const steps=[["完成付款","立即取得數位工具包，不需等待實體寄送。"],["創建嘴饞角色","完成第 0 天情緒性進食 6 型測驗。"],["開始今日關卡","每天完成一個約 5～10 分鐘的互動任務。"],["解鎖徽章與任務道具","看見自己的時間、場景、情緒與營養模式。"],["生成個人止損地圖","完成第 7 關，整理接下來的行動方向。"],["完成破關，領取神秘好禮","完成迷霧核心後，個人止損地圖正式生成，同時解鎖神秘禮物。"]];return <section className="section purchase-start"><div className="container"><SectionHeading eyebrow="START HERE" title="購買後，我要怎麼開始？"/><div className="purchase-step-grid">{steps.map((x,i)=><article className={i===5?"reward-step":""} key={x[0]}><span>STEP {i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p>{i===5&&<b>🎁 神秘禮物｜完成第 7 關後解鎖</b>}</article>)}</div><p>如果不想按照 7 天順序，也可以直接打開需要的任務道具使用。</p><PrimaryCTA>開始我的 7 天破關旅程</PrimaryCTA></div></section>}

export function AdvancedToolsSection(){const details=[{name:"含糖飲料替換清單 Pro",subtitle:"把『我要戒飲料』變成『我知道下一杯怎麼點』。",items:["手搖飲風險、杯型與糖度判讀","加料、奶茶與咖啡替換","超商飲料與點餐話術"],scenes:["珍奶 → 小杯、微糖、不加料","甜咖啡 → 無糖拿鐵＋穩定點心","超商甜飲 → 無糖茶或豆漿"]},{name:"外食補給導航 Pro",subtitle:"不是固定菜單，而是到不同地方都知道這餐缺什麼。",items:["超商、早餐店、便當店與麵店","滷味、自助餐、火鍋與外送","依很累、很餓、很趕提供補法"],scenes:["蛋餅 → 補無糖豆漿或蛋","一碗麵 → 加燙青菜與蛋白質","超商 → 蛋白質＋主食＋無糖飲"]}];return <section className="section advanced-tools"><div className="container"><SectionHeading eyebrow="ADVANCED TOOLS" title="想把破關方法帶進更多生活場景？" description="完成基礎任務後，也可以解鎖兩項進階任務道具。"/><div className="advanced-grid">{details.map((tool,i)=>{const asset=salesPageAssets.proTools[i];return <article key={tool.name}><span>進階任務道具 0{i+1}</span><h3>{tool.name}</h3><strong>{tool.subtitle}</strong><ul>{tool.items.map(x=><li key={x}>✓ {x}</li>)}</ul><div className="advanced-scenes">{tool.scenes.map(x=><p key={x}>{x}</p>)}</div><div className="advanced-preview"><div><b>📄 PDF 版</b><SalesAssetImage src={asset.pdfImage} alt={`${tool.name} PDF 預覽`} label={`${tool.name} PDF 預覽`}/></div><div><b>📱 線上互動版</b><SalesAssetImage src={asset.mobileImage} alt={`${tool.name}手機版預覽`} label={`${tool.name}手機截圖`}/></div></div></article>})}</div><p className="advanced-closing">兩項進階工具都提供線上互動版與 PDF 閱讀／列印版，可以依照當下場景直接打開使用。</p></div></section>}
